// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

// Enclosing macro to prevent multiple inclusion
#ifndef __CONNECT_EVENTS__
#define __CONNECT_EVENTS__


// Generated events.
#include PLATFORM_HEADER
#include "stack/include/ember-types.h"
#include "hal/hal.h"


void emberAfPluginHeartbeatEventHandler(void);
extern EmberEventControl emberAfPluginHeartbeatEventControl;

void emberAfPluginPollEventHandler(void);
extern EmberEventControl emberAfPluginPollEventControl;

void adcHandler(void);
extern EmberEventControl adcEventControl;

const EmberEventData emAppEvents[] = {
  {&emberAfPluginHeartbeatEventControl, emberAfPluginHeartbeatEventHandler},
  {&emberAfPluginPollEventControl, emberAfPluginPollEventHandler},
  {&adcEventControl, adcHandler},
  {NULL, NULL}
};
#endif // __CONNECT_EVENTS__
