
__all__ = [ 'RM_Peripheral_LDMA' ]

from static import Base_RM_Peripheral
from LDMA_register import *

class RM_Peripheral_LDMA(Base_RM_Peripheral):
    def __init__(self, rmio, label):
        self.__dict__['zz_frozen'] = False
        super(RM_Peripheral_LDMA, self).__init__(rmio, label,
            0x400E2000, 'LDMA',
            "")
        self.CTRL = RM_Register_LDMA_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL'] = self.CTRL
        self.STATUS = RM_Register_LDMA_STATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS'] = self.STATUS
        self.SYNC = RM_Register_LDMA_SYNC(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNC'] = self.SYNC
        self.CHEN = RM_Register_LDMA_CHEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHEN'] = self.CHEN
        self.CHBUSY = RM_Register_LDMA_CHBUSY(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHBUSY'] = self.CHBUSY
        self.CHDONE = RM_Register_LDMA_CHDONE(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHDONE'] = self.CHDONE
        self.DBGHALT = RM_Register_LDMA_DBGHALT(self.zz_rmio, self.zz_label)
        self.zz_rdict['DBGHALT'] = self.DBGHALT
        self.SWREQ = RM_Register_LDMA_SWREQ(self.zz_rmio, self.zz_label)
        self.zz_rdict['SWREQ'] = self.SWREQ
        self.REQDIS = RM_Register_LDMA_REQDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['REQDIS'] = self.REQDIS
        self.REQPEND = RM_Register_LDMA_REQPEND(self.zz_rmio, self.zz_label)
        self.zz_rdict['REQPEND'] = self.REQPEND
        self.LINKLOAD = RM_Register_LDMA_LINKLOAD(self.zz_rmio, self.zz_label)
        self.zz_rdict['LINKLOAD'] = self.LINKLOAD
        self.REQCLEAR = RM_Register_LDMA_REQCLEAR(self.zz_rmio, self.zz_label)
        self.zz_rdict['REQCLEAR'] = self.REQCLEAR
        self.IF = RM_Register_LDMA_IF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IF'] = self.IF
        self.IFS = RM_Register_LDMA_IFS(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFS'] = self.IFS
        self.IFC = RM_Register_LDMA_IFC(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFC'] = self.IFC
        self.IEN = RM_Register_LDMA_IEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['IEN'] = self.IEN
        self.CH0_REQSEL = RM_Register_LDMA_CH0_REQSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH0_REQSEL'] = self.CH0_REQSEL
        self.CH0_CFG = RM_Register_LDMA_CH0_CFG(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH0_CFG'] = self.CH0_CFG
        self.CH0_LOOP = RM_Register_LDMA_CH0_LOOP(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH0_LOOP'] = self.CH0_LOOP
        self.CH0_CTRL = RM_Register_LDMA_CH0_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH0_CTRL'] = self.CH0_CTRL
        self.CH0_SRC = RM_Register_LDMA_CH0_SRC(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH0_SRC'] = self.CH0_SRC
        self.CH0_DST = RM_Register_LDMA_CH0_DST(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH0_DST'] = self.CH0_DST
        self.CH0_LINK = RM_Register_LDMA_CH0_LINK(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH0_LINK'] = self.CH0_LINK
        self.CH1_REQSEL = RM_Register_LDMA_CH1_REQSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH1_REQSEL'] = self.CH1_REQSEL
        self.CH1_CFG = RM_Register_LDMA_CH1_CFG(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH1_CFG'] = self.CH1_CFG
        self.CH1_LOOP = RM_Register_LDMA_CH1_LOOP(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH1_LOOP'] = self.CH1_LOOP
        self.CH1_CTRL = RM_Register_LDMA_CH1_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH1_CTRL'] = self.CH1_CTRL
        self.CH1_SRC = RM_Register_LDMA_CH1_SRC(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH1_SRC'] = self.CH1_SRC
        self.CH1_DST = RM_Register_LDMA_CH1_DST(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH1_DST'] = self.CH1_DST
        self.CH1_LINK = RM_Register_LDMA_CH1_LINK(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH1_LINK'] = self.CH1_LINK
        self.CH2_REQSEL = RM_Register_LDMA_CH2_REQSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH2_REQSEL'] = self.CH2_REQSEL
        self.CH2_CFG = RM_Register_LDMA_CH2_CFG(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH2_CFG'] = self.CH2_CFG
        self.CH2_LOOP = RM_Register_LDMA_CH2_LOOP(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH2_LOOP'] = self.CH2_LOOP
        self.CH2_CTRL = RM_Register_LDMA_CH2_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH2_CTRL'] = self.CH2_CTRL
        self.CH2_SRC = RM_Register_LDMA_CH2_SRC(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH2_SRC'] = self.CH2_SRC
        self.CH2_DST = RM_Register_LDMA_CH2_DST(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH2_DST'] = self.CH2_DST
        self.CH2_LINK = RM_Register_LDMA_CH2_LINK(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH2_LINK'] = self.CH2_LINK
        self.CH3_REQSEL = RM_Register_LDMA_CH3_REQSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH3_REQSEL'] = self.CH3_REQSEL
        self.CH3_CFG = RM_Register_LDMA_CH3_CFG(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH3_CFG'] = self.CH3_CFG
        self.CH3_LOOP = RM_Register_LDMA_CH3_LOOP(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH3_LOOP'] = self.CH3_LOOP
        self.CH3_CTRL = RM_Register_LDMA_CH3_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH3_CTRL'] = self.CH3_CTRL
        self.CH3_SRC = RM_Register_LDMA_CH3_SRC(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH3_SRC'] = self.CH3_SRC
        self.CH3_DST = RM_Register_LDMA_CH3_DST(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH3_DST'] = self.CH3_DST
        self.CH3_LINK = RM_Register_LDMA_CH3_LINK(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH3_LINK'] = self.CH3_LINK
        self.CH4_REQSEL = RM_Register_LDMA_CH4_REQSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH4_REQSEL'] = self.CH4_REQSEL
        self.CH4_CFG = RM_Register_LDMA_CH4_CFG(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH4_CFG'] = self.CH4_CFG
        self.CH4_LOOP = RM_Register_LDMA_CH4_LOOP(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH4_LOOP'] = self.CH4_LOOP
        self.CH4_CTRL = RM_Register_LDMA_CH4_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH4_CTRL'] = self.CH4_CTRL
        self.CH4_SRC = RM_Register_LDMA_CH4_SRC(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH4_SRC'] = self.CH4_SRC
        self.CH4_DST = RM_Register_LDMA_CH4_DST(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH4_DST'] = self.CH4_DST
        self.CH4_LINK = RM_Register_LDMA_CH4_LINK(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH4_LINK'] = self.CH4_LINK
        self.CH5_REQSEL = RM_Register_LDMA_CH5_REQSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH5_REQSEL'] = self.CH5_REQSEL
        self.CH5_CFG = RM_Register_LDMA_CH5_CFG(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH5_CFG'] = self.CH5_CFG
        self.CH5_LOOP = RM_Register_LDMA_CH5_LOOP(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH5_LOOP'] = self.CH5_LOOP
        self.CH5_CTRL = RM_Register_LDMA_CH5_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH5_CTRL'] = self.CH5_CTRL
        self.CH5_SRC = RM_Register_LDMA_CH5_SRC(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH5_SRC'] = self.CH5_SRC
        self.CH5_DST = RM_Register_LDMA_CH5_DST(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH5_DST'] = self.CH5_DST
        self.CH5_LINK = RM_Register_LDMA_CH5_LINK(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH5_LINK'] = self.CH5_LINK
        self.CH6_REQSEL = RM_Register_LDMA_CH6_REQSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH6_REQSEL'] = self.CH6_REQSEL
        self.CH6_CFG = RM_Register_LDMA_CH6_CFG(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH6_CFG'] = self.CH6_CFG
        self.CH6_LOOP = RM_Register_LDMA_CH6_LOOP(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH6_LOOP'] = self.CH6_LOOP
        self.CH6_CTRL = RM_Register_LDMA_CH6_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH6_CTRL'] = self.CH6_CTRL
        self.CH6_SRC = RM_Register_LDMA_CH6_SRC(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH6_SRC'] = self.CH6_SRC
        self.CH6_DST = RM_Register_LDMA_CH6_DST(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH6_DST'] = self.CH6_DST
        self.CH6_LINK = RM_Register_LDMA_CH6_LINK(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH6_LINK'] = self.CH6_LINK
        self.CH7_REQSEL = RM_Register_LDMA_CH7_REQSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH7_REQSEL'] = self.CH7_REQSEL
        self.CH7_CFG = RM_Register_LDMA_CH7_CFG(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH7_CFG'] = self.CH7_CFG
        self.CH7_LOOP = RM_Register_LDMA_CH7_LOOP(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH7_LOOP'] = self.CH7_LOOP
        self.CH7_CTRL = RM_Register_LDMA_CH7_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH7_CTRL'] = self.CH7_CTRL
        self.CH7_SRC = RM_Register_LDMA_CH7_SRC(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH7_SRC'] = self.CH7_SRC
        self.CH7_DST = RM_Register_LDMA_CH7_DST(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH7_DST'] = self.CH7_DST
        self.CH7_LINK = RM_Register_LDMA_CH7_LINK(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH7_LINK'] = self.CH7_LINK
        self.__dict__['zz_frozen'] = True