
__all__ = [ 'RM_Peripheral_EMU' ]

from static import Base_RM_Peripheral
from EMU_register import *

class RM_Peripheral_EMU(Base_RM_Peripheral):
    def __init__(self, rmio, label):
        self.__dict__['zz_frozen'] = False
        super(RM_Peripheral_EMU, self).__init__(rmio, label,
            0x400E3000, 'EMU',
            "")
        self.CTRL = RM_Register_EMU_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL'] = self.CTRL
        self.STATUS = RM_Register_EMU_STATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS'] = self.STATUS
        self.LOCK = RM_Register_EMU_LOCK(self.zz_rmio, self.zz_label)
        self.zz_rdict['LOCK'] = self.LOCK
        self.RAM0CTRL = RM_Register_EMU_RAM0CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAM0CTRL'] = self.RAM0CTRL
        self.CMD = RM_Register_EMU_CMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['CMD'] = self.CMD
        self.PERACTCONF = RM_Register_EMU_PERACTCONF(self.zz_rmio, self.zz_label)
        self.zz_rdict['PERACTCONF'] = self.PERACTCONF
        self.EM4CTRL = RM_Register_EMU_EM4CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['EM4CTRL'] = self.EM4CTRL
        self.TEMPLIMITS = RM_Register_EMU_TEMPLIMITS(self.zz_rmio, self.zz_label)
        self.zz_rdict['TEMPLIMITS'] = self.TEMPLIMITS
        self.TEMP = RM_Register_EMU_TEMP(self.zz_rmio, self.zz_label)
        self.zz_rdict['TEMP'] = self.TEMP
        self.IF = RM_Register_EMU_IF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IF'] = self.IF
        self.IFS = RM_Register_EMU_IFS(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFS'] = self.IFS
        self.IFC = RM_Register_EMU_IFC(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFC'] = self.IFC
        self.IEN = RM_Register_EMU_IEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['IEN'] = self.IEN
        self.PWRLOCK = RM_Register_EMU_PWRLOCK(self.zz_rmio, self.zz_label)
        self.zz_rdict['PWRLOCK'] = self.PWRLOCK
        self.PWRCFG = RM_Register_EMU_PWRCFG(self.zz_rmio, self.zz_label)
        self.zz_rdict['PWRCFG'] = self.PWRCFG
        self.PWRCTRL = RM_Register_EMU_PWRCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PWRCTRL'] = self.PWRCTRL
        self.DCDCCTRL = RM_Register_EMU_DCDCCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCCTRL'] = self.DCDCCTRL
        self.DCDCSMCTRL = RM_Register_EMU_DCDCSMCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCSMCTRL'] = self.DCDCSMCTRL
        self.DCDCSWCTRL = RM_Register_EMU_DCDCSWCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCSWCTRL'] = self.DCDCSWCTRL
        self.DCDCMISCCTRL = RM_Register_EMU_DCDCMISCCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCMISCCTRL'] = self.DCDCMISCCTRL
        self.DCDCZDETCTRL = RM_Register_EMU_DCDCZDETCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCZDETCTRL'] = self.DCDCZDETCTRL
        self.DCDCCLIMCTRL = RM_Register_EMU_DCDCCLIMCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCCLIMCTRL'] = self.DCDCCLIMCTRL
        self.DCDCLNCOMPCTRL = RM_Register_EMU_DCDCLNCOMPCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCLNCOMPCTRL'] = self.DCDCLNCOMPCTRL
        self.DCDCLNVCTRL = RM_Register_EMU_DCDCLNVCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCLNVCTRL'] = self.DCDCLNVCTRL
        self.DCDCTIMING = RM_Register_EMU_DCDCTIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCTIMING'] = self.DCDCTIMING
        self.DCDCLPVCTRL = RM_Register_EMU_DCDCLPVCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCLPVCTRL'] = self.DCDCLPVCTRL
        self.DCDCLPFREQCTRL = RM_Register_EMU_DCDCLPFREQCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCLPFREQCTRL'] = self.DCDCLPFREQCTRL
        self.DCDCLPCTRL = RM_Register_EMU_DCDCLPCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCLPCTRL'] = self.DCDCLPCTRL
        self.DCDCLNFREQCTRL = RM_Register_EMU_DCDCLNFREQCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCLNFREQCTRL'] = self.DCDCLNFREQCTRL
        self.DCDCRCOSC = RM_Register_EMU_DCDCRCOSC(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCRCOSC'] = self.DCDCRCOSC
        self.DCDCSYNC = RM_Register_EMU_DCDCSYNC(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCSYNC'] = self.DCDCSYNC
        self.DCDCSTATUS = RM_Register_EMU_DCDCSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCSTATUS'] = self.DCDCSTATUS
        self.DCDCTRIM0 = RM_Register_EMU_DCDCTRIM0(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCTRIM0'] = self.DCDCTRIM0
        self.DCDCTRIM1 = RM_Register_EMU_DCDCTRIM1(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCTRIM1'] = self.DCDCTRIM1
        self.DCDCTEST = RM_Register_EMU_DCDCTEST(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCTEST'] = self.DCDCTEST
        self.VMONCTRL = RM_Register_EMU_VMONCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['VMONCTRL'] = self.VMONCTRL
        self.VMONAVDDCTRL = RM_Register_EMU_VMONAVDDCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['VMONAVDDCTRL'] = self.VMONAVDDCTRL
        self.VMONALTAVDDCTRL = RM_Register_EMU_VMONALTAVDDCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['VMONALTAVDDCTRL'] = self.VMONALTAVDDCTRL
        self.VMONDVDDCTRL = RM_Register_EMU_VMONDVDDCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['VMONDVDDCTRL'] = self.VMONDVDDCTRL
        self.VMONIO0CTRL = RM_Register_EMU_VMONIO0CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['VMONIO0CTRL'] = self.VMONIO0CTRL
        self.VMONFVDDCTRL = RM_Register_EMU_VMONFVDDCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['VMONFVDDCTRL'] = self.VMONFVDDCTRL
        self.SGLNAMIXCTRL = RM_Register_EMU_SGLNAMIXCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['SGLNAMIXCTRL'] = self.SGLNAMIXCTRL
        self.RAM1CTRL = RM_Register_EMU_RAM1CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAM1CTRL'] = self.RAM1CTRL
        self.RAM2CTRL = RM_Register_EMU_RAM2CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAM2CTRL'] = self.RAM2CTRL
        self.STATEDLY2 = RM_Register_EMU_STATEDLY2(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATEDLY2'] = self.STATEDLY2
        self.DCDCLPEM01CFG = RM_Register_EMU_DCDCLPEM01CFG(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCLPEM01CFG'] = self.DCDCLPEM01CFG
        self.DCDCPRSSEL = RM_Register_EMU_DCDCPRSSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DCDCPRSSEL'] = self.DCDCPRSSEL
        self.EM23PERNORETAINCMD = RM_Register_EMU_EM23PERNORETAINCMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['EM23PERNORETAINCMD'] = self.EM23PERNORETAINCMD
        self.EM23PERNORETAINSTATUS = RM_Register_EMU_EM23PERNORETAINSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['EM23PERNORETAINSTATUS'] = self.EM23PERNORETAINSTATUS
        self.EM23PERNORETAINCTRL = RM_Register_EMU_EM23PERNORETAINCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['EM23PERNORETAINCTRL'] = self.EM23PERNORETAINCTRL
        self.AUXCTRL0 = RM_Register_EMU_AUXCTRL0(self.zz_rmio, self.zz_label)
        self.zz_rdict['AUXCTRL0'] = self.AUXCTRL0
        self.AUXCTRL1 = RM_Register_EMU_AUXCTRL1(self.zz_rmio, self.zz_label)
        self.zz_rdict['AUXCTRL1'] = self.AUXCTRL1
        self.AUXCTRL2 = RM_Register_EMU_AUXCTRL2(self.zz_rmio, self.zz_label)
        self.zz_rdict['AUXCTRL2'] = self.AUXCTRL2
        self.PORBOD = RM_Register_EMU_PORBOD(self.zz_rmio, self.zz_label)
        self.zz_rdict['PORBOD'] = self.PORBOD
        self.PORBODREFRESH = RM_Register_EMU_PORBODREFRESH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PORBODREFRESH'] = self.PORBODREFRESH
        self.PORBODOVERRIDE = RM_Register_EMU_PORBODOVERRIDE(self.zz_rmio, self.zz_label)
        self.zz_rdict['PORBODOVERRIDE'] = self.PORBODOVERRIDE
        self.BODCONF = RM_Register_EMU_BODCONF(self.zz_rmio, self.zz_label)
        self.zz_rdict['BODCONF'] = self.BODCONF
        self.FLASHBOD = RM_Register_EMU_FLASHBOD(self.zz_rmio, self.zz_label)
        self.zz_rdict['FLASHBOD'] = self.FLASHBOD
        self.DECBOD = RM_Register_EMU_DECBOD(self.zz_rmio, self.zz_label)
        self.zz_rdict['DECBOD'] = self.DECBOD
        self.BIASCONF = RM_Register_EMU_BIASCONF(self.zz_rmio, self.zz_label)
        self.zz_rdict['BIASCONF'] = self.BIASCONF
        self.BIASABSTRIM = RM_Register_EMU_BIASABSTRIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['BIASABSTRIM'] = self.BIASABSTRIM
        self.BIASTEMPTRIM = RM_Register_EMU_BIASTEMPTRIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['BIASTEMPTRIM'] = self.BIASTEMPTRIM
        self.BIASTRIM = RM_Register_EMU_BIASTRIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['BIASTRIM'] = self.BIASTRIM
        self.BIASPERIOD = RM_Register_EMU_BIASPERIOD(self.zz_rmio, self.zz_label)
        self.zz_rdict['BIASPERIOD'] = self.BIASPERIOD
        self.DREGCALIB = RM_Register_EMU_DREGCALIB(self.zz_rmio, self.zz_label)
        self.zz_rdict['DREGCALIB'] = self.DREGCALIB
        self.DREGOVERRIDE = RM_Register_EMU_DREGOVERRIDE(self.zz_rmio, self.zz_label)
        self.zz_rdict['DREGOVERRIDE'] = self.DREGOVERRIDE
        self.RAM0FEATURE = RM_Register_EMU_RAM0FEATURE(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAM0FEATURE'] = self.RAM0FEATURE
        self.STATEDLY0 = RM_Register_EMU_STATEDLY0(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATEDLY0'] = self.STATEDLY0
        self.STATEDLY1 = RM_Register_EMU_STATEDLY1(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATEDLY1'] = self.STATEDLY1
        self.VMONCONF = RM_Register_EMU_VMONCONF(self.zz_rmio, self.zz_label)
        self.zz_rdict['VMONCONF'] = self.VMONCONF
        self.TESTLOCK = RM_Register_EMU_TESTLOCK(self.zz_rmio, self.zz_label)
        self.zz_rdict['TESTLOCK'] = self.TESTLOCK
        self.SCANCTRL = RM_Register_EMU_SCANCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['SCANCTRL'] = self.SCANCTRL
        self.TESTCTRL = RM_Register_EMU_TESTCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['TESTCTRL'] = self.TESTCTRL
        self.BIASTESTCTRL = RM_Register_EMU_BIASTESTCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['BIASTESTCTRL'] = self.BIASTESTCTRL
        self.TESTCTRLANAISO = RM_Register_EMU_TESTCTRLANAISO(self.zz_rmio, self.zz_label)
        self.zz_rdict['TESTCTRLANAISO'] = self.TESTCTRLANAISO
        self.EM01COUNTERWAIT = RM_Register_EMU_EM01COUNTERWAIT(self.zz_rmio, self.zz_label)
        self.zz_rdict['EM01COUNTERWAIT'] = self.EM01COUNTERWAIT
        self.RAM1FEATURE = RM_Register_EMU_RAM1FEATURE(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAM1FEATURE'] = self.RAM1FEATURE
        self.RAM2FEATURE = RM_Register_EMU_RAM2FEATURE(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAM2FEATURE'] = self.RAM2FEATURE
        self.RAMBIASCONF = RM_Register_EMU_RAMBIASCONF(self.zz_rmio, self.zz_label)
        self.zz_rdict['RAMBIASCONF'] = self.RAMBIASCONF
        self.TGTRAMRM = RM_Register_EMU_TGTRAMRM(self.zz_rmio, self.zz_label)
        self.zz_rdict['TGTRAMRM'] = self.TGTRAMRM
        self.TGTDECBODTHR = RM_Register_EMU_TGTDECBODTHR(self.zz_rmio, self.zz_label)
        self.zz_rdict['TGTDECBODTHR'] = self.TGTDECBODTHR
        self.TGTHDREGTRIM = RM_Register_EMU_TGTHDREGTRIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['TGTHDREGTRIM'] = self.TGTHDREGTRIM
        self.TGTDCDCLNVCTRL = RM_Register_EMU_TGTDCDCLNVCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['TGTDCDCLNVCTRL'] = self.TGTDCDCLNVCTRL
        self.TGTLDREGTRIM = RM_Register_EMU_TGTLDREGTRIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['TGTLDREGTRIM'] = self.TGTLDREGTRIM
        self.TGTDCDCLPVCTRL = RM_Register_EMU_TGTDCDCLPVCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['TGTDCDCLPVCTRL'] = self.TGTDCDCLPVCTRL
        self.TGTRREGTRIM = RM_Register_EMU_TGTRREGTRIM(self.zz_rmio, self.zz_label)
        self.zz_rdict['TGTRREGTRIM'] = self.TGTRREGTRIM
        self.TGTHFRCOCTRL = RM_Register_EMU_TGTHFRCOCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['TGTHFRCOCTRL'] = self.TGTHFRCOCTRL
        self.RREGCALIB = RM_Register_EMU_RREGCALIB(self.zz_rmio, self.zz_label)
        self.zz_rdict['RREGCALIB'] = self.RREGCALIB
        self.RREGTEST = RM_Register_EMU_RREGTEST(self.zz_rmio, self.zz_label)
        self.zz_rdict['RREGTEST'] = self.RREGTEST
        self.RREGOVERRIDE = RM_Register_EMU_RREGOVERRIDE(self.zz_rmio, self.zz_label)
        self.zz_rdict['RREGOVERRIDE'] = self.RREGOVERRIDE
        self.BCOSCENCMD = RM_Register_EMU_BCOSCENCMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['BCOSCENCMD'] = self.BCOSCENCMD
        self.BCLFRCOCTRL = RM_Register_EMU_BCLFRCOCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['BCLFRCOCTRL'] = self.BCLFRCOCTRL
        self.TESTBCLFRCOCTRL = RM_Register_EMU_TESTBCLFRCOCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['TESTBCLFRCOCTRL'] = self.TESTBCLFRCOCTRL
        self.PORBOD2 = RM_Register_EMU_PORBOD2(self.zz_rmio, self.zz_label)
        self.zz_rdict['PORBOD2'] = self.PORBOD2
        self.FLASHVREFCALIB = RM_Register_EMU_FLASHVREFCALIB(self.zz_rmio, self.zz_label)
        self.zz_rdict['FLASHVREFCALIB'] = self.FLASHVREFCALIB
        self.TEMPLO_THR0 = RM_Register_EMU_TEMPLO_THR0(self.zz_rmio, self.zz_label)
        self.zz_rdict['TEMPLO_THR0'] = self.TEMPLO_THR0
        self.TEMPHI_THR0 = RM_Register_EMU_TEMPHI_THR0(self.zz_rmio, self.zz_label)
        self.zz_rdict['TEMPHI_THR0'] = self.TEMPHI_THR0
        self.TEMPLO_THR1 = RM_Register_EMU_TEMPLO_THR1(self.zz_rmio, self.zz_label)
        self.zz_rdict['TEMPLO_THR1'] = self.TEMPLO_THR1
        self.TEMPHI_THR1 = RM_Register_EMU_TEMPHI_THR1(self.zz_rmio, self.zz_label)
        self.zz_rdict['TEMPHI_THR1'] = self.TEMPHI_THR1
        self.TEMPLO_THR2 = RM_Register_EMU_TEMPLO_THR2(self.zz_rmio, self.zz_label)
        self.zz_rdict['TEMPLO_THR2'] = self.TEMPLO_THR2
        self.DIAGAEN = RM_Register_EMU_DIAGAEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIAGAEN'] = self.DIAGAEN
        self.DIAGABLKTPSEL = RM_Register_EMU_DIAGABLKTPSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIAGABLKTPSEL'] = self.DIAGABLKTPSEL
        self.DIAGPNBLKSEL = RM_Register_EMU_DIAGPNBLKSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIAGPNBLKSEL'] = self.DIAGPNBLKSEL
        self.DIAGABRIDGESEL = RM_Register_EMU_DIAGABRIDGESEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DIAGABRIDGESEL'] = self.DIAGABRIDGESEL
        self.APDPGPIOSEL = RM_Register_EMU_APDPGPIOSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['APDPGPIOSEL'] = self.APDPGPIOSEL
        self.APDNGPIOSEL = RM_Register_EMU_APDNGPIOSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['APDNGPIOSEL'] = self.APDNGPIOSEL
        self.APAPGPIOSEL = RM_Register_EMU_APAPGPIOSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['APAPGPIOSEL'] = self.APAPGPIOSEL
        self.APANGPIOSEL = RM_Register_EMU_APANGPIOSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['APANGPIOSEL'] = self.APANGPIOSEL
        self.APBPGPIOSEL = RM_Register_EMU_APBPGPIOSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['APBPGPIOSEL'] = self.APBPGPIOSEL
        self.APBNGPIOSEL = RM_Register_EMU_APBNGPIOSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['APBNGPIOSEL'] = self.APBNGPIOSEL
        self.APCPGPIOSEL = RM_Register_EMU_APCPGPIOSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['APCPGPIOSEL'] = self.APCPGPIOSEL
        self.APCNGPIOSEL = RM_Register_EMU_APCNGPIOSEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['APCNGPIOSEL'] = self.APCNGPIOSEL
        self.EM2PERCTRL = RM_Register_EMU_EM2PERCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['EM2PERCTRL'] = self.EM2PERCTRL
        self.__dict__['zz_frozen'] = True