
__all__ = [ 'RM_Peripheral_GPIO' ]

from static import Base_RM_Peripheral
from GPIO_register import *

class RM_Peripheral_GPIO(Base_RM_Peripheral):
    def __init__(self, rmio, label):
        self.__dict__['zz_frozen'] = False
        super(RM_Peripheral_GPIO, self).__init__(rmio, label,
            0x4000A000, 'GPIO',
            "")
        self.PA_CTRL = RM_Register_GPIO_PA_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PA_CTRL'] = self.PA_CTRL
        self.PA_MODEL = RM_Register_GPIO_PA_MODEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PA_MODEL'] = self.PA_MODEL
        self.PA_MODEH = RM_Register_GPIO_PA_MODEH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PA_MODEH'] = self.PA_MODEH
        self.PA_DOUT = RM_Register_GPIO_PA_DOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PA_DOUT'] = self.PA_DOUT
        self.PA_DOUTTGL = RM_Register_GPIO_PA_DOUTTGL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PA_DOUTTGL'] = self.PA_DOUTTGL
        self.PA_DIN = RM_Register_GPIO_PA_DIN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PA_DIN'] = self.PA_DIN
        self.PA_PINLOCKN = RM_Register_GPIO_PA_PINLOCKN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PA_PINLOCKN'] = self.PA_PINLOCKN
        self.PA_OVTDIS = RM_Register_GPIO_PA_OVTDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PA_OVTDIS'] = self.PA_OVTDIS
        self.PB_CTRL = RM_Register_GPIO_PB_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PB_CTRL'] = self.PB_CTRL
        self.PB_MODEL = RM_Register_GPIO_PB_MODEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PB_MODEL'] = self.PB_MODEL
        self.PB_MODEH = RM_Register_GPIO_PB_MODEH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PB_MODEH'] = self.PB_MODEH
        self.PB_DOUT = RM_Register_GPIO_PB_DOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PB_DOUT'] = self.PB_DOUT
        self.PB_DOUTTGL = RM_Register_GPIO_PB_DOUTTGL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PB_DOUTTGL'] = self.PB_DOUTTGL
        self.PB_DIN = RM_Register_GPIO_PB_DIN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PB_DIN'] = self.PB_DIN
        self.PB_PINLOCKN = RM_Register_GPIO_PB_PINLOCKN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PB_PINLOCKN'] = self.PB_PINLOCKN
        self.PB_OVTDIS = RM_Register_GPIO_PB_OVTDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PB_OVTDIS'] = self.PB_OVTDIS
        self.PC_CTRL = RM_Register_GPIO_PC_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PC_CTRL'] = self.PC_CTRL
        self.PC_MODEL = RM_Register_GPIO_PC_MODEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PC_MODEL'] = self.PC_MODEL
        self.PC_MODEH = RM_Register_GPIO_PC_MODEH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PC_MODEH'] = self.PC_MODEH
        self.PC_DOUT = RM_Register_GPIO_PC_DOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PC_DOUT'] = self.PC_DOUT
        self.PC_DOUTTGL = RM_Register_GPIO_PC_DOUTTGL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PC_DOUTTGL'] = self.PC_DOUTTGL
        self.PC_DIN = RM_Register_GPIO_PC_DIN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PC_DIN'] = self.PC_DIN
        self.PC_PINLOCKN = RM_Register_GPIO_PC_PINLOCKN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PC_PINLOCKN'] = self.PC_PINLOCKN
        self.PC_OVTDIS = RM_Register_GPIO_PC_OVTDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PC_OVTDIS'] = self.PC_OVTDIS
        self.PD_CTRL = RM_Register_GPIO_PD_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PD_CTRL'] = self.PD_CTRL
        self.PD_MODEL = RM_Register_GPIO_PD_MODEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PD_MODEL'] = self.PD_MODEL
        self.PD_MODEH = RM_Register_GPIO_PD_MODEH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PD_MODEH'] = self.PD_MODEH
        self.PD_DOUT = RM_Register_GPIO_PD_DOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PD_DOUT'] = self.PD_DOUT
        self.PD_DOUTTGL = RM_Register_GPIO_PD_DOUTTGL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PD_DOUTTGL'] = self.PD_DOUTTGL
        self.PD_DIN = RM_Register_GPIO_PD_DIN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PD_DIN'] = self.PD_DIN
        self.PD_PINLOCKN = RM_Register_GPIO_PD_PINLOCKN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PD_PINLOCKN'] = self.PD_PINLOCKN
        self.PD_OVTDIS = RM_Register_GPIO_PD_OVTDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PD_OVTDIS'] = self.PD_OVTDIS
        self.PE_CTRL = RM_Register_GPIO_PE_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PE_CTRL'] = self.PE_CTRL
        self.PE_MODEL = RM_Register_GPIO_PE_MODEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PE_MODEL'] = self.PE_MODEL
        self.PE_MODEH = RM_Register_GPIO_PE_MODEH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PE_MODEH'] = self.PE_MODEH
        self.PE_DOUT = RM_Register_GPIO_PE_DOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PE_DOUT'] = self.PE_DOUT
        self.PE_DOUTTGL = RM_Register_GPIO_PE_DOUTTGL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PE_DOUTTGL'] = self.PE_DOUTTGL
        self.PE_DIN = RM_Register_GPIO_PE_DIN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PE_DIN'] = self.PE_DIN
        self.PE_PINLOCKN = RM_Register_GPIO_PE_PINLOCKN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PE_PINLOCKN'] = self.PE_PINLOCKN
        self.PE_OVTDIS = RM_Register_GPIO_PE_OVTDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PE_OVTDIS'] = self.PE_OVTDIS
        self.PF_CTRL = RM_Register_GPIO_PF_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PF_CTRL'] = self.PF_CTRL
        self.PF_MODEL = RM_Register_GPIO_PF_MODEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PF_MODEL'] = self.PF_MODEL
        self.PF_MODEH = RM_Register_GPIO_PF_MODEH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PF_MODEH'] = self.PF_MODEH
        self.PF_DOUT = RM_Register_GPIO_PF_DOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PF_DOUT'] = self.PF_DOUT
        self.PF_DOUTTGL = RM_Register_GPIO_PF_DOUTTGL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PF_DOUTTGL'] = self.PF_DOUTTGL
        self.PF_DIN = RM_Register_GPIO_PF_DIN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PF_DIN'] = self.PF_DIN
        self.PF_PINLOCKN = RM_Register_GPIO_PF_PINLOCKN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PF_PINLOCKN'] = self.PF_PINLOCKN
        self.PF_OVTDIS = RM_Register_GPIO_PF_OVTDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PF_OVTDIS'] = self.PF_OVTDIS
        self.PG_CTRL = RM_Register_GPIO_PG_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PG_CTRL'] = self.PG_CTRL
        self.PG_MODEL = RM_Register_GPIO_PG_MODEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PG_MODEL'] = self.PG_MODEL
        self.PG_MODEH = RM_Register_GPIO_PG_MODEH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PG_MODEH'] = self.PG_MODEH
        self.PG_DOUT = RM_Register_GPIO_PG_DOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PG_DOUT'] = self.PG_DOUT
        self.PG_DOUTTGL = RM_Register_GPIO_PG_DOUTTGL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PG_DOUTTGL'] = self.PG_DOUTTGL
        self.PG_DIN = RM_Register_GPIO_PG_DIN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PG_DIN'] = self.PG_DIN
        self.PG_PINLOCKN = RM_Register_GPIO_PG_PINLOCKN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PG_PINLOCKN'] = self.PG_PINLOCKN
        self.PG_OVTDIS = RM_Register_GPIO_PG_OVTDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PG_OVTDIS'] = self.PG_OVTDIS
        self.PH_CTRL = RM_Register_GPIO_PH_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PH_CTRL'] = self.PH_CTRL
        self.PH_MODEL = RM_Register_GPIO_PH_MODEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PH_MODEL'] = self.PH_MODEL
        self.PH_MODEH = RM_Register_GPIO_PH_MODEH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PH_MODEH'] = self.PH_MODEH
        self.PH_DOUT = RM_Register_GPIO_PH_DOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PH_DOUT'] = self.PH_DOUT
        self.PH_DOUTTGL = RM_Register_GPIO_PH_DOUTTGL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PH_DOUTTGL'] = self.PH_DOUTTGL
        self.PH_DIN = RM_Register_GPIO_PH_DIN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PH_DIN'] = self.PH_DIN
        self.PH_PINLOCKN = RM_Register_GPIO_PH_PINLOCKN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PH_PINLOCKN'] = self.PH_PINLOCKN
        self.PH_OVTDIS = RM_Register_GPIO_PH_OVTDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PH_OVTDIS'] = self.PH_OVTDIS
        self.PI_CTRL = RM_Register_GPIO_PI_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PI_CTRL'] = self.PI_CTRL
        self.PI_MODEL = RM_Register_GPIO_PI_MODEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PI_MODEL'] = self.PI_MODEL
        self.PI_MODEH = RM_Register_GPIO_PI_MODEH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PI_MODEH'] = self.PI_MODEH
        self.PI_DOUT = RM_Register_GPIO_PI_DOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PI_DOUT'] = self.PI_DOUT
        self.PI_DOUTTGL = RM_Register_GPIO_PI_DOUTTGL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PI_DOUTTGL'] = self.PI_DOUTTGL
        self.PI_DIN = RM_Register_GPIO_PI_DIN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PI_DIN'] = self.PI_DIN
        self.PI_PINLOCKN = RM_Register_GPIO_PI_PINLOCKN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PI_PINLOCKN'] = self.PI_PINLOCKN
        self.PI_OVTDIS = RM_Register_GPIO_PI_OVTDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PI_OVTDIS'] = self.PI_OVTDIS
        self.PJ_CTRL = RM_Register_GPIO_PJ_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PJ_CTRL'] = self.PJ_CTRL
        self.PJ_MODEL = RM_Register_GPIO_PJ_MODEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PJ_MODEL'] = self.PJ_MODEL
        self.PJ_MODEH = RM_Register_GPIO_PJ_MODEH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PJ_MODEH'] = self.PJ_MODEH
        self.PJ_DOUT = RM_Register_GPIO_PJ_DOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PJ_DOUT'] = self.PJ_DOUT
        self.PJ_DOUTTGL = RM_Register_GPIO_PJ_DOUTTGL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PJ_DOUTTGL'] = self.PJ_DOUTTGL
        self.PJ_DIN = RM_Register_GPIO_PJ_DIN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PJ_DIN'] = self.PJ_DIN
        self.PJ_PINLOCKN = RM_Register_GPIO_PJ_PINLOCKN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PJ_PINLOCKN'] = self.PJ_PINLOCKN
        self.PJ_OVTDIS = RM_Register_GPIO_PJ_OVTDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PJ_OVTDIS'] = self.PJ_OVTDIS
        self.PK_CTRL = RM_Register_GPIO_PK_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PK_CTRL'] = self.PK_CTRL
        self.PK_MODEL = RM_Register_GPIO_PK_MODEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PK_MODEL'] = self.PK_MODEL
        self.PK_MODEH = RM_Register_GPIO_PK_MODEH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PK_MODEH'] = self.PK_MODEH
        self.PK_DOUT = RM_Register_GPIO_PK_DOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PK_DOUT'] = self.PK_DOUT
        self.PK_DOUTTGL = RM_Register_GPIO_PK_DOUTTGL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PK_DOUTTGL'] = self.PK_DOUTTGL
        self.PK_DIN = RM_Register_GPIO_PK_DIN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PK_DIN'] = self.PK_DIN
        self.PK_PINLOCKN = RM_Register_GPIO_PK_PINLOCKN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PK_PINLOCKN'] = self.PK_PINLOCKN
        self.PK_OVTDIS = RM_Register_GPIO_PK_OVTDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PK_OVTDIS'] = self.PK_OVTDIS
        self.PL_CTRL = RM_Register_GPIO_PL_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PL_CTRL'] = self.PL_CTRL
        self.PL_MODEL = RM_Register_GPIO_PL_MODEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PL_MODEL'] = self.PL_MODEL
        self.PL_MODEH = RM_Register_GPIO_PL_MODEH(self.zz_rmio, self.zz_label)
        self.zz_rdict['PL_MODEH'] = self.PL_MODEH
        self.PL_DOUT = RM_Register_GPIO_PL_DOUT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PL_DOUT'] = self.PL_DOUT
        self.PL_DOUTTGL = RM_Register_GPIO_PL_DOUTTGL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PL_DOUTTGL'] = self.PL_DOUTTGL
        self.PL_DIN = RM_Register_GPIO_PL_DIN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PL_DIN'] = self.PL_DIN
        self.PL_PINLOCKN = RM_Register_GPIO_PL_PINLOCKN(self.zz_rmio, self.zz_label)
        self.zz_rdict['PL_PINLOCKN'] = self.PL_PINLOCKN
        self.PL_OVTDIS = RM_Register_GPIO_PL_OVTDIS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PL_OVTDIS'] = self.PL_OVTDIS
        self.EXTIPSELL = RM_Register_GPIO_EXTIPSELL(self.zz_rmio, self.zz_label)
        self.zz_rdict['EXTIPSELL'] = self.EXTIPSELL
        self.EXTIPSELH = RM_Register_GPIO_EXTIPSELH(self.zz_rmio, self.zz_label)
        self.zz_rdict['EXTIPSELH'] = self.EXTIPSELH
        self.EXTIPINSELL = RM_Register_GPIO_EXTIPINSELL(self.zz_rmio, self.zz_label)
        self.zz_rdict['EXTIPINSELL'] = self.EXTIPINSELL
        self.EXTIPINSELH = RM_Register_GPIO_EXTIPINSELH(self.zz_rmio, self.zz_label)
        self.zz_rdict['EXTIPINSELH'] = self.EXTIPINSELH
        self.EXTIRISE = RM_Register_GPIO_EXTIRISE(self.zz_rmio, self.zz_label)
        self.zz_rdict['EXTIRISE'] = self.EXTIRISE
        self.EXTIFALL = RM_Register_GPIO_EXTIFALL(self.zz_rmio, self.zz_label)
        self.zz_rdict['EXTIFALL'] = self.EXTIFALL
        self.EXTILEVEL = RM_Register_GPIO_EXTILEVEL(self.zz_rmio, self.zz_label)
        self.zz_rdict['EXTILEVEL'] = self.EXTILEVEL
        self.IF = RM_Register_GPIO_IF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IF'] = self.IF
        self.IFS = RM_Register_GPIO_IFS(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFS'] = self.IFS
        self.IFC = RM_Register_GPIO_IFC(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFC'] = self.IFC
        self.IEN = RM_Register_GPIO_IEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['IEN'] = self.IEN
        self.EM4WUEN = RM_Register_GPIO_EM4WUEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['EM4WUEN'] = self.EM4WUEN
        self.ROUTEPEN = RM_Register_GPIO_ROUTEPEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['ROUTEPEN'] = self.ROUTEPEN
        self.ROUTELOC0 = RM_Register_GPIO_ROUTELOC0(self.zz_rmio, self.zz_label)
        self.zz_rdict['ROUTELOC0'] = self.ROUTELOC0
        self.ROUTELOC1 = RM_Register_GPIO_ROUTELOC1(self.zz_rmio, self.zz_label)
        self.zz_rdict['ROUTELOC1'] = self.ROUTELOC1
        self.INSENSE = RM_Register_GPIO_INSENSE(self.zz_rmio, self.zz_label)
        self.zz_rdict['INSENSE'] = self.INSENSE
        self.LOCK = RM_Register_GPIO_LOCK(self.zz_rmio, self.zz_label)
        self.zz_rdict['LOCK'] = self.LOCK
        self.__dict__['zz_frozen'] = True