
__all__ = [ 'RM_Peripheral_LESENSE' ]

from static import Base_RM_Peripheral
from LESENSE_register import *

class RM_Peripheral_LESENSE(Base_RM_Peripheral):
    def __init__(self, rmio, label):
        self.__dict__['zz_frozen'] = False
        super(RM_Peripheral_LESENSE, self).__init__(rmio, label,
            0x40055000, 'LESENSE',
            "")
        self.CTRL = RM_Register_LESENSE_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL'] = self.CTRL
        self.TIMCTRL = RM_Register_LESENSE_TIMCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['TIMCTRL'] = self.TIMCTRL
        self.PERCTRL = RM_Register_LESENSE_PERCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PERCTRL'] = self.PERCTRL
        self.DECCTRL = RM_Register_LESENSE_DECCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['DECCTRL'] = self.DECCTRL
        self.BIASCTRL = RM_Register_LESENSE_BIASCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['BIASCTRL'] = self.BIASCTRL
        self.EVALCTRL = RM_Register_LESENSE_EVALCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['EVALCTRL'] = self.EVALCTRL
        self.PRSCTRL = RM_Register_LESENSE_PRSCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PRSCTRL'] = self.PRSCTRL
        self.CMD = RM_Register_LESENSE_CMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['CMD'] = self.CMD
        self.CHEN = RM_Register_LESENSE_CHEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHEN'] = self.CHEN
        self.SCANRES = RM_Register_LESENSE_SCANRES(self.zz_rmio, self.zz_label)
        self.zz_rdict['SCANRES'] = self.SCANRES
        self.STATUS = RM_Register_LESENSE_STATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS'] = self.STATUS
        self.PTR = RM_Register_LESENSE_PTR(self.zz_rmio, self.zz_label)
        self.zz_rdict['PTR'] = self.PTR
        self.BUFDATA = RM_Register_LESENSE_BUFDATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUFDATA'] = self.BUFDATA
        self.CURCH = RM_Register_LESENSE_CURCH(self.zz_rmio, self.zz_label)
        self.zz_rdict['CURCH'] = self.CURCH
        self.DECSTATE = RM_Register_LESENSE_DECSTATE(self.zz_rmio, self.zz_label)
        self.zz_rdict['DECSTATE'] = self.DECSTATE
        self.SENSORSTATE = RM_Register_LESENSE_SENSORSTATE(self.zz_rmio, self.zz_label)
        self.zz_rdict['SENSORSTATE'] = self.SENSORSTATE
        self.IDLECONF = RM_Register_LESENSE_IDLECONF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IDLECONF'] = self.IDLECONF
        self.ALTEXCONF = RM_Register_LESENSE_ALTEXCONF(self.zz_rmio, self.zz_label)
        self.zz_rdict['ALTEXCONF'] = self.ALTEXCONF
        self.IF = RM_Register_LESENSE_IF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IF'] = self.IF
        self.IFS = RM_Register_LESENSE_IFS(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFS'] = self.IFS
        self.IFC = RM_Register_LESENSE_IFC(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFC'] = self.IFC
        self.IEN = RM_Register_LESENSE_IEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['IEN'] = self.IEN
        self.SYNCBUSY = RM_Register_LESENSE_SYNCBUSY(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNCBUSY'] = self.SYNCBUSY
        self.ROUTEPEN = RM_Register_LESENSE_ROUTEPEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['ROUTEPEN'] = self.ROUTEPEN
        self.FEATURECONF = RM_Register_LESENSE_FEATURECONF(self.zz_rmio, self.zz_label)
        self.zz_rdict['FEATURECONF'] = self.FEATURECONF
        self.TESTCTRL = RM_Register_LESENSE_TESTCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['TESTCTRL'] = self.TESTCTRL
        self.RIPCNT = RM_Register_LESENSE_RIPCNT(self.zz_rmio, self.zz_label)
        self.zz_rdict['RIPCNT'] = self.RIPCNT
        self.ST0_TCONFA = RM_Register_LESENSE_ST0_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST0_TCONFA'] = self.ST0_TCONFA
        self.ST0_TCONFB = RM_Register_LESENSE_ST0_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST0_TCONFB'] = self.ST0_TCONFB
        self.ST1_TCONFA = RM_Register_LESENSE_ST1_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST1_TCONFA'] = self.ST1_TCONFA
        self.ST1_TCONFB = RM_Register_LESENSE_ST1_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST1_TCONFB'] = self.ST1_TCONFB
        self.ST2_TCONFA = RM_Register_LESENSE_ST2_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST2_TCONFA'] = self.ST2_TCONFA
        self.ST2_TCONFB = RM_Register_LESENSE_ST2_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST2_TCONFB'] = self.ST2_TCONFB
        self.ST3_TCONFA = RM_Register_LESENSE_ST3_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST3_TCONFA'] = self.ST3_TCONFA
        self.ST3_TCONFB = RM_Register_LESENSE_ST3_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST3_TCONFB'] = self.ST3_TCONFB
        self.ST4_TCONFA = RM_Register_LESENSE_ST4_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST4_TCONFA'] = self.ST4_TCONFA
        self.ST4_TCONFB = RM_Register_LESENSE_ST4_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST4_TCONFB'] = self.ST4_TCONFB
        self.ST5_TCONFA = RM_Register_LESENSE_ST5_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST5_TCONFA'] = self.ST5_TCONFA
        self.ST5_TCONFB = RM_Register_LESENSE_ST5_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST5_TCONFB'] = self.ST5_TCONFB
        self.ST6_TCONFA = RM_Register_LESENSE_ST6_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST6_TCONFA'] = self.ST6_TCONFA
        self.ST6_TCONFB = RM_Register_LESENSE_ST6_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST6_TCONFB'] = self.ST6_TCONFB
        self.ST7_TCONFA = RM_Register_LESENSE_ST7_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST7_TCONFA'] = self.ST7_TCONFA
        self.ST7_TCONFB = RM_Register_LESENSE_ST7_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST7_TCONFB'] = self.ST7_TCONFB
        self.ST8_TCONFA = RM_Register_LESENSE_ST8_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST8_TCONFA'] = self.ST8_TCONFA
        self.ST8_TCONFB = RM_Register_LESENSE_ST8_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST8_TCONFB'] = self.ST8_TCONFB
        self.ST9_TCONFA = RM_Register_LESENSE_ST9_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST9_TCONFA'] = self.ST9_TCONFA
        self.ST9_TCONFB = RM_Register_LESENSE_ST9_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST9_TCONFB'] = self.ST9_TCONFB
        self.ST10_TCONFA = RM_Register_LESENSE_ST10_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST10_TCONFA'] = self.ST10_TCONFA
        self.ST10_TCONFB = RM_Register_LESENSE_ST10_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST10_TCONFB'] = self.ST10_TCONFB
        self.ST11_TCONFA = RM_Register_LESENSE_ST11_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST11_TCONFA'] = self.ST11_TCONFA
        self.ST11_TCONFB = RM_Register_LESENSE_ST11_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST11_TCONFB'] = self.ST11_TCONFB
        self.ST12_TCONFA = RM_Register_LESENSE_ST12_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST12_TCONFA'] = self.ST12_TCONFA
        self.ST12_TCONFB = RM_Register_LESENSE_ST12_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST12_TCONFB'] = self.ST12_TCONFB
        self.ST13_TCONFA = RM_Register_LESENSE_ST13_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST13_TCONFA'] = self.ST13_TCONFA
        self.ST13_TCONFB = RM_Register_LESENSE_ST13_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST13_TCONFB'] = self.ST13_TCONFB
        self.ST14_TCONFA = RM_Register_LESENSE_ST14_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST14_TCONFA'] = self.ST14_TCONFA
        self.ST14_TCONFB = RM_Register_LESENSE_ST14_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST14_TCONFB'] = self.ST14_TCONFB
        self.ST15_TCONFA = RM_Register_LESENSE_ST15_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST15_TCONFA'] = self.ST15_TCONFA
        self.ST15_TCONFB = RM_Register_LESENSE_ST15_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST15_TCONFB'] = self.ST15_TCONFB
        self.ST16_TCONFA = RM_Register_LESENSE_ST16_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST16_TCONFA'] = self.ST16_TCONFA
        self.ST16_TCONFB = RM_Register_LESENSE_ST16_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST16_TCONFB'] = self.ST16_TCONFB
        self.ST17_TCONFA = RM_Register_LESENSE_ST17_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST17_TCONFA'] = self.ST17_TCONFA
        self.ST17_TCONFB = RM_Register_LESENSE_ST17_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST17_TCONFB'] = self.ST17_TCONFB
        self.ST18_TCONFA = RM_Register_LESENSE_ST18_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST18_TCONFA'] = self.ST18_TCONFA
        self.ST18_TCONFB = RM_Register_LESENSE_ST18_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST18_TCONFB'] = self.ST18_TCONFB
        self.ST19_TCONFA = RM_Register_LESENSE_ST19_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST19_TCONFA'] = self.ST19_TCONFA
        self.ST19_TCONFB = RM_Register_LESENSE_ST19_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST19_TCONFB'] = self.ST19_TCONFB
        self.ST20_TCONFA = RM_Register_LESENSE_ST20_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST20_TCONFA'] = self.ST20_TCONFA
        self.ST20_TCONFB = RM_Register_LESENSE_ST20_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST20_TCONFB'] = self.ST20_TCONFB
        self.ST21_TCONFA = RM_Register_LESENSE_ST21_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST21_TCONFA'] = self.ST21_TCONFA
        self.ST21_TCONFB = RM_Register_LESENSE_ST21_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST21_TCONFB'] = self.ST21_TCONFB
        self.ST22_TCONFA = RM_Register_LESENSE_ST22_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST22_TCONFA'] = self.ST22_TCONFA
        self.ST22_TCONFB = RM_Register_LESENSE_ST22_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST22_TCONFB'] = self.ST22_TCONFB
        self.ST23_TCONFA = RM_Register_LESENSE_ST23_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST23_TCONFA'] = self.ST23_TCONFA
        self.ST23_TCONFB = RM_Register_LESENSE_ST23_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST23_TCONFB'] = self.ST23_TCONFB
        self.ST24_TCONFA = RM_Register_LESENSE_ST24_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST24_TCONFA'] = self.ST24_TCONFA
        self.ST24_TCONFB = RM_Register_LESENSE_ST24_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST24_TCONFB'] = self.ST24_TCONFB
        self.ST25_TCONFA = RM_Register_LESENSE_ST25_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST25_TCONFA'] = self.ST25_TCONFA
        self.ST25_TCONFB = RM_Register_LESENSE_ST25_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST25_TCONFB'] = self.ST25_TCONFB
        self.ST26_TCONFA = RM_Register_LESENSE_ST26_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST26_TCONFA'] = self.ST26_TCONFA
        self.ST26_TCONFB = RM_Register_LESENSE_ST26_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST26_TCONFB'] = self.ST26_TCONFB
        self.ST27_TCONFA = RM_Register_LESENSE_ST27_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST27_TCONFA'] = self.ST27_TCONFA
        self.ST27_TCONFB = RM_Register_LESENSE_ST27_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST27_TCONFB'] = self.ST27_TCONFB
        self.ST28_TCONFA = RM_Register_LESENSE_ST28_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST28_TCONFA'] = self.ST28_TCONFA
        self.ST28_TCONFB = RM_Register_LESENSE_ST28_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST28_TCONFB'] = self.ST28_TCONFB
        self.ST29_TCONFA = RM_Register_LESENSE_ST29_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST29_TCONFA'] = self.ST29_TCONFA
        self.ST29_TCONFB = RM_Register_LESENSE_ST29_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST29_TCONFB'] = self.ST29_TCONFB
        self.ST30_TCONFA = RM_Register_LESENSE_ST30_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST30_TCONFA'] = self.ST30_TCONFA
        self.ST30_TCONFB = RM_Register_LESENSE_ST30_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST30_TCONFB'] = self.ST30_TCONFB
        self.ST31_TCONFA = RM_Register_LESENSE_ST31_TCONFA(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST31_TCONFA'] = self.ST31_TCONFA
        self.ST31_TCONFB = RM_Register_LESENSE_ST31_TCONFB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ST31_TCONFB'] = self.ST31_TCONFB
        self.BUF0_DATA = RM_Register_LESENSE_BUF0_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF0_DATA'] = self.BUF0_DATA
        self.BUF1_DATA = RM_Register_LESENSE_BUF1_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF1_DATA'] = self.BUF1_DATA
        self.BUF2_DATA = RM_Register_LESENSE_BUF2_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF2_DATA'] = self.BUF2_DATA
        self.BUF3_DATA = RM_Register_LESENSE_BUF3_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF3_DATA'] = self.BUF3_DATA
        self.BUF4_DATA = RM_Register_LESENSE_BUF4_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF4_DATA'] = self.BUF4_DATA
        self.BUF5_DATA = RM_Register_LESENSE_BUF5_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF5_DATA'] = self.BUF5_DATA
        self.BUF6_DATA = RM_Register_LESENSE_BUF6_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF6_DATA'] = self.BUF6_DATA
        self.BUF7_DATA = RM_Register_LESENSE_BUF7_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF7_DATA'] = self.BUF7_DATA
        self.BUF8_DATA = RM_Register_LESENSE_BUF8_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF8_DATA'] = self.BUF8_DATA
        self.BUF9_DATA = RM_Register_LESENSE_BUF9_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF9_DATA'] = self.BUF9_DATA
        self.BUF10_DATA = RM_Register_LESENSE_BUF10_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF10_DATA'] = self.BUF10_DATA
        self.BUF11_DATA = RM_Register_LESENSE_BUF11_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF11_DATA'] = self.BUF11_DATA
        self.BUF12_DATA = RM_Register_LESENSE_BUF12_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF12_DATA'] = self.BUF12_DATA
        self.BUF13_DATA = RM_Register_LESENSE_BUF13_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF13_DATA'] = self.BUF13_DATA
        self.BUF14_DATA = RM_Register_LESENSE_BUF14_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF14_DATA'] = self.BUF14_DATA
        self.BUF15_DATA = RM_Register_LESENSE_BUF15_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['BUF15_DATA'] = self.BUF15_DATA
        self.CH0_TIMING = RM_Register_LESENSE_CH0_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH0_TIMING'] = self.CH0_TIMING
        self.CH0_INTERACT = RM_Register_LESENSE_CH0_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH0_INTERACT'] = self.CH0_INTERACT
        self.CH0_EVAL = RM_Register_LESENSE_CH0_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH0_EVAL'] = self.CH0_EVAL
        self.CH1_TIMING = RM_Register_LESENSE_CH1_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH1_TIMING'] = self.CH1_TIMING
        self.CH1_INTERACT = RM_Register_LESENSE_CH1_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH1_INTERACT'] = self.CH1_INTERACT
        self.CH1_EVAL = RM_Register_LESENSE_CH1_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH1_EVAL'] = self.CH1_EVAL
        self.CH2_TIMING = RM_Register_LESENSE_CH2_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH2_TIMING'] = self.CH2_TIMING
        self.CH2_INTERACT = RM_Register_LESENSE_CH2_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH2_INTERACT'] = self.CH2_INTERACT
        self.CH2_EVAL = RM_Register_LESENSE_CH2_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH2_EVAL'] = self.CH2_EVAL
        self.CH3_TIMING = RM_Register_LESENSE_CH3_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH3_TIMING'] = self.CH3_TIMING
        self.CH3_INTERACT = RM_Register_LESENSE_CH3_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH3_INTERACT'] = self.CH3_INTERACT
        self.CH3_EVAL = RM_Register_LESENSE_CH3_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH3_EVAL'] = self.CH3_EVAL
        self.CH4_TIMING = RM_Register_LESENSE_CH4_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH4_TIMING'] = self.CH4_TIMING
        self.CH4_INTERACT = RM_Register_LESENSE_CH4_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH4_INTERACT'] = self.CH4_INTERACT
        self.CH4_EVAL = RM_Register_LESENSE_CH4_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH4_EVAL'] = self.CH4_EVAL
        self.CH5_TIMING = RM_Register_LESENSE_CH5_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH5_TIMING'] = self.CH5_TIMING
        self.CH5_INTERACT = RM_Register_LESENSE_CH5_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH5_INTERACT'] = self.CH5_INTERACT
        self.CH5_EVAL = RM_Register_LESENSE_CH5_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH5_EVAL'] = self.CH5_EVAL
        self.CH6_TIMING = RM_Register_LESENSE_CH6_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH6_TIMING'] = self.CH6_TIMING
        self.CH6_INTERACT = RM_Register_LESENSE_CH6_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH6_INTERACT'] = self.CH6_INTERACT
        self.CH6_EVAL = RM_Register_LESENSE_CH6_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH6_EVAL'] = self.CH6_EVAL
        self.CH7_TIMING = RM_Register_LESENSE_CH7_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH7_TIMING'] = self.CH7_TIMING
        self.CH7_INTERACT = RM_Register_LESENSE_CH7_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH7_INTERACT'] = self.CH7_INTERACT
        self.CH7_EVAL = RM_Register_LESENSE_CH7_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH7_EVAL'] = self.CH7_EVAL
        self.CH8_TIMING = RM_Register_LESENSE_CH8_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH8_TIMING'] = self.CH8_TIMING
        self.CH8_INTERACT = RM_Register_LESENSE_CH8_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH8_INTERACT'] = self.CH8_INTERACT
        self.CH8_EVAL = RM_Register_LESENSE_CH8_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH8_EVAL'] = self.CH8_EVAL
        self.CH9_TIMING = RM_Register_LESENSE_CH9_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH9_TIMING'] = self.CH9_TIMING
        self.CH9_INTERACT = RM_Register_LESENSE_CH9_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH9_INTERACT'] = self.CH9_INTERACT
        self.CH9_EVAL = RM_Register_LESENSE_CH9_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH9_EVAL'] = self.CH9_EVAL
        self.CH10_TIMING = RM_Register_LESENSE_CH10_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH10_TIMING'] = self.CH10_TIMING
        self.CH10_INTERACT = RM_Register_LESENSE_CH10_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH10_INTERACT'] = self.CH10_INTERACT
        self.CH10_EVAL = RM_Register_LESENSE_CH10_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH10_EVAL'] = self.CH10_EVAL
        self.CH11_TIMING = RM_Register_LESENSE_CH11_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH11_TIMING'] = self.CH11_TIMING
        self.CH11_INTERACT = RM_Register_LESENSE_CH11_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH11_INTERACT'] = self.CH11_INTERACT
        self.CH11_EVAL = RM_Register_LESENSE_CH11_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH11_EVAL'] = self.CH11_EVAL
        self.CH12_TIMING = RM_Register_LESENSE_CH12_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH12_TIMING'] = self.CH12_TIMING
        self.CH12_INTERACT = RM_Register_LESENSE_CH12_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH12_INTERACT'] = self.CH12_INTERACT
        self.CH12_EVAL = RM_Register_LESENSE_CH12_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH12_EVAL'] = self.CH12_EVAL
        self.CH13_TIMING = RM_Register_LESENSE_CH13_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH13_TIMING'] = self.CH13_TIMING
        self.CH13_INTERACT = RM_Register_LESENSE_CH13_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH13_INTERACT'] = self.CH13_INTERACT
        self.CH13_EVAL = RM_Register_LESENSE_CH13_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH13_EVAL'] = self.CH13_EVAL
        self.CH14_TIMING = RM_Register_LESENSE_CH14_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH14_TIMING'] = self.CH14_TIMING
        self.CH14_INTERACT = RM_Register_LESENSE_CH14_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH14_INTERACT'] = self.CH14_INTERACT
        self.CH14_EVAL = RM_Register_LESENSE_CH14_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH14_EVAL'] = self.CH14_EVAL
        self.CH15_TIMING = RM_Register_LESENSE_CH15_TIMING(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH15_TIMING'] = self.CH15_TIMING
        self.CH15_INTERACT = RM_Register_LESENSE_CH15_INTERACT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH15_INTERACT'] = self.CH15_INTERACT
        self.CH15_EVAL = RM_Register_LESENSE_CH15_EVAL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CH15_EVAL'] = self.CH15_EVAL
        self.__dict__['zz_frozen'] = True