
from static import Base_RM_Enum
from collections import OrderedDict


class RM_Enum_PRS_ROUTELOC0_CH0LOC(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.LOC0 = 0x00000000
        zz_edict['LOC0'] = self.LOC0
        zz_desc['LOC0'] = ""
        self.LOC1 = 0x00000001
        zz_edict['LOC1'] = self.LOC1
        zz_desc['LOC1'] = ""
        self.LOC2 = 0x00000002
        zz_edict['LOC2'] = self.LOC2
        zz_desc['LOC2'] = ""
        self.LOC3 = 0x00000003
        zz_edict['LOC3'] = self.LOC3
        zz_desc['LOC3'] = ""
        self.LOC4 = 0x00000004
        zz_edict['LOC4'] = self.LOC4
        zz_desc['LOC4'] = ""
        self.LOC5 = 0x00000005
        zz_edict['LOC5'] = self.LOC5
        zz_desc['LOC5'] = ""
        self.LOC6 = 0x00000006
        zz_edict['LOC6'] = self.LOC6
        zz_desc['LOC6'] = ""
        self.LOC7 = 0x00000007
        zz_edict['LOC7'] = self.LOC7
        zz_desc['LOC7'] = ""
        self.LOC8 = 0x00000008
        zz_edict['LOC8'] = self.LOC8
        zz_desc['LOC8'] = ""
        self.LOC9 = 0x00000009
        zz_edict['LOC9'] = self.LOC9
        zz_desc['LOC9'] = ""
        self.LOC10 = 0x0000000A
        zz_edict['LOC10'] = self.LOC10
        zz_desc['LOC10'] = ""
        self.LOC11 = 0x0000000B
        zz_edict['LOC11'] = self.LOC11
        zz_desc['LOC11'] = ""
        self.LOC12 = 0x0000000C
        zz_edict['LOC12'] = self.LOC12
        zz_desc['LOC12'] = ""
        self.LOC13 = 0x0000000D
        zz_edict['LOC13'] = self.LOC13
        zz_desc['LOC13'] = ""
        super(RM_Enum_PRS_ROUTELOC0_CH0LOC, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_ROUTELOC0_CH1LOC(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.LOC0 = 0x00000000
        zz_edict['LOC0'] = self.LOC0
        zz_desc['LOC0'] = ""
        self.LOC1 = 0x00000001
        zz_edict['LOC1'] = self.LOC1
        zz_desc['LOC1'] = ""
        self.LOC2 = 0x00000002
        zz_edict['LOC2'] = self.LOC2
        zz_desc['LOC2'] = ""
        self.LOC3 = 0x00000003
        zz_edict['LOC3'] = self.LOC3
        zz_desc['LOC3'] = ""
        self.LOC4 = 0x00000004
        zz_edict['LOC4'] = self.LOC4
        zz_desc['LOC4'] = ""
        self.LOC5 = 0x00000005
        zz_edict['LOC5'] = self.LOC5
        zz_desc['LOC5'] = ""
        self.LOC6 = 0x00000006
        zz_edict['LOC6'] = self.LOC6
        zz_desc['LOC6'] = ""
        self.LOC7 = 0x00000007
        zz_edict['LOC7'] = self.LOC7
        zz_desc['LOC7'] = ""
        super(RM_Enum_PRS_ROUTELOC0_CH1LOC, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_ROUTELOC0_CH2LOC(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.LOC0 = 0x00000000
        zz_edict['LOC0'] = self.LOC0
        zz_desc['LOC0'] = ""
        self.LOC1 = 0x00000001
        zz_edict['LOC1'] = self.LOC1
        zz_desc['LOC1'] = ""
        self.LOC2 = 0x00000002
        zz_edict['LOC2'] = self.LOC2
        zz_desc['LOC2'] = ""
        self.LOC3 = 0x00000003
        zz_edict['LOC3'] = self.LOC3
        zz_desc['LOC3'] = ""
        self.LOC4 = 0x00000004
        zz_edict['LOC4'] = self.LOC4
        zz_desc['LOC4'] = ""
        self.LOC5 = 0x00000005
        zz_edict['LOC5'] = self.LOC5
        zz_desc['LOC5'] = ""
        self.LOC6 = 0x00000006
        zz_edict['LOC6'] = self.LOC6
        zz_desc['LOC6'] = ""
        self.LOC7 = 0x00000007
        zz_edict['LOC7'] = self.LOC7
        zz_desc['LOC7'] = ""
        super(RM_Enum_PRS_ROUTELOC0_CH2LOC, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_ROUTELOC0_CH3LOC(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.LOC0 = 0x00000000
        zz_edict['LOC0'] = self.LOC0
        zz_desc['LOC0'] = ""
        self.LOC1 = 0x00000001
        zz_edict['LOC1'] = self.LOC1
        zz_desc['LOC1'] = ""
        self.LOC2 = 0x00000002
        zz_edict['LOC2'] = self.LOC2
        zz_desc['LOC2'] = ""
        self.LOC3 = 0x00000003
        zz_edict['LOC3'] = self.LOC3
        zz_desc['LOC3'] = ""
        self.LOC4 = 0x00000004
        zz_edict['LOC4'] = self.LOC4
        zz_desc['LOC4'] = ""
        self.LOC5 = 0x00000005
        zz_edict['LOC5'] = self.LOC5
        zz_desc['LOC5'] = ""
        self.LOC6 = 0x00000006
        zz_edict['LOC6'] = self.LOC6
        zz_desc['LOC6'] = ""
        self.LOC7 = 0x00000007
        zz_edict['LOC7'] = self.LOC7
        zz_desc['LOC7'] = ""
        self.LOC8 = 0x00000008
        zz_edict['LOC8'] = self.LOC8
        zz_desc['LOC8'] = ""
        self.LOC9 = 0x00000009
        zz_edict['LOC9'] = self.LOC9
        zz_desc['LOC9'] = ""
        self.LOC10 = 0x0000000A
        zz_edict['LOC10'] = self.LOC10
        zz_desc['LOC10'] = ""
        self.LOC11 = 0x0000000B
        zz_edict['LOC11'] = self.LOC11
        zz_desc['LOC11'] = ""
        self.LOC12 = 0x0000000C
        zz_edict['LOC12'] = self.LOC12
        zz_desc['LOC12'] = ""
        self.LOC13 = 0x0000000D
        zz_edict['LOC13'] = self.LOC13
        zz_desc['LOC13'] = ""
        self.LOC14 = 0x0000000E
        zz_edict['LOC14'] = self.LOC14
        zz_desc['LOC14'] = ""
        super(RM_Enum_PRS_ROUTELOC0_CH3LOC, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_ROUTELOC1_CH4LOC(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.LOC0 = 0x00000000
        zz_edict['LOC0'] = self.LOC0
        zz_desc['LOC0'] = ""
        self.LOC1 = 0x00000001
        zz_edict['LOC1'] = self.LOC1
        zz_desc['LOC1'] = ""
        self.LOC2 = 0x00000002
        zz_edict['LOC2'] = self.LOC2
        zz_desc['LOC2'] = ""
        self.LOC3 = 0x00000003
        zz_edict['LOC3'] = self.LOC3
        zz_desc['LOC3'] = ""
        self.LOC4 = 0x00000004
        zz_edict['LOC4'] = self.LOC4
        zz_desc['LOC4'] = ""
        self.LOC5 = 0x00000005
        zz_edict['LOC5'] = self.LOC5
        zz_desc['LOC5'] = ""
        self.LOC6 = 0x00000006
        zz_edict['LOC6'] = self.LOC6
        zz_desc['LOC6'] = ""
        super(RM_Enum_PRS_ROUTELOC1_CH4LOC, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_ROUTELOC1_CH5LOC(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.LOC0 = 0x00000000
        zz_edict['LOC0'] = self.LOC0
        zz_desc['LOC0'] = ""
        self.LOC1 = 0x00000001
        zz_edict['LOC1'] = self.LOC1
        zz_desc['LOC1'] = ""
        self.LOC2 = 0x00000002
        zz_edict['LOC2'] = self.LOC2
        zz_desc['LOC2'] = ""
        self.LOC3 = 0x00000003
        zz_edict['LOC3'] = self.LOC3
        zz_desc['LOC3'] = ""
        self.LOC4 = 0x00000004
        zz_edict['LOC4'] = self.LOC4
        zz_desc['LOC4'] = ""
        self.LOC5 = 0x00000005
        zz_edict['LOC5'] = self.LOC5
        zz_desc['LOC5'] = ""
        self.LOC6 = 0x00000006
        zz_edict['LOC6'] = self.LOC6
        zz_desc['LOC6'] = ""
        super(RM_Enum_PRS_ROUTELOC1_CH5LOC, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_ROUTELOC1_CH6LOC(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.LOC0 = 0x00000000
        zz_edict['LOC0'] = self.LOC0
        zz_desc['LOC0'] = ""
        self.LOC1 = 0x00000001
        zz_edict['LOC1'] = self.LOC1
        zz_desc['LOC1'] = ""
        self.LOC2 = 0x00000002
        zz_edict['LOC2'] = self.LOC2
        zz_desc['LOC2'] = ""
        self.LOC3 = 0x00000003
        zz_edict['LOC3'] = self.LOC3
        zz_desc['LOC3'] = ""
        self.LOC4 = 0x00000004
        zz_edict['LOC4'] = self.LOC4
        zz_desc['LOC4'] = ""
        self.LOC5 = 0x00000005
        zz_edict['LOC5'] = self.LOC5
        zz_desc['LOC5'] = ""
        self.LOC6 = 0x00000006
        zz_edict['LOC6'] = self.LOC6
        zz_desc['LOC6'] = ""
        self.LOC7 = 0x00000007
        zz_edict['LOC7'] = self.LOC7
        zz_desc['LOC7'] = ""
        self.LOC8 = 0x00000008
        zz_edict['LOC8'] = self.LOC8
        zz_desc['LOC8'] = ""
        self.LOC9 = 0x00000009
        zz_edict['LOC9'] = self.LOC9
        zz_desc['LOC9'] = ""
        self.LOC10 = 0x0000000A
        zz_edict['LOC10'] = self.LOC10
        zz_desc['LOC10'] = ""
        self.LOC11 = 0x0000000B
        zz_edict['LOC11'] = self.LOC11
        zz_desc['LOC11'] = ""
        self.LOC12 = 0x0000000C
        zz_edict['LOC12'] = self.LOC12
        zz_desc['LOC12'] = ""
        self.LOC13 = 0x0000000D
        zz_edict['LOC13'] = self.LOC13
        zz_desc['LOC13'] = ""
        self.LOC14 = 0x0000000E
        zz_edict['LOC14'] = self.LOC14
        zz_desc['LOC14'] = ""
        self.LOC15 = 0x0000000F
        zz_edict['LOC15'] = self.LOC15
        zz_desc['LOC15'] = ""
        self.LOC16 = 0x00000010
        zz_edict['LOC16'] = self.LOC16
        zz_desc['LOC16'] = ""
        self.LOC17 = 0x00000011
        zz_edict['LOC17'] = self.LOC17
        zz_desc['LOC17'] = ""
        super(RM_Enum_PRS_ROUTELOC1_CH6LOC, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_ROUTELOC1_CH7LOC(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.LOC0 = 0x00000000
        zz_edict['LOC0'] = self.LOC0
        zz_desc['LOC0'] = ""
        self.LOC1 = 0x00000001
        zz_edict['LOC1'] = self.LOC1
        zz_desc['LOC1'] = ""
        self.LOC2 = 0x00000002
        zz_edict['LOC2'] = self.LOC2
        zz_desc['LOC2'] = ""
        self.LOC3 = 0x00000003
        zz_edict['LOC3'] = self.LOC3
        zz_desc['LOC3'] = ""
        self.LOC4 = 0x00000004
        zz_edict['LOC4'] = self.LOC4
        zz_desc['LOC4'] = ""
        self.LOC5 = 0x00000005
        zz_edict['LOC5'] = self.LOC5
        zz_desc['LOC5'] = ""
        self.LOC6 = 0x00000006
        zz_edict['LOC6'] = self.LOC6
        zz_desc['LOC6'] = ""
        self.LOC7 = 0x00000007
        zz_edict['LOC7'] = self.LOC7
        zz_desc['LOC7'] = ""
        self.LOC8 = 0x00000008
        zz_edict['LOC8'] = self.LOC8
        zz_desc['LOC8'] = ""
        self.LOC9 = 0x00000009
        zz_edict['LOC9'] = self.LOC9
        zz_desc['LOC9'] = ""
        self.LOC10 = 0x0000000A
        zz_edict['LOC10'] = self.LOC10
        zz_desc['LOC10'] = ""
        super(RM_Enum_PRS_ROUTELOC1_CH7LOC, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_ROUTELOC2_CH8LOC(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.LOC0 = 0x00000000
        zz_edict['LOC0'] = self.LOC0
        zz_desc['LOC0'] = ""
        self.LOC1 = 0x00000001
        zz_edict['LOC1'] = self.LOC1
        zz_desc['LOC1'] = ""
        self.LOC2 = 0x00000002
        zz_edict['LOC2'] = self.LOC2
        zz_desc['LOC2'] = ""
        self.LOC3 = 0x00000003
        zz_edict['LOC3'] = self.LOC3
        zz_desc['LOC3'] = ""
        self.LOC4 = 0x00000004
        zz_edict['LOC4'] = self.LOC4
        zz_desc['LOC4'] = ""
        self.LOC5 = 0x00000005
        zz_edict['LOC5'] = self.LOC5
        zz_desc['LOC5'] = ""
        self.LOC6 = 0x00000006
        zz_edict['LOC6'] = self.LOC6
        zz_desc['LOC6'] = ""
        self.LOC7 = 0x00000007
        zz_edict['LOC7'] = self.LOC7
        zz_desc['LOC7'] = ""
        self.LOC8 = 0x00000008
        zz_edict['LOC8'] = self.LOC8
        zz_desc['LOC8'] = ""
        self.LOC9 = 0x00000009
        zz_edict['LOC9'] = self.LOC9
        zz_desc['LOC9'] = ""
        self.LOC10 = 0x0000000A
        zz_edict['LOC10'] = self.LOC10
        zz_desc['LOC10'] = ""
        super(RM_Enum_PRS_ROUTELOC2_CH8LOC, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_ROUTELOC2_CH9LOC(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.LOC0 = 0x00000000
        zz_edict['LOC0'] = self.LOC0
        zz_desc['LOC0'] = ""
        self.LOC1 = 0x00000001
        zz_edict['LOC1'] = self.LOC1
        zz_desc['LOC1'] = ""
        self.LOC2 = 0x00000002
        zz_edict['LOC2'] = self.LOC2
        zz_desc['LOC2'] = ""
        self.LOC3 = 0x00000003
        zz_edict['LOC3'] = self.LOC3
        zz_desc['LOC3'] = ""
        self.LOC4 = 0x00000004
        zz_edict['LOC4'] = self.LOC4
        zz_desc['LOC4'] = ""
        self.LOC5 = 0x00000005
        zz_edict['LOC5'] = self.LOC5
        zz_desc['LOC5'] = ""
        self.LOC6 = 0x00000006
        zz_edict['LOC6'] = self.LOC6
        zz_desc['LOC6'] = ""
        self.LOC7 = 0x00000007
        zz_edict['LOC7'] = self.LOC7
        zz_desc['LOC7'] = ""
        self.LOC8 = 0x00000008
        zz_edict['LOC8'] = self.LOC8
        zz_desc['LOC8'] = ""
        self.LOC9 = 0x00000009
        zz_edict['LOC9'] = self.LOC9
        zz_desc['LOC9'] = ""
        self.LOC10 = 0x0000000A
        zz_edict['LOC10'] = self.LOC10
        zz_desc['LOC10'] = ""
        self.LOC11 = 0x0000000B
        zz_edict['LOC11'] = self.LOC11
        zz_desc['LOC11'] = ""
        self.LOC12 = 0x0000000C
        zz_edict['LOC12'] = self.LOC12
        zz_desc['LOC12'] = ""
        self.LOC13 = 0x0000000D
        zz_edict['LOC13'] = self.LOC13
        zz_desc['LOC13'] = ""
        self.LOC14 = 0x0000000E
        zz_edict['LOC14'] = self.LOC14
        zz_desc['LOC14'] = ""
        self.LOC15 = 0x0000000F
        zz_edict['LOC15'] = self.LOC15
        zz_desc['LOC15'] = ""
        self.LOC16 = 0x00000010
        zz_edict['LOC16'] = self.LOC16
        zz_desc['LOC16'] = ""
        super(RM_Enum_PRS_ROUTELOC2_CH9LOC, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_ROUTELOC2_CH10LOC(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.LOC0 = 0x00000000
        zz_edict['LOC0'] = self.LOC0
        zz_desc['LOC0'] = ""
        self.LOC1 = 0x00000001
        zz_edict['LOC1'] = self.LOC1
        zz_desc['LOC1'] = ""
        self.LOC2 = 0x00000002
        zz_edict['LOC2'] = self.LOC2
        zz_desc['LOC2'] = ""
        self.LOC3 = 0x00000003
        zz_edict['LOC3'] = self.LOC3
        zz_desc['LOC3'] = ""
        self.LOC4 = 0x00000004
        zz_edict['LOC4'] = self.LOC4
        zz_desc['LOC4'] = ""
        self.LOC5 = 0x00000005
        zz_edict['LOC5'] = self.LOC5
        zz_desc['LOC5'] = ""
        super(RM_Enum_PRS_ROUTELOC2_CH10LOC, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_ROUTELOC2_CH11LOC(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.LOC0 = 0x00000000
        zz_edict['LOC0'] = self.LOC0
        zz_desc['LOC0'] = ""
        self.LOC1 = 0x00000001
        zz_edict['LOC1'] = self.LOC1
        zz_desc['LOC1'] = ""
        self.LOC2 = 0x00000002
        zz_edict['LOC2'] = self.LOC2
        zz_desc['LOC2'] = ""
        self.LOC3 = 0x00000003
        zz_edict['LOC3'] = self.LOC3
        zz_desc['LOC3'] = ""
        self.LOC4 = 0x00000004
        zz_edict['LOC4'] = self.LOC4
        zz_desc['LOC4'] = ""
        self.LOC5 = 0x00000005
        zz_edict['LOC5'] = self.LOC5
        zz_desc['LOC5'] = ""
        super(RM_Enum_PRS_ROUTELOC2_CH11LOC, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CTRL_SEVONPRSSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.PRSCH0 = 0x00000000
        zz_edict['PRSCH0'] = self.PRSCH0
        zz_desc['PRSCH0'] = ""
        self.PRSCH1 = 0x00000001
        zz_edict['PRSCH1'] = self.PRSCH1
        zz_desc['PRSCH1'] = ""
        self.PRSCH2 = 0x00000002
        zz_edict['PRSCH2'] = self.PRSCH2
        zz_desc['PRSCH2'] = ""
        self.PRSCH3 = 0x00000003
        zz_edict['PRSCH3'] = self.PRSCH3
        zz_desc['PRSCH3'] = ""
        self.PRSCH4 = 0x00000004
        zz_edict['PRSCH4'] = self.PRSCH4
        zz_desc['PRSCH4'] = ""
        self.PRSCH5 = 0x00000005
        zz_edict['PRSCH5'] = self.PRSCH5
        zz_desc['PRSCH5'] = ""
        self.PRSCH6 = 0x00000006
        zz_edict['PRSCH6'] = self.PRSCH6
        zz_desc['PRSCH6'] = ""
        self.PRSCH7 = 0x00000007
        zz_edict['PRSCH7'] = self.PRSCH7
        zz_desc['PRSCH7'] = ""
        self.PRSCH8 = 0x00000008
        zz_edict['PRSCH8'] = self.PRSCH8
        zz_desc['PRSCH8'] = ""
        self.PRSCH9 = 0x00000009
        zz_edict['PRSCH9'] = self.PRSCH9
        zz_desc['PRSCH9'] = ""
        self.PRSCH10 = 0x0000000A
        zz_edict['PRSCH10'] = self.PRSCH10
        zz_desc['PRSCH10'] = ""
        self.PRSCH11 = 0x0000000B
        zz_edict['PRSCH11'] = self.PRSCH11
        zz_desc['PRSCH11'] = ""
        super(RM_Enum_PRS_CTRL_SEVONPRSSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_DMAREQ0_PRSSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.PRSCH0 = 0x00000000
        zz_edict['PRSCH0'] = self.PRSCH0
        zz_desc['PRSCH0'] = ""
        self.PRSCH1 = 0x00000001
        zz_edict['PRSCH1'] = self.PRSCH1
        zz_desc['PRSCH1'] = ""
        self.PRSCH2 = 0x00000002
        zz_edict['PRSCH2'] = self.PRSCH2
        zz_desc['PRSCH2'] = ""
        self.PRSCH3 = 0x00000003
        zz_edict['PRSCH3'] = self.PRSCH3
        zz_desc['PRSCH3'] = ""
        self.PRSCH4 = 0x00000004
        zz_edict['PRSCH4'] = self.PRSCH4
        zz_desc['PRSCH4'] = ""
        self.PRSCH5 = 0x00000005
        zz_edict['PRSCH5'] = self.PRSCH5
        zz_desc['PRSCH5'] = ""
        self.PRSCH6 = 0x00000006
        zz_edict['PRSCH6'] = self.PRSCH6
        zz_desc['PRSCH6'] = ""
        self.PRSCH7 = 0x00000007
        zz_edict['PRSCH7'] = self.PRSCH7
        zz_desc['PRSCH7'] = ""
        self.PRSCH8 = 0x00000008
        zz_edict['PRSCH8'] = self.PRSCH8
        zz_desc['PRSCH8'] = ""
        self.PRSCH9 = 0x00000009
        zz_edict['PRSCH9'] = self.PRSCH9
        zz_desc['PRSCH9'] = ""
        self.PRSCH10 = 0x0000000A
        zz_edict['PRSCH10'] = self.PRSCH10
        zz_desc['PRSCH10'] = ""
        self.PRSCH11 = 0x0000000B
        zz_edict['PRSCH11'] = self.PRSCH11
        zz_desc['PRSCH11'] = ""
        super(RM_Enum_PRS_DMAREQ0_PRSSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_DMAREQ1_PRSSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.PRSCH0 = 0x00000000
        zz_edict['PRSCH0'] = self.PRSCH0
        zz_desc['PRSCH0'] = ""
        self.PRSCH1 = 0x00000001
        zz_edict['PRSCH1'] = self.PRSCH1
        zz_desc['PRSCH1'] = ""
        self.PRSCH2 = 0x00000002
        zz_edict['PRSCH2'] = self.PRSCH2
        zz_desc['PRSCH2'] = ""
        self.PRSCH3 = 0x00000003
        zz_edict['PRSCH3'] = self.PRSCH3
        zz_desc['PRSCH3'] = ""
        self.PRSCH4 = 0x00000004
        zz_edict['PRSCH4'] = self.PRSCH4
        zz_desc['PRSCH4'] = ""
        self.PRSCH5 = 0x00000005
        zz_edict['PRSCH5'] = self.PRSCH5
        zz_desc['PRSCH5'] = ""
        self.PRSCH6 = 0x00000006
        zz_edict['PRSCH6'] = self.PRSCH6
        zz_desc['PRSCH6'] = ""
        self.PRSCH7 = 0x00000007
        zz_edict['PRSCH7'] = self.PRSCH7
        zz_desc['PRSCH7'] = ""
        self.PRSCH8 = 0x00000008
        zz_edict['PRSCH8'] = self.PRSCH8
        zz_desc['PRSCH8'] = ""
        self.PRSCH9 = 0x00000009
        zz_edict['PRSCH9'] = self.PRSCH9
        zz_desc['PRSCH9'] = ""
        self.PRSCH10 = 0x0000000A
        zz_edict['PRSCH10'] = self.PRSCH10
        zz_desc['PRSCH10'] = ""
        self.PRSCH11 = 0x0000000B
        zz_edict['PRSCH11'] = self.PRSCH11
        zz_desc['PRSCH11'] = ""
        super(RM_Enum_PRS_DMAREQ1_PRSSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH0_CTRL_SOURCESEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.NONE = 0x00000000
        zz_edict['NONE'] = self.NONE
        zz_desc['NONE'] = ""
        self.PRSL = 0x00000001
        zz_edict['PRSL'] = self.PRSL
        zz_desc['PRSL'] = ""
        self.PRSH = 0x00000002
        zz_edict['PRSH'] = self.PRSH
        zz_desc['PRSH'] = ""
        self.ACMP0 = 0x00000003
        zz_edict['ACMP0'] = self.ACMP0
        zz_desc['ACMP0'] = ""
        self.ACMP1 = 0x00000004
        zz_edict['ACMP1'] = self.ACMP1
        zz_desc['ACMP1'] = ""
        self.ADC0 = 0x00000005
        zz_edict['ADC0'] = self.ADC0
        zz_desc['ADC0'] = ""
        self.CSEN = 0x00000006
        zz_edict['CSEN'] = self.CSEN
        zz_desc['CSEN'] = ""
        self.LESENSEL = 0x00000007
        zz_edict['LESENSEL'] = self.LESENSEL
        zz_desc['LESENSEL'] = ""
        self.LESENSEH = 0x00000008
        zz_edict['LESENSEH'] = self.LESENSEH
        zz_desc['LESENSEH'] = ""
        self.LESENSED = 0x00000009
        zz_edict['LESENSED'] = self.LESENSED
        zz_desc['LESENSED'] = ""
        self.LESENSE = 0x0000000A
        zz_edict['LESENSE'] = self.LESENSE
        zz_desc['LESENSE'] = ""
        self.RTCC = 0x0000000B
        zz_edict['RTCC'] = self.RTCC
        zz_desc['RTCC'] = ""
        self.GPIOL = 0x0000000C
        zz_edict['GPIOL'] = self.GPIOL
        zz_desc['GPIOL'] = ""
        self.GPIOH = 0x0000000D
        zz_edict['GPIOH'] = self.GPIOH
        zz_desc['GPIOH'] = ""
        self.LETIMER0 = 0x0000000E
        zz_edict['LETIMER0'] = self.LETIMER0
        zz_desc['LETIMER0'] = ""
        self.PCNT0 = 0x0000000F
        zz_edict['PCNT0'] = self.PCNT0
        zz_desc['PCNT0'] = ""
        self.PCNT1 = 0x00000010
        zz_edict['PCNT1'] = self.PCNT1
        zz_desc['PCNT1'] = ""
        self.PCNT2 = 0x00000011
        zz_edict['PCNT2'] = self.PCNT2
        zz_desc['PCNT2'] = ""
        self.CMU = 0x00000012
        zz_edict['CMU'] = self.CMU
        zz_desc['CMU'] = ""
        self.LETEST = 0x00000013
        zz_edict['LETEST'] = self.LETEST
        zz_desc['LETEST'] = ""
        self.MANTESTL = 0x00000014
        zz_edict['MANTESTL'] = self.MANTESTL
        zz_desc['MANTESTL'] = ""
        self.MANTESTH = 0x00000015
        zz_edict['MANTESTH'] = self.MANTESTH
        zz_desc['MANTESTH'] = ""
        self.EMUL = 0x00000016
        zz_edict['EMUL'] = self.EMUL
        zz_desc['EMUL'] = ""
        self.EMUH = 0x00000017
        zz_edict['EMUH'] = self.EMUH
        zz_desc['EMUH'] = ""
        self.VDAC0 = 0x00000018
        zz_edict['VDAC0'] = self.VDAC0
        zz_desc['VDAC0'] = ""
        self.RFSENSE = 0x00000019
        zz_edict['RFSENSE'] = self.RFSENSE
        zz_desc['RFSENSE'] = ""
        self.CRYOTIMER = 0x0000001A
        zz_edict['CRYOTIMER'] = self.CRYOTIMER
        zz_desc['CRYOTIMER'] = ""
        self.USART0 = 0x00000030
        zz_edict['USART0'] = self.USART0
        zz_desc['USART0'] = ""
        self.USART1 = 0x00000031
        zz_edict['USART1'] = self.USART1
        zz_desc['USART1'] = ""
        self.USART2 = 0x00000032
        zz_edict['USART2'] = self.USART2
        zz_desc['USART2'] = ""
        self.USART3 = 0x00000033
        zz_edict['USART3'] = self.USART3
        zz_desc['USART3'] = ""
        self.TIMER0 = 0x0000003C
        zz_edict['TIMER0'] = self.TIMER0
        zz_desc['TIMER0'] = ""
        self.TIMER1 = 0x0000003D
        zz_edict['TIMER1'] = self.TIMER1
        zz_desc['TIMER1'] = ""
        self.WTIMER0 = 0x0000003E
        zz_edict['WTIMER0'] = self.WTIMER0
        zz_desc['WTIMER0'] = ""
        self.WTIMER1 = 0x0000003F
        zz_edict['WTIMER1'] = self.WTIMER1
        zz_desc['WTIMER1'] = ""
        self.CM4 = 0x00000043
        zz_edict['CM4'] = self.CM4
        zz_desc['CM4'] = ""
        self.DMEM0 = 0x00000047
        zz_edict['DMEM0'] = self.DMEM0
        zz_desc['DMEM0'] = ""
        self.DMEM1 = 0x00000048
        zz_edict['DMEM1'] = self.DMEM1
        zz_desc['DMEM1'] = ""
        self.RACH = 0x00000050
        zz_edict['RACH'] = self.RACH
        zz_desc['RACH'] = ""
        self.RAC = 0x00000051
        zz_edict['RAC'] = self.RAC
        zz_desc['RAC'] = ""
        self.BUFC = 0x00000052
        zz_edict['BUFC'] = self.BUFC
        zz_desc['BUFC'] = ""
        self.PROTIMERL = 0x00000053
        zz_edict['PROTIMERL'] = self.PROTIMERL
        zz_desc['PROTIMERL'] = ""
        self.PROTIMERH = 0x00000054
        zz_edict['PROTIMERH'] = self.PROTIMERH
        zz_desc['PROTIMERH'] = ""
        self.FRC = 0x00000055
        zz_edict['FRC'] = self.FRC
        zz_desc['FRC'] = ""
        self.MODEML = 0x00000056
        zz_edict['MODEML'] = self.MODEML
        zz_desc['MODEML'] = ""
        self.MODEMH = 0x00000057
        zz_edict['MODEMH'] = self.MODEMH
        zz_desc['MODEMH'] = ""
        self.AGC = 0x00000058
        zz_edict['AGC'] = self.AGC
        zz_desc['AGC'] = ""
        self.SYNTH = 0x0000005A
        zz_edict['SYNTH'] = self.SYNTH
        zz_desc['SYNTH'] = ""
        super(RM_Enum_PRS_CH0_CTRL_SOURCESEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH0_CTRL_EDSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.OFF = 0x00000000
        zz_edict['OFF'] = self.OFF
        zz_desc['OFF'] = ""
        self.POSEDGE = 0x00000001
        zz_edict['POSEDGE'] = self.POSEDGE
        zz_desc['POSEDGE'] = ""
        self.NEGEDGE = 0x00000002
        zz_edict['NEGEDGE'] = self.NEGEDGE
        zz_desc['NEGEDGE'] = ""
        self.BOTHEDGES = 0x00000003
        zz_edict['BOTHEDGES'] = self.BOTHEDGES
        zz_desc['BOTHEDGES'] = ""
        super(RM_Enum_PRS_CH0_CTRL_EDSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH1_CTRL_SOURCESEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.NONE = 0x00000000
        zz_edict['NONE'] = self.NONE
        zz_desc['NONE'] = ""
        self.PRSL = 0x00000001
        zz_edict['PRSL'] = self.PRSL
        zz_desc['PRSL'] = ""
        self.PRSH = 0x00000002
        zz_edict['PRSH'] = self.PRSH
        zz_desc['PRSH'] = ""
        self.ACMP0 = 0x00000003
        zz_edict['ACMP0'] = self.ACMP0
        zz_desc['ACMP0'] = ""
        self.ACMP1 = 0x00000004
        zz_edict['ACMP1'] = self.ACMP1
        zz_desc['ACMP1'] = ""
        self.ADC0 = 0x00000005
        zz_edict['ADC0'] = self.ADC0
        zz_desc['ADC0'] = ""
        self.CSEN = 0x00000006
        zz_edict['CSEN'] = self.CSEN
        zz_desc['CSEN'] = ""
        self.LESENSEL = 0x00000007
        zz_edict['LESENSEL'] = self.LESENSEL
        zz_desc['LESENSEL'] = ""
        self.LESENSEH = 0x00000008
        zz_edict['LESENSEH'] = self.LESENSEH
        zz_desc['LESENSEH'] = ""
        self.LESENSED = 0x00000009
        zz_edict['LESENSED'] = self.LESENSED
        zz_desc['LESENSED'] = ""
        self.LESENSE = 0x0000000A
        zz_edict['LESENSE'] = self.LESENSE
        zz_desc['LESENSE'] = ""
        self.RTCC = 0x0000000B
        zz_edict['RTCC'] = self.RTCC
        zz_desc['RTCC'] = ""
        self.GPIOL = 0x0000000C
        zz_edict['GPIOL'] = self.GPIOL
        zz_desc['GPIOL'] = ""
        self.GPIOH = 0x0000000D
        zz_edict['GPIOH'] = self.GPIOH
        zz_desc['GPIOH'] = ""
        self.LETIMER0 = 0x0000000E
        zz_edict['LETIMER0'] = self.LETIMER0
        zz_desc['LETIMER0'] = ""
        self.PCNT0 = 0x0000000F
        zz_edict['PCNT0'] = self.PCNT0
        zz_desc['PCNT0'] = ""
        self.PCNT1 = 0x00000010
        zz_edict['PCNT1'] = self.PCNT1
        zz_desc['PCNT1'] = ""
        self.PCNT2 = 0x00000011
        zz_edict['PCNT2'] = self.PCNT2
        zz_desc['PCNT2'] = ""
        self.CMU = 0x00000012
        zz_edict['CMU'] = self.CMU
        zz_desc['CMU'] = ""
        self.LETEST = 0x00000013
        zz_edict['LETEST'] = self.LETEST
        zz_desc['LETEST'] = ""
        self.MANTESTL = 0x00000014
        zz_edict['MANTESTL'] = self.MANTESTL
        zz_desc['MANTESTL'] = ""
        self.MANTESTH = 0x00000015
        zz_edict['MANTESTH'] = self.MANTESTH
        zz_desc['MANTESTH'] = ""
        self.EMUL = 0x00000016
        zz_edict['EMUL'] = self.EMUL
        zz_desc['EMUL'] = ""
        self.EMUH = 0x00000017
        zz_edict['EMUH'] = self.EMUH
        zz_desc['EMUH'] = ""
        self.VDAC0 = 0x00000018
        zz_edict['VDAC0'] = self.VDAC0
        zz_desc['VDAC0'] = ""
        self.RFSENSE = 0x00000019
        zz_edict['RFSENSE'] = self.RFSENSE
        zz_desc['RFSENSE'] = ""
        self.CRYOTIMER = 0x0000001A
        zz_edict['CRYOTIMER'] = self.CRYOTIMER
        zz_desc['CRYOTIMER'] = ""
        self.USART0 = 0x00000030
        zz_edict['USART0'] = self.USART0
        zz_desc['USART0'] = ""
        self.USART1 = 0x00000031
        zz_edict['USART1'] = self.USART1
        zz_desc['USART1'] = ""
        self.USART2 = 0x00000032
        zz_edict['USART2'] = self.USART2
        zz_desc['USART2'] = ""
        self.USART3 = 0x00000033
        zz_edict['USART3'] = self.USART3
        zz_desc['USART3'] = ""
        self.TIMER0 = 0x0000003C
        zz_edict['TIMER0'] = self.TIMER0
        zz_desc['TIMER0'] = ""
        self.TIMER1 = 0x0000003D
        zz_edict['TIMER1'] = self.TIMER1
        zz_desc['TIMER1'] = ""
        self.WTIMER0 = 0x0000003E
        zz_edict['WTIMER0'] = self.WTIMER0
        zz_desc['WTIMER0'] = ""
        self.WTIMER1 = 0x0000003F
        zz_edict['WTIMER1'] = self.WTIMER1
        zz_desc['WTIMER1'] = ""
        self.CM4 = 0x00000043
        zz_edict['CM4'] = self.CM4
        zz_desc['CM4'] = ""
        self.DMEM0 = 0x00000047
        zz_edict['DMEM0'] = self.DMEM0
        zz_desc['DMEM0'] = ""
        self.DMEM1 = 0x00000048
        zz_edict['DMEM1'] = self.DMEM1
        zz_desc['DMEM1'] = ""
        self.RACH = 0x00000050
        zz_edict['RACH'] = self.RACH
        zz_desc['RACH'] = ""
        self.RAC = 0x00000051
        zz_edict['RAC'] = self.RAC
        zz_desc['RAC'] = ""
        self.BUFC = 0x00000052
        zz_edict['BUFC'] = self.BUFC
        zz_desc['BUFC'] = ""
        self.PROTIMERL = 0x00000053
        zz_edict['PROTIMERL'] = self.PROTIMERL
        zz_desc['PROTIMERL'] = ""
        self.PROTIMERH = 0x00000054
        zz_edict['PROTIMERH'] = self.PROTIMERH
        zz_desc['PROTIMERH'] = ""
        self.FRC = 0x00000055
        zz_edict['FRC'] = self.FRC
        zz_desc['FRC'] = ""
        self.MODEML = 0x00000056
        zz_edict['MODEML'] = self.MODEML
        zz_desc['MODEML'] = ""
        self.MODEMH = 0x00000057
        zz_edict['MODEMH'] = self.MODEMH
        zz_desc['MODEMH'] = ""
        self.AGC = 0x00000058
        zz_edict['AGC'] = self.AGC
        zz_desc['AGC'] = ""
        self.SYNTH = 0x0000005A
        zz_edict['SYNTH'] = self.SYNTH
        zz_desc['SYNTH'] = ""
        super(RM_Enum_PRS_CH1_CTRL_SOURCESEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH1_CTRL_EDSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.OFF = 0x00000000
        zz_edict['OFF'] = self.OFF
        zz_desc['OFF'] = ""
        self.POSEDGE = 0x00000001
        zz_edict['POSEDGE'] = self.POSEDGE
        zz_desc['POSEDGE'] = ""
        self.NEGEDGE = 0x00000002
        zz_edict['NEGEDGE'] = self.NEGEDGE
        zz_desc['NEGEDGE'] = ""
        self.BOTHEDGES = 0x00000003
        zz_edict['BOTHEDGES'] = self.BOTHEDGES
        zz_desc['BOTHEDGES'] = ""
        super(RM_Enum_PRS_CH1_CTRL_EDSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH2_CTRL_SOURCESEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.NONE = 0x00000000
        zz_edict['NONE'] = self.NONE
        zz_desc['NONE'] = ""
        self.PRSL = 0x00000001
        zz_edict['PRSL'] = self.PRSL
        zz_desc['PRSL'] = ""
        self.PRSH = 0x00000002
        zz_edict['PRSH'] = self.PRSH
        zz_desc['PRSH'] = ""
        self.ACMP0 = 0x00000003
        zz_edict['ACMP0'] = self.ACMP0
        zz_desc['ACMP0'] = ""
        self.ACMP1 = 0x00000004
        zz_edict['ACMP1'] = self.ACMP1
        zz_desc['ACMP1'] = ""
        self.ADC0 = 0x00000005
        zz_edict['ADC0'] = self.ADC0
        zz_desc['ADC0'] = ""
        self.CSEN = 0x00000006
        zz_edict['CSEN'] = self.CSEN
        zz_desc['CSEN'] = ""
        self.LESENSEL = 0x00000007
        zz_edict['LESENSEL'] = self.LESENSEL
        zz_desc['LESENSEL'] = ""
        self.LESENSEH = 0x00000008
        zz_edict['LESENSEH'] = self.LESENSEH
        zz_desc['LESENSEH'] = ""
        self.LESENSED = 0x00000009
        zz_edict['LESENSED'] = self.LESENSED
        zz_desc['LESENSED'] = ""
        self.LESENSE = 0x0000000A
        zz_edict['LESENSE'] = self.LESENSE
        zz_desc['LESENSE'] = ""
        self.RTCC = 0x0000000B
        zz_edict['RTCC'] = self.RTCC
        zz_desc['RTCC'] = ""
        self.GPIOL = 0x0000000C
        zz_edict['GPIOL'] = self.GPIOL
        zz_desc['GPIOL'] = ""
        self.GPIOH = 0x0000000D
        zz_edict['GPIOH'] = self.GPIOH
        zz_desc['GPIOH'] = ""
        self.LETIMER0 = 0x0000000E
        zz_edict['LETIMER0'] = self.LETIMER0
        zz_desc['LETIMER0'] = ""
        self.PCNT0 = 0x0000000F
        zz_edict['PCNT0'] = self.PCNT0
        zz_desc['PCNT0'] = ""
        self.PCNT1 = 0x00000010
        zz_edict['PCNT1'] = self.PCNT1
        zz_desc['PCNT1'] = ""
        self.PCNT2 = 0x00000011
        zz_edict['PCNT2'] = self.PCNT2
        zz_desc['PCNT2'] = ""
        self.CMU = 0x00000012
        zz_edict['CMU'] = self.CMU
        zz_desc['CMU'] = ""
        self.LETEST = 0x00000013
        zz_edict['LETEST'] = self.LETEST
        zz_desc['LETEST'] = ""
        self.MANTESTL = 0x00000014
        zz_edict['MANTESTL'] = self.MANTESTL
        zz_desc['MANTESTL'] = ""
        self.MANTESTH = 0x00000015
        zz_edict['MANTESTH'] = self.MANTESTH
        zz_desc['MANTESTH'] = ""
        self.EMUL = 0x00000016
        zz_edict['EMUL'] = self.EMUL
        zz_desc['EMUL'] = ""
        self.EMUH = 0x00000017
        zz_edict['EMUH'] = self.EMUH
        zz_desc['EMUH'] = ""
        self.VDAC0 = 0x00000018
        zz_edict['VDAC0'] = self.VDAC0
        zz_desc['VDAC0'] = ""
        self.RFSENSE = 0x00000019
        zz_edict['RFSENSE'] = self.RFSENSE
        zz_desc['RFSENSE'] = ""
        self.CRYOTIMER = 0x0000001A
        zz_edict['CRYOTIMER'] = self.CRYOTIMER
        zz_desc['CRYOTIMER'] = ""
        self.USART0 = 0x00000030
        zz_edict['USART0'] = self.USART0
        zz_desc['USART0'] = ""
        self.USART1 = 0x00000031
        zz_edict['USART1'] = self.USART1
        zz_desc['USART1'] = ""
        self.USART2 = 0x00000032
        zz_edict['USART2'] = self.USART2
        zz_desc['USART2'] = ""
        self.USART3 = 0x00000033
        zz_edict['USART3'] = self.USART3
        zz_desc['USART3'] = ""
        self.TIMER0 = 0x0000003C
        zz_edict['TIMER0'] = self.TIMER0
        zz_desc['TIMER0'] = ""
        self.TIMER1 = 0x0000003D
        zz_edict['TIMER1'] = self.TIMER1
        zz_desc['TIMER1'] = ""
        self.WTIMER0 = 0x0000003E
        zz_edict['WTIMER0'] = self.WTIMER0
        zz_desc['WTIMER0'] = ""
        self.WTIMER1 = 0x0000003F
        zz_edict['WTIMER1'] = self.WTIMER1
        zz_desc['WTIMER1'] = ""
        self.CM4 = 0x00000043
        zz_edict['CM4'] = self.CM4
        zz_desc['CM4'] = ""
        self.DMEM0 = 0x00000047
        zz_edict['DMEM0'] = self.DMEM0
        zz_desc['DMEM0'] = ""
        self.DMEM1 = 0x00000048
        zz_edict['DMEM1'] = self.DMEM1
        zz_desc['DMEM1'] = ""
        self.RACH = 0x00000050
        zz_edict['RACH'] = self.RACH
        zz_desc['RACH'] = ""
        self.RAC = 0x00000051
        zz_edict['RAC'] = self.RAC
        zz_desc['RAC'] = ""
        self.BUFC = 0x00000052
        zz_edict['BUFC'] = self.BUFC
        zz_desc['BUFC'] = ""
        self.PROTIMERL = 0x00000053
        zz_edict['PROTIMERL'] = self.PROTIMERL
        zz_desc['PROTIMERL'] = ""
        self.PROTIMERH = 0x00000054
        zz_edict['PROTIMERH'] = self.PROTIMERH
        zz_desc['PROTIMERH'] = ""
        self.FRC = 0x00000055
        zz_edict['FRC'] = self.FRC
        zz_desc['FRC'] = ""
        self.MODEML = 0x00000056
        zz_edict['MODEML'] = self.MODEML
        zz_desc['MODEML'] = ""
        self.MODEMH = 0x00000057
        zz_edict['MODEMH'] = self.MODEMH
        zz_desc['MODEMH'] = ""
        self.AGC = 0x00000058
        zz_edict['AGC'] = self.AGC
        zz_desc['AGC'] = ""
        self.SYNTH = 0x0000005A
        zz_edict['SYNTH'] = self.SYNTH
        zz_desc['SYNTH'] = ""
        super(RM_Enum_PRS_CH2_CTRL_SOURCESEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH2_CTRL_EDSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.OFF = 0x00000000
        zz_edict['OFF'] = self.OFF
        zz_desc['OFF'] = ""
        self.POSEDGE = 0x00000001
        zz_edict['POSEDGE'] = self.POSEDGE
        zz_desc['POSEDGE'] = ""
        self.NEGEDGE = 0x00000002
        zz_edict['NEGEDGE'] = self.NEGEDGE
        zz_desc['NEGEDGE'] = ""
        self.BOTHEDGES = 0x00000003
        zz_edict['BOTHEDGES'] = self.BOTHEDGES
        zz_desc['BOTHEDGES'] = ""
        super(RM_Enum_PRS_CH2_CTRL_EDSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH3_CTRL_SOURCESEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.NONE = 0x00000000
        zz_edict['NONE'] = self.NONE
        zz_desc['NONE'] = ""
        self.PRSL = 0x00000001
        zz_edict['PRSL'] = self.PRSL
        zz_desc['PRSL'] = ""
        self.PRSH = 0x00000002
        zz_edict['PRSH'] = self.PRSH
        zz_desc['PRSH'] = ""
        self.ACMP0 = 0x00000003
        zz_edict['ACMP0'] = self.ACMP0
        zz_desc['ACMP0'] = ""
        self.ACMP1 = 0x00000004
        zz_edict['ACMP1'] = self.ACMP1
        zz_desc['ACMP1'] = ""
        self.ADC0 = 0x00000005
        zz_edict['ADC0'] = self.ADC0
        zz_desc['ADC0'] = ""
        self.CSEN = 0x00000006
        zz_edict['CSEN'] = self.CSEN
        zz_desc['CSEN'] = ""
        self.LESENSEL = 0x00000007
        zz_edict['LESENSEL'] = self.LESENSEL
        zz_desc['LESENSEL'] = ""
        self.LESENSEH = 0x00000008
        zz_edict['LESENSEH'] = self.LESENSEH
        zz_desc['LESENSEH'] = ""
        self.LESENSED = 0x00000009
        zz_edict['LESENSED'] = self.LESENSED
        zz_desc['LESENSED'] = ""
        self.LESENSE = 0x0000000A
        zz_edict['LESENSE'] = self.LESENSE
        zz_desc['LESENSE'] = ""
        self.RTCC = 0x0000000B
        zz_edict['RTCC'] = self.RTCC
        zz_desc['RTCC'] = ""
        self.GPIOL = 0x0000000C
        zz_edict['GPIOL'] = self.GPIOL
        zz_desc['GPIOL'] = ""
        self.GPIOH = 0x0000000D
        zz_edict['GPIOH'] = self.GPIOH
        zz_desc['GPIOH'] = ""
        self.LETIMER0 = 0x0000000E
        zz_edict['LETIMER0'] = self.LETIMER0
        zz_desc['LETIMER0'] = ""
        self.PCNT0 = 0x0000000F
        zz_edict['PCNT0'] = self.PCNT0
        zz_desc['PCNT0'] = ""
        self.PCNT1 = 0x00000010
        zz_edict['PCNT1'] = self.PCNT1
        zz_desc['PCNT1'] = ""
        self.PCNT2 = 0x00000011
        zz_edict['PCNT2'] = self.PCNT2
        zz_desc['PCNT2'] = ""
        self.CMU = 0x00000012
        zz_edict['CMU'] = self.CMU
        zz_desc['CMU'] = ""
        self.LETEST = 0x00000013
        zz_edict['LETEST'] = self.LETEST
        zz_desc['LETEST'] = ""
        self.MANTESTL = 0x00000014
        zz_edict['MANTESTL'] = self.MANTESTL
        zz_desc['MANTESTL'] = ""
        self.MANTESTH = 0x00000015
        zz_edict['MANTESTH'] = self.MANTESTH
        zz_desc['MANTESTH'] = ""
        self.EMUL = 0x00000016
        zz_edict['EMUL'] = self.EMUL
        zz_desc['EMUL'] = ""
        self.EMUH = 0x00000017
        zz_edict['EMUH'] = self.EMUH
        zz_desc['EMUH'] = ""
        self.VDAC0 = 0x00000018
        zz_edict['VDAC0'] = self.VDAC0
        zz_desc['VDAC0'] = ""
        self.RFSENSE = 0x00000019
        zz_edict['RFSENSE'] = self.RFSENSE
        zz_desc['RFSENSE'] = ""
        self.CRYOTIMER = 0x0000001A
        zz_edict['CRYOTIMER'] = self.CRYOTIMER
        zz_desc['CRYOTIMER'] = ""
        self.USART0 = 0x00000030
        zz_edict['USART0'] = self.USART0
        zz_desc['USART0'] = ""
        self.USART1 = 0x00000031
        zz_edict['USART1'] = self.USART1
        zz_desc['USART1'] = ""
        self.USART2 = 0x00000032
        zz_edict['USART2'] = self.USART2
        zz_desc['USART2'] = ""
        self.USART3 = 0x00000033
        zz_edict['USART3'] = self.USART3
        zz_desc['USART3'] = ""
        self.TIMER0 = 0x0000003C
        zz_edict['TIMER0'] = self.TIMER0
        zz_desc['TIMER0'] = ""
        self.TIMER1 = 0x0000003D
        zz_edict['TIMER1'] = self.TIMER1
        zz_desc['TIMER1'] = ""
        self.WTIMER0 = 0x0000003E
        zz_edict['WTIMER0'] = self.WTIMER0
        zz_desc['WTIMER0'] = ""
        self.WTIMER1 = 0x0000003F
        zz_edict['WTIMER1'] = self.WTIMER1
        zz_desc['WTIMER1'] = ""
        self.CM4 = 0x00000043
        zz_edict['CM4'] = self.CM4
        zz_desc['CM4'] = ""
        self.DMEM0 = 0x00000047
        zz_edict['DMEM0'] = self.DMEM0
        zz_desc['DMEM0'] = ""
        self.DMEM1 = 0x00000048
        zz_edict['DMEM1'] = self.DMEM1
        zz_desc['DMEM1'] = ""
        self.RACH = 0x00000050
        zz_edict['RACH'] = self.RACH
        zz_desc['RACH'] = ""
        self.RAC = 0x00000051
        zz_edict['RAC'] = self.RAC
        zz_desc['RAC'] = ""
        self.BUFC = 0x00000052
        zz_edict['BUFC'] = self.BUFC
        zz_desc['BUFC'] = ""
        self.PROTIMERL = 0x00000053
        zz_edict['PROTIMERL'] = self.PROTIMERL
        zz_desc['PROTIMERL'] = ""
        self.PROTIMERH = 0x00000054
        zz_edict['PROTIMERH'] = self.PROTIMERH
        zz_desc['PROTIMERH'] = ""
        self.FRC = 0x00000055
        zz_edict['FRC'] = self.FRC
        zz_desc['FRC'] = ""
        self.MODEML = 0x00000056
        zz_edict['MODEML'] = self.MODEML
        zz_desc['MODEML'] = ""
        self.MODEMH = 0x00000057
        zz_edict['MODEMH'] = self.MODEMH
        zz_desc['MODEMH'] = ""
        self.AGC = 0x00000058
        zz_edict['AGC'] = self.AGC
        zz_desc['AGC'] = ""
        self.SYNTH = 0x0000005A
        zz_edict['SYNTH'] = self.SYNTH
        zz_desc['SYNTH'] = ""
        super(RM_Enum_PRS_CH3_CTRL_SOURCESEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH3_CTRL_EDSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.OFF = 0x00000000
        zz_edict['OFF'] = self.OFF
        zz_desc['OFF'] = ""
        self.POSEDGE = 0x00000001
        zz_edict['POSEDGE'] = self.POSEDGE
        zz_desc['POSEDGE'] = ""
        self.NEGEDGE = 0x00000002
        zz_edict['NEGEDGE'] = self.NEGEDGE
        zz_desc['NEGEDGE'] = ""
        self.BOTHEDGES = 0x00000003
        zz_edict['BOTHEDGES'] = self.BOTHEDGES
        zz_desc['BOTHEDGES'] = ""
        super(RM_Enum_PRS_CH3_CTRL_EDSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH4_CTRL_SOURCESEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.NONE = 0x00000000
        zz_edict['NONE'] = self.NONE
        zz_desc['NONE'] = ""
        self.PRSL = 0x00000001
        zz_edict['PRSL'] = self.PRSL
        zz_desc['PRSL'] = ""
        self.PRSH = 0x00000002
        zz_edict['PRSH'] = self.PRSH
        zz_desc['PRSH'] = ""
        self.ACMP0 = 0x00000003
        zz_edict['ACMP0'] = self.ACMP0
        zz_desc['ACMP0'] = ""
        self.ACMP1 = 0x00000004
        zz_edict['ACMP1'] = self.ACMP1
        zz_desc['ACMP1'] = ""
        self.ADC0 = 0x00000005
        zz_edict['ADC0'] = self.ADC0
        zz_desc['ADC0'] = ""
        self.CSEN = 0x00000006
        zz_edict['CSEN'] = self.CSEN
        zz_desc['CSEN'] = ""
        self.LESENSEL = 0x00000007
        zz_edict['LESENSEL'] = self.LESENSEL
        zz_desc['LESENSEL'] = ""
        self.LESENSEH = 0x00000008
        zz_edict['LESENSEH'] = self.LESENSEH
        zz_desc['LESENSEH'] = ""
        self.LESENSED = 0x00000009
        zz_edict['LESENSED'] = self.LESENSED
        zz_desc['LESENSED'] = ""
        self.LESENSE = 0x0000000A
        zz_edict['LESENSE'] = self.LESENSE
        zz_desc['LESENSE'] = ""
        self.RTCC = 0x0000000B
        zz_edict['RTCC'] = self.RTCC
        zz_desc['RTCC'] = ""
        self.GPIOL = 0x0000000C
        zz_edict['GPIOL'] = self.GPIOL
        zz_desc['GPIOL'] = ""
        self.GPIOH = 0x0000000D
        zz_edict['GPIOH'] = self.GPIOH
        zz_desc['GPIOH'] = ""
        self.LETIMER0 = 0x0000000E
        zz_edict['LETIMER0'] = self.LETIMER0
        zz_desc['LETIMER0'] = ""
        self.PCNT0 = 0x0000000F
        zz_edict['PCNT0'] = self.PCNT0
        zz_desc['PCNT0'] = ""
        self.PCNT1 = 0x00000010
        zz_edict['PCNT1'] = self.PCNT1
        zz_desc['PCNT1'] = ""
        self.PCNT2 = 0x00000011
        zz_edict['PCNT2'] = self.PCNT2
        zz_desc['PCNT2'] = ""
        self.CMU = 0x00000012
        zz_edict['CMU'] = self.CMU
        zz_desc['CMU'] = ""
        self.LETEST = 0x00000013
        zz_edict['LETEST'] = self.LETEST
        zz_desc['LETEST'] = ""
        self.MANTESTL = 0x00000014
        zz_edict['MANTESTL'] = self.MANTESTL
        zz_desc['MANTESTL'] = ""
        self.MANTESTH = 0x00000015
        zz_edict['MANTESTH'] = self.MANTESTH
        zz_desc['MANTESTH'] = ""
        self.EMUL = 0x00000016
        zz_edict['EMUL'] = self.EMUL
        zz_desc['EMUL'] = ""
        self.EMUH = 0x00000017
        zz_edict['EMUH'] = self.EMUH
        zz_desc['EMUH'] = ""
        self.VDAC0 = 0x00000018
        zz_edict['VDAC0'] = self.VDAC0
        zz_desc['VDAC0'] = ""
        self.RFSENSE = 0x00000019
        zz_edict['RFSENSE'] = self.RFSENSE
        zz_desc['RFSENSE'] = ""
        self.CRYOTIMER = 0x0000001A
        zz_edict['CRYOTIMER'] = self.CRYOTIMER
        zz_desc['CRYOTIMER'] = ""
        self.USART0 = 0x00000030
        zz_edict['USART0'] = self.USART0
        zz_desc['USART0'] = ""
        self.USART1 = 0x00000031
        zz_edict['USART1'] = self.USART1
        zz_desc['USART1'] = ""
        self.USART2 = 0x00000032
        zz_edict['USART2'] = self.USART2
        zz_desc['USART2'] = ""
        self.USART3 = 0x00000033
        zz_edict['USART3'] = self.USART3
        zz_desc['USART3'] = ""
        self.TIMER0 = 0x0000003C
        zz_edict['TIMER0'] = self.TIMER0
        zz_desc['TIMER0'] = ""
        self.TIMER1 = 0x0000003D
        zz_edict['TIMER1'] = self.TIMER1
        zz_desc['TIMER1'] = ""
        self.WTIMER0 = 0x0000003E
        zz_edict['WTIMER0'] = self.WTIMER0
        zz_desc['WTIMER0'] = ""
        self.WTIMER1 = 0x0000003F
        zz_edict['WTIMER1'] = self.WTIMER1
        zz_desc['WTIMER1'] = ""
        self.CM4 = 0x00000043
        zz_edict['CM4'] = self.CM4
        zz_desc['CM4'] = ""
        self.DMEM0 = 0x00000047
        zz_edict['DMEM0'] = self.DMEM0
        zz_desc['DMEM0'] = ""
        self.DMEM1 = 0x00000048
        zz_edict['DMEM1'] = self.DMEM1
        zz_desc['DMEM1'] = ""
        self.RACH = 0x00000050
        zz_edict['RACH'] = self.RACH
        zz_desc['RACH'] = ""
        self.RAC = 0x00000051
        zz_edict['RAC'] = self.RAC
        zz_desc['RAC'] = ""
        self.BUFC = 0x00000052
        zz_edict['BUFC'] = self.BUFC
        zz_desc['BUFC'] = ""
        self.PROTIMERL = 0x00000053
        zz_edict['PROTIMERL'] = self.PROTIMERL
        zz_desc['PROTIMERL'] = ""
        self.PROTIMERH = 0x00000054
        zz_edict['PROTIMERH'] = self.PROTIMERH
        zz_desc['PROTIMERH'] = ""
        self.FRC = 0x00000055
        zz_edict['FRC'] = self.FRC
        zz_desc['FRC'] = ""
        self.MODEML = 0x00000056
        zz_edict['MODEML'] = self.MODEML
        zz_desc['MODEML'] = ""
        self.MODEMH = 0x00000057
        zz_edict['MODEMH'] = self.MODEMH
        zz_desc['MODEMH'] = ""
        self.AGC = 0x00000058
        zz_edict['AGC'] = self.AGC
        zz_desc['AGC'] = ""
        self.SYNTH = 0x0000005A
        zz_edict['SYNTH'] = self.SYNTH
        zz_desc['SYNTH'] = ""
        super(RM_Enum_PRS_CH4_CTRL_SOURCESEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH4_CTRL_EDSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.OFF = 0x00000000
        zz_edict['OFF'] = self.OFF
        zz_desc['OFF'] = ""
        self.POSEDGE = 0x00000001
        zz_edict['POSEDGE'] = self.POSEDGE
        zz_desc['POSEDGE'] = ""
        self.NEGEDGE = 0x00000002
        zz_edict['NEGEDGE'] = self.NEGEDGE
        zz_desc['NEGEDGE'] = ""
        self.BOTHEDGES = 0x00000003
        zz_edict['BOTHEDGES'] = self.BOTHEDGES
        zz_desc['BOTHEDGES'] = ""
        super(RM_Enum_PRS_CH4_CTRL_EDSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH5_CTRL_SOURCESEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.NONE = 0x00000000
        zz_edict['NONE'] = self.NONE
        zz_desc['NONE'] = ""
        self.PRSL = 0x00000001
        zz_edict['PRSL'] = self.PRSL
        zz_desc['PRSL'] = ""
        self.PRSH = 0x00000002
        zz_edict['PRSH'] = self.PRSH
        zz_desc['PRSH'] = ""
        self.ACMP0 = 0x00000003
        zz_edict['ACMP0'] = self.ACMP0
        zz_desc['ACMP0'] = ""
        self.ACMP1 = 0x00000004
        zz_edict['ACMP1'] = self.ACMP1
        zz_desc['ACMP1'] = ""
        self.ADC0 = 0x00000005
        zz_edict['ADC0'] = self.ADC0
        zz_desc['ADC0'] = ""
        self.CSEN = 0x00000006
        zz_edict['CSEN'] = self.CSEN
        zz_desc['CSEN'] = ""
        self.LESENSEL = 0x00000007
        zz_edict['LESENSEL'] = self.LESENSEL
        zz_desc['LESENSEL'] = ""
        self.LESENSEH = 0x00000008
        zz_edict['LESENSEH'] = self.LESENSEH
        zz_desc['LESENSEH'] = ""
        self.LESENSED = 0x00000009
        zz_edict['LESENSED'] = self.LESENSED
        zz_desc['LESENSED'] = ""
        self.LESENSE = 0x0000000A
        zz_edict['LESENSE'] = self.LESENSE
        zz_desc['LESENSE'] = ""
        self.RTCC = 0x0000000B
        zz_edict['RTCC'] = self.RTCC
        zz_desc['RTCC'] = ""
        self.GPIOL = 0x0000000C
        zz_edict['GPIOL'] = self.GPIOL
        zz_desc['GPIOL'] = ""
        self.GPIOH = 0x0000000D
        zz_edict['GPIOH'] = self.GPIOH
        zz_desc['GPIOH'] = ""
        self.LETIMER0 = 0x0000000E
        zz_edict['LETIMER0'] = self.LETIMER0
        zz_desc['LETIMER0'] = ""
        self.PCNT0 = 0x0000000F
        zz_edict['PCNT0'] = self.PCNT0
        zz_desc['PCNT0'] = ""
        self.PCNT1 = 0x00000010
        zz_edict['PCNT1'] = self.PCNT1
        zz_desc['PCNT1'] = ""
        self.PCNT2 = 0x00000011
        zz_edict['PCNT2'] = self.PCNT2
        zz_desc['PCNT2'] = ""
        self.CMU = 0x00000012
        zz_edict['CMU'] = self.CMU
        zz_desc['CMU'] = ""
        self.LETEST = 0x00000013
        zz_edict['LETEST'] = self.LETEST
        zz_desc['LETEST'] = ""
        self.MANTESTL = 0x00000014
        zz_edict['MANTESTL'] = self.MANTESTL
        zz_desc['MANTESTL'] = ""
        self.MANTESTH = 0x00000015
        zz_edict['MANTESTH'] = self.MANTESTH
        zz_desc['MANTESTH'] = ""
        self.EMUL = 0x00000016
        zz_edict['EMUL'] = self.EMUL
        zz_desc['EMUL'] = ""
        self.EMUH = 0x00000017
        zz_edict['EMUH'] = self.EMUH
        zz_desc['EMUH'] = ""
        self.VDAC0 = 0x00000018
        zz_edict['VDAC0'] = self.VDAC0
        zz_desc['VDAC0'] = ""
        self.RFSENSE = 0x00000019
        zz_edict['RFSENSE'] = self.RFSENSE
        zz_desc['RFSENSE'] = ""
        self.CRYOTIMER = 0x0000001A
        zz_edict['CRYOTIMER'] = self.CRYOTIMER
        zz_desc['CRYOTIMER'] = ""
        self.USART0 = 0x00000030
        zz_edict['USART0'] = self.USART0
        zz_desc['USART0'] = ""
        self.USART1 = 0x00000031
        zz_edict['USART1'] = self.USART1
        zz_desc['USART1'] = ""
        self.USART2 = 0x00000032
        zz_edict['USART2'] = self.USART2
        zz_desc['USART2'] = ""
        self.USART3 = 0x00000033
        zz_edict['USART3'] = self.USART3
        zz_desc['USART3'] = ""
        self.TIMER0 = 0x0000003C
        zz_edict['TIMER0'] = self.TIMER0
        zz_desc['TIMER0'] = ""
        self.TIMER1 = 0x0000003D
        zz_edict['TIMER1'] = self.TIMER1
        zz_desc['TIMER1'] = ""
        self.WTIMER0 = 0x0000003E
        zz_edict['WTIMER0'] = self.WTIMER0
        zz_desc['WTIMER0'] = ""
        self.WTIMER1 = 0x0000003F
        zz_edict['WTIMER1'] = self.WTIMER1
        zz_desc['WTIMER1'] = ""
        self.CM4 = 0x00000043
        zz_edict['CM4'] = self.CM4
        zz_desc['CM4'] = ""
        self.DMEM0 = 0x00000047
        zz_edict['DMEM0'] = self.DMEM0
        zz_desc['DMEM0'] = ""
        self.DMEM1 = 0x00000048
        zz_edict['DMEM1'] = self.DMEM1
        zz_desc['DMEM1'] = ""
        self.RACH = 0x00000050
        zz_edict['RACH'] = self.RACH
        zz_desc['RACH'] = ""
        self.RAC = 0x00000051
        zz_edict['RAC'] = self.RAC
        zz_desc['RAC'] = ""
        self.BUFC = 0x00000052
        zz_edict['BUFC'] = self.BUFC
        zz_desc['BUFC'] = ""
        self.PROTIMERL = 0x00000053
        zz_edict['PROTIMERL'] = self.PROTIMERL
        zz_desc['PROTIMERL'] = ""
        self.PROTIMERH = 0x00000054
        zz_edict['PROTIMERH'] = self.PROTIMERH
        zz_desc['PROTIMERH'] = ""
        self.FRC = 0x00000055
        zz_edict['FRC'] = self.FRC
        zz_desc['FRC'] = ""
        self.MODEML = 0x00000056
        zz_edict['MODEML'] = self.MODEML
        zz_desc['MODEML'] = ""
        self.MODEMH = 0x00000057
        zz_edict['MODEMH'] = self.MODEMH
        zz_desc['MODEMH'] = ""
        self.AGC = 0x00000058
        zz_edict['AGC'] = self.AGC
        zz_desc['AGC'] = ""
        self.SYNTH = 0x0000005A
        zz_edict['SYNTH'] = self.SYNTH
        zz_desc['SYNTH'] = ""
        super(RM_Enum_PRS_CH5_CTRL_SOURCESEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH5_CTRL_EDSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.OFF = 0x00000000
        zz_edict['OFF'] = self.OFF
        zz_desc['OFF'] = ""
        self.POSEDGE = 0x00000001
        zz_edict['POSEDGE'] = self.POSEDGE
        zz_desc['POSEDGE'] = ""
        self.NEGEDGE = 0x00000002
        zz_edict['NEGEDGE'] = self.NEGEDGE
        zz_desc['NEGEDGE'] = ""
        self.BOTHEDGES = 0x00000003
        zz_edict['BOTHEDGES'] = self.BOTHEDGES
        zz_desc['BOTHEDGES'] = ""
        super(RM_Enum_PRS_CH5_CTRL_EDSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH6_CTRL_SOURCESEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.NONE = 0x00000000
        zz_edict['NONE'] = self.NONE
        zz_desc['NONE'] = ""
        self.PRSL = 0x00000001
        zz_edict['PRSL'] = self.PRSL
        zz_desc['PRSL'] = ""
        self.PRSH = 0x00000002
        zz_edict['PRSH'] = self.PRSH
        zz_desc['PRSH'] = ""
        self.ACMP0 = 0x00000003
        zz_edict['ACMP0'] = self.ACMP0
        zz_desc['ACMP0'] = ""
        self.ACMP1 = 0x00000004
        zz_edict['ACMP1'] = self.ACMP1
        zz_desc['ACMP1'] = ""
        self.ADC0 = 0x00000005
        zz_edict['ADC0'] = self.ADC0
        zz_desc['ADC0'] = ""
        self.CSEN = 0x00000006
        zz_edict['CSEN'] = self.CSEN
        zz_desc['CSEN'] = ""
        self.LESENSEL = 0x00000007
        zz_edict['LESENSEL'] = self.LESENSEL
        zz_desc['LESENSEL'] = ""
        self.LESENSEH = 0x00000008
        zz_edict['LESENSEH'] = self.LESENSEH
        zz_desc['LESENSEH'] = ""
        self.LESENSED = 0x00000009
        zz_edict['LESENSED'] = self.LESENSED
        zz_desc['LESENSED'] = ""
        self.LESENSE = 0x0000000A
        zz_edict['LESENSE'] = self.LESENSE
        zz_desc['LESENSE'] = ""
        self.RTCC = 0x0000000B
        zz_edict['RTCC'] = self.RTCC
        zz_desc['RTCC'] = ""
        self.GPIOL = 0x0000000C
        zz_edict['GPIOL'] = self.GPIOL
        zz_desc['GPIOL'] = ""
        self.GPIOH = 0x0000000D
        zz_edict['GPIOH'] = self.GPIOH
        zz_desc['GPIOH'] = ""
        self.LETIMER0 = 0x0000000E
        zz_edict['LETIMER0'] = self.LETIMER0
        zz_desc['LETIMER0'] = ""
        self.PCNT0 = 0x0000000F
        zz_edict['PCNT0'] = self.PCNT0
        zz_desc['PCNT0'] = ""
        self.PCNT1 = 0x00000010
        zz_edict['PCNT1'] = self.PCNT1
        zz_desc['PCNT1'] = ""
        self.PCNT2 = 0x00000011
        zz_edict['PCNT2'] = self.PCNT2
        zz_desc['PCNT2'] = ""
        self.CMU = 0x00000012
        zz_edict['CMU'] = self.CMU
        zz_desc['CMU'] = ""
        self.LETEST = 0x00000013
        zz_edict['LETEST'] = self.LETEST
        zz_desc['LETEST'] = ""
        self.MANTESTL = 0x00000014
        zz_edict['MANTESTL'] = self.MANTESTL
        zz_desc['MANTESTL'] = ""
        self.MANTESTH = 0x00000015
        zz_edict['MANTESTH'] = self.MANTESTH
        zz_desc['MANTESTH'] = ""
        self.EMUL = 0x00000016
        zz_edict['EMUL'] = self.EMUL
        zz_desc['EMUL'] = ""
        self.EMUH = 0x00000017
        zz_edict['EMUH'] = self.EMUH
        zz_desc['EMUH'] = ""
        self.VDAC0 = 0x00000018
        zz_edict['VDAC0'] = self.VDAC0
        zz_desc['VDAC0'] = ""
        self.RFSENSE = 0x00000019
        zz_edict['RFSENSE'] = self.RFSENSE
        zz_desc['RFSENSE'] = ""
        self.CRYOTIMER = 0x0000001A
        zz_edict['CRYOTIMER'] = self.CRYOTIMER
        zz_desc['CRYOTIMER'] = ""
        self.USART0 = 0x00000030
        zz_edict['USART0'] = self.USART0
        zz_desc['USART0'] = ""
        self.USART1 = 0x00000031
        zz_edict['USART1'] = self.USART1
        zz_desc['USART1'] = ""
        self.USART2 = 0x00000032
        zz_edict['USART2'] = self.USART2
        zz_desc['USART2'] = ""
        self.USART3 = 0x00000033
        zz_edict['USART3'] = self.USART3
        zz_desc['USART3'] = ""
        self.TIMER0 = 0x0000003C
        zz_edict['TIMER0'] = self.TIMER0
        zz_desc['TIMER0'] = ""
        self.TIMER1 = 0x0000003D
        zz_edict['TIMER1'] = self.TIMER1
        zz_desc['TIMER1'] = ""
        self.WTIMER0 = 0x0000003E
        zz_edict['WTIMER0'] = self.WTIMER0
        zz_desc['WTIMER0'] = ""
        self.WTIMER1 = 0x0000003F
        zz_edict['WTIMER1'] = self.WTIMER1
        zz_desc['WTIMER1'] = ""
        self.CM4 = 0x00000043
        zz_edict['CM4'] = self.CM4
        zz_desc['CM4'] = ""
        self.DMEM0 = 0x00000047
        zz_edict['DMEM0'] = self.DMEM0
        zz_desc['DMEM0'] = ""
        self.DMEM1 = 0x00000048
        zz_edict['DMEM1'] = self.DMEM1
        zz_desc['DMEM1'] = ""
        self.RACH = 0x00000050
        zz_edict['RACH'] = self.RACH
        zz_desc['RACH'] = ""
        self.RAC = 0x00000051
        zz_edict['RAC'] = self.RAC
        zz_desc['RAC'] = ""
        self.BUFC = 0x00000052
        zz_edict['BUFC'] = self.BUFC
        zz_desc['BUFC'] = ""
        self.PROTIMERL = 0x00000053
        zz_edict['PROTIMERL'] = self.PROTIMERL
        zz_desc['PROTIMERL'] = ""
        self.PROTIMERH = 0x00000054
        zz_edict['PROTIMERH'] = self.PROTIMERH
        zz_desc['PROTIMERH'] = ""
        self.FRC = 0x00000055
        zz_edict['FRC'] = self.FRC
        zz_desc['FRC'] = ""
        self.MODEML = 0x00000056
        zz_edict['MODEML'] = self.MODEML
        zz_desc['MODEML'] = ""
        self.MODEMH = 0x00000057
        zz_edict['MODEMH'] = self.MODEMH
        zz_desc['MODEMH'] = ""
        self.AGC = 0x00000058
        zz_edict['AGC'] = self.AGC
        zz_desc['AGC'] = ""
        self.SYNTH = 0x0000005A
        zz_edict['SYNTH'] = self.SYNTH
        zz_desc['SYNTH'] = ""
        super(RM_Enum_PRS_CH6_CTRL_SOURCESEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH6_CTRL_EDSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.OFF = 0x00000000
        zz_edict['OFF'] = self.OFF
        zz_desc['OFF'] = ""
        self.POSEDGE = 0x00000001
        zz_edict['POSEDGE'] = self.POSEDGE
        zz_desc['POSEDGE'] = ""
        self.NEGEDGE = 0x00000002
        zz_edict['NEGEDGE'] = self.NEGEDGE
        zz_desc['NEGEDGE'] = ""
        self.BOTHEDGES = 0x00000003
        zz_edict['BOTHEDGES'] = self.BOTHEDGES
        zz_desc['BOTHEDGES'] = ""
        super(RM_Enum_PRS_CH6_CTRL_EDSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH7_CTRL_SOURCESEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.NONE = 0x00000000
        zz_edict['NONE'] = self.NONE
        zz_desc['NONE'] = ""
        self.PRSL = 0x00000001
        zz_edict['PRSL'] = self.PRSL
        zz_desc['PRSL'] = ""
        self.PRSH = 0x00000002
        zz_edict['PRSH'] = self.PRSH
        zz_desc['PRSH'] = ""
        self.ACMP0 = 0x00000003
        zz_edict['ACMP0'] = self.ACMP0
        zz_desc['ACMP0'] = ""
        self.ACMP1 = 0x00000004
        zz_edict['ACMP1'] = self.ACMP1
        zz_desc['ACMP1'] = ""
        self.ADC0 = 0x00000005
        zz_edict['ADC0'] = self.ADC0
        zz_desc['ADC0'] = ""
        self.CSEN = 0x00000006
        zz_edict['CSEN'] = self.CSEN
        zz_desc['CSEN'] = ""
        self.LESENSEL = 0x00000007
        zz_edict['LESENSEL'] = self.LESENSEL
        zz_desc['LESENSEL'] = ""
        self.LESENSEH = 0x00000008
        zz_edict['LESENSEH'] = self.LESENSEH
        zz_desc['LESENSEH'] = ""
        self.LESENSED = 0x00000009
        zz_edict['LESENSED'] = self.LESENSED
        zz_desc['LESENSED'] = ""
        self.LESENSE = 0x0000000A
        zz_edict['LESENSE'] = self.LESENSE
        zz_desc['LESENSE'] = ""
        self.RTCC = 0x0000000B
        zz_edict['RTCC'] = self.RTCC
        zz_desc['RTCC'] = ""
        self.GPIOL = 0x0000000C
        zz_edict['GPIOL'] = self.GPIOL
        zz_desc['GPIOL'] = ""
        self.GPIOH = 0x0000000D
        zz_edict['GPIOH'] = self.GPIOH
        zz_desc['GPIOH'] = ""
        self.LETIMER0 = 0x0000000E
        zz_edict['LETIMER0'] = self.LETIMER0
        zz_desc['LETIMER0'] = ""
        self.PCNT0 = 0x0000000F
        zz_edict['PCNT0'] = self.PCNT0
        zz_desc['PCNT0'] = ""
        self.PCNT1 = 0x00000010
        zz_edict['PCNT1'] = self.PCNT1
        zz_desc['PCNT1'] = ""
        self.PCNT2 = 0x00000011
        zz_edict['PCNT2'] = self.PCNT2
        zz_desc['PCNT2'] = ""
        self.CMU = 0x00000012
        zz_edict['CMU'] = self.CMU
        zz_desc['CMU'] = ""
        self.LETEST = 0x00000013
        zz_edict['LETEST'] = self.LETEST
        zz_desc['LETEST'] = ""
        self.MANTESTL = 0x00000014
        zz_edict['MANTESTL'] = self.MANTESTL
        zz_desc['MANTESTL'] = ""
        self.MANTESTH = 0x00000015
        zz_edict['MANTESTH'] = self.MANTESTH
        zz_desc['MANTESTH'] = ""
        self.EMUL = 0x00000016
        zz_edict['EMUL'] = self.EMUL
        zz_desc['EMUL'] = ""
        self.EMUH = 0x00000017
        zz_edict['EMUH'] = self.EMUH
        zz_desc['EMUH'] = ""
        self.VDAC0 = 0x00000018
        zz_edict['VDAC0'] = self.VDAC0
        zz_desc['VDAC0'] = ""
        self.RFSENSE = 0x00000019
        zz_edict['RFSENSE'] = self.RFSENSE
        zz_desc['RFSENSE'] = ""
        self.CRYOTIMER = 0x0000001A
        zz_edict['CRYOTIMER'] = self.CRYOTIMER
        zz_desc['CRYOTIMER'] = ""
        self.USART0 = 0x00000030
        zz_edict['USART0'] = self.USART0
        zz_desc['USART0'] = ""
        self.USART1 = 0x00000031
        zz_edict['USART1'] = self.USART1
        zz_desc['USART1'] = ""
        self.USART2 = 0x00000032
        zz_edict['USART2'] = self.USART2
        zz_desc['USART2'] = ""
        self.USART3 = 0x00000033
        zz_edict['USART3'] = self.USART3
        zz_desc['USART3'] = ""
        self.TIMER0 = 0x0000003C
        zz_edict['TIMER0'] = self.TIMER0
        zz_desc['TIMER0'] = ""
        self.TIMER1 = 0x0000003D
        zz_edict['TIMER1'] = self.TIMER1
        zz_desc['TIMER1'] = ""
        self.WTIMER0 = 0x0000003E
        zz_edict['WTIMER0'] = self.WTIMER0
        zz_desc['WTIMER0'] = ""
        self.WTIMER1 = 0x0000003F
        zz_edict['WTIMER1'] = self.WTIMER1
        zz_desc['WTIMER1'] = ""
        self.CM4 = 0x00000043
        zz_edict['CM4'] = self.CM4
        zz_desc['CM4'] = ""
        self.DMEM0 = 0x00000047
        zz_edict['DMEM0'] = self.DMEM0
        zz_desc['DMEM0'] = ""
        self.DMEM1 = 0x00000048
        zz_edict['DMEM1'] = self.DMEM1
        zz_desc['DMEM1'] = ""
        self.RACH = 0x00000050
        zz_edict['RACH'] = self.RACH
        zz_desc['RACH'] = ""
        self.RAC = 0x00000051
        zz_edict['RAC'] = self.RAC
        zz_desc['RAC'] = ""
        self.BUFC = 0x00000052
        zz_edict['BUFC'] = self.BUFC
        zz_desc['BUFC'] = ""
        self.PROTIMERL = 0x00000053
        zz_edict['PROTIMERL'] = self.PROTIMERL
        zz_desc['PROTIMERL'] = ""
        self.PROTIMERH = 0x00000054
        zz_edict['PROTIMERH'] = self.PROTIMERH
        zz_desc['PROTIMERH'] = ""
        self.FRC = 0x00000055
        zz_edict['FRC'] = self.FRC
        zz_desc['FRC'] = ""
        self.MODEML = 0x00000056
        zz_edict['MODEML'] = self.MODEML
        zz_desc['MODEML'] = ""
        self.MODEMH = 0x00000057
        zz_edict['MODEMH'] = self.MODEMH
        zz_desc['MODEMH'] = ""
        self.AGC = 0x00000058
        zz_edict['AGC'] = self.AGC
        zz_desc['AGC'] = ""
        self.SYNTH = 0x0000005A
        zz_edict['SYNTH'] = self.SYNTH
        zz_desc['SYNTH'] = ""
        super(RM_Enum_PRS_CH7_CTRL_SOURCESEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH7_CTRL_EDSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.OFF = 0x00000000
        zz_edict['OFF'] = self.OFF
        zz_desc['OFF'] = ""
        self.POSEDGE = 0x00000001
        zz_edict['POSEDGE'] = self.POSEDGE
        zz_desc['POSEDGE'] = ""
        self.NEGEDGE = 0x00000002
        zz_edict['NEGEDGE'] = self.NEGEDGE
        zz_desc['NEGEDGE'] = ""
        self.BOTHEDGES = 0x00000003
        zz_edict['BOTHEDGES'] = self.BOTHEDGES
        zz_desc['BOTHEDGES'] = ""
        super(RM_Enum_PRS_CH7_CTRL_EDSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH8_CTRL_SOURCESEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.NONE = 0x00000000
        zz_edict['NONE'] = self.NONE
        zz_desc['NONE'] = ""
        self.PRSL = 0x00000001
        zz_edict['PRSL'] = self.PRSL
        zz_desc['PRSL'] = ""
        self.PRSH = 0x00000002
        zz_edict['PRSH'] = self.PRSH
        zz_desc['PRSH'] = ""
        self.ACMP0 = 0x00000003
        zz_edict['ACMP0'] = self.ACMP0
        zz_desc['ACMP0'] = ""
        self.ACMP1 = 0x00000004
        zz_edict['ACMP1'] = self.ACMP1
        zz_desc['ACMP1'] = ""
        self.ADC0 = 0x00000005
        zz_edict['ADC0'] = self.ADC0
        zz_desc['ADC0'] = ""
        self.CSEN = 0x00000006
        zz_edict['CSEN'] = self.CSEN
        zz_desc['CSEN'] = ""
        self.LESENSEL = 0x00000007
        zz_edict['LESENSEL'] = self.LESENSEL
        zz_desc['LESENSEL'] = ""
        self.LESENSEH = 0x00000008
        zz_edict['LESENSEH'] = self.LESENSEH
        zz_desc['LESENSEH'] = ""
        self.LESENSED = 0x00000009
        zz_edict['LESENSED'] = self.LESENSED
        zz_desc['LESENSED'] = ""
        self.LESENSE = 0x0000000A
        zz_edict['LESENSE'] = self.LESENSE
        zz_desc['LESENSE'] = ""
        self.RTCC = 0x0000000B
        zz_edict['RTCC'] = self.RTCC
        zz_desc['RTCC'] = ""
        self.GPIOL = 0x0000000C
        zz_edict['GPIOL'] = self.GPIOL
        zz_desc['GPIOL'] = ""
        self.GPIOH = 0x0000000D
        zz_edict['GPIOH'] = self.GPIOH
        zz_desc['GPIOH'] = ""
        self.LETIMER0 = 0x0000000E
        zz_edict['LETIMER0'] = self.LETIMER0
        zz_desc['LETIMER0'] = ""
        self.PCNT0 = 0x0000000F
        zz_edict['PCNT0'] = self.PCNT0
        zz_desc['PCNT0'] = ""
        self.PCNT1 = 0x00000010
        zz_edict['PCNT1'] = self.PCNT1
        zz_desc['PCNT1'] = ""
        self.PCNT2 = 0x00000011
        zz_edict['PCNT2'] = self.PCNT2
        zz_desc['PCNT2'] = ""
        self.CMU = 0x00000012
        zz_edict['CMU'] = self.CMU
        zz_desc['CMU'] = ""
        self.LETEST = 0x00000013
        zz_edict['LETEST'] = self.LETEST
        zz_desc['LETEST'] = ""
        self.MANTESTL = 0x00000014
        zz_edict['MANTESTL'] = self.MANTESTL
        zz_desc['MANTESTL'] = ""
        self.MANTESTH = 0x00000015
        zz_edict['MANTESTH'] = self.MANTESTH
        zz_desc['MANTESTH'] = ""
        self.EMUL = 0x00000016
        zz_edict['EMUL'] = self.EMUL
        zz_desc['EMUL'] = ""
        self.EMUH = 0x00000017
        zz_edict['EMUH'] = self.EMUH
        zz_desc['EMUH'] = ""
        self.VDAC0 = 0x00000018
        zz_edict['VDAC0'] = self.VDAC0
        zz_desc['VDAC0'] = ""
        self.RFSENSE = 0x00000019
        zz_edict['RFSENSE'] = self.RFSENSE
        zz_desc['RFSENSE'] = ""
        self.CRYOTIMER = 0x0000001A
        zz_edict['CRYOTIMER'] = self.CRYOTIMER
        zz_desc['CRYOTIMER'] = ""
        self.USART0 = 0x00000030
        zz_edict['USART0'] = self.USART0
        zz_desc['USART0'] = ""
        self.USART1 = 0x00000031
        zz_edict['USART1'] = self.USART1
        zz_desc['USART1'] = ""
        self.USART2 = 0x00000032
        zz_edict['USART2'] = self.USART2
        zz_desc['USART2'] = ""
        self.USART3 = 0x00000033
        zz_edict['USART3'] = self.USART3
        zz_desc['USART3'] = ""
        self.TIMER0 = 0x0000003C
        zz_edict['TIMER0'] = self.TIMER0
        zz_desc['TIMER0'] = ""
        self.TIMER1 = 0x0000003D
        zz_edict['TIMER1'] = self.TIMER1
        zz_desc['TIMER1'] = ""
        self.WTIMER0 = 0x0000003E
        zz_edict['WTIMER0'] = self.WTIMER0
        zz_desc['WTIMER0'] = ""
        self.WTIMER1 = 0x0000003F
        zz_edict['WTIMER1'] = self.WTIMER1
        zz_desc['WTIMER1'] = ""
        self.CM4 = 0x00000043
        zz_edict['CM4'] = self.CM4
        zz_desc['CM4'] = ""
        self.DMEM0 = 0x00000047
        zz_edict['DMEM0'] = self.DMEM0
        zz_desc['DMEM0'] = ""
        self.DMEM1 = 0x00000048
        zz_edict['DMEM1'] = self.DMEM1
        zz_desc['DMEM1'] = ""
        self.RACH = 0x00000050
        zz_edict['RACH'] = self.RACH
        zz_desc['RACH'] = ""
        self.RAC = 0x00000051
        zz_edict['RAC'] = self.RAC
        zz_desc['RAC'] = ""
        self.BUFC = 0x00000052
        zz_edict['BUFC'] = self.BUFC
        zz_desc['BUFC'] = ""
        self.PROTIMERL = 0x00000053
        zz_edict['PROTIMERL'] = self.PROTIMERL
        zz_desc['PROTIMERL'] = ""
        self.PROTIMERH = 0x00000054
        zz_edict['PROTIMERH'] = self.PROTIMERH
        zz_desc['PROTIMERH'] = ""
        self.FRC = 0x00000055
        zz_edict['FRC'] = self.FRC
        zz_desc['FRC'] = ""
        self.MODEML = 0x00000056
        zz_edict['MODEML'] = self.MODEML
        zz_desc['MODEML'] = ""
        self.MODEMH = 0x00000057
        zz_edict['MODEMH'] = self.MODEMH
        zz_desc['MODEMH'] = ""
        self.AGC = 0x00000058
        zz_edict['AGC'] = self.AGC
        zz_desc['AGC'] = ""
        self.SYNTH = 0x0000005A
        zz_edict['SYNTH'] = self.SYNTH
        zz_desc['SYNTH'] = ""
        super(RM_Enum_PRS_CH8_CTRL_SOURCESEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH8_CTRL_EDSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.OFF = 0x00000000
        zz_edict['OFF'] = self.OFF
        zz_desc['OFF'] = ""
        self.POSEDGE = 0x00000001
        zz_edict['POSEDGE'] = self.POSEDGE
        zz_desc['POSEDGE'] = ""
        self.NEGEDGE = 0x00000002
        zz_edict['NEGEDGE'] = self.NEGEDGE
        zz_desc['NEGEDGE'] = ""
        self.BOTHEDGES = 0x00000003
        zz_edict['BOTHEDGES'] = self.BOTHEDGES
        zz_desc['BOTHEDGES'] = ""
        super(RM_Enum_PRS_CH8_CTRL_EDSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH9_CTRL_SOURCESEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.NONE = 0x00000000
        zz_edict['NONE'] = self.NONE
        zz_desc['NONE'] = ""
        self.PRSL = 0x00000001
        zz_edict['PRSL'] = self.PRSL
        zz_desc['PRSL'] = ""
        self.PRSH = 0x00000002
        zz_edict['PRSH'] = self.PRSH
        zz_desc['PRSH'] = ""
        self.ACMP0 = 0x00000003
        zz_edict['ACMP0'] = self.ACMP0
        zz_desc['ACMP0'] = ""
        self.ACMP1 = 0x00000004
        zz_edict['ACMP1'] = self.ACMP1
        zz_desc['ACMP1'] = ""
        self.ADC0 = 0x00000005
        zz_edict['ADC0'] = self.ADC0
        zz_desc['ADC0'] = ""
        self.CSEN = 0x00000006
        zz_edict['CSEN'] = self.CSEN
        zz_desc['CSEN'] = ""
        self.LESENSEL = 0x00000007
        zz_edict['LESENSEL'] = self.LESENSEL
        zz_desc['LESENSEL'] = ""
        self.LESENSEH = 0x00000008
        zz_edict['LESENSEH'] = self.LESENSEH
        zz_desc['LESENSEH'] = ""
        self.LESENSED = 0x00000009
        zz_edict['LESENSED'] = self.LESENSED
        zz_desc['LESENSED'] = ""
        self.LESENSE = 0x0000000A
        zz_edict['LESENSE'] = self.LESENSE
        zz_desc['LESENSE'] = ""
        self.RTCC = 0x0000000B
        zz_edict['RTCC'] = self.RTCC
        zz_desc['RTCC'] = ""
        self.GPIOL = 0x0000000C
        zz_edict['GPIOL'] = self.GPIOL
        zz_desc['GPIOL'] = ""
        self.GPIOH = 0x0000000D
        zz_edict['GPIOH'] = self.GPIOH
        zz_desc['GPIOH'] = ""
        self.LETIMER0 = 0x0000000E
        zz_edict['LETIMER0'] = self.LETIMER0
        zz_desc['LETIMER0'] = ""
        self.PCNT0 = 0x0000000F
        zz_edict['PCNT0'] = self.PCNT0
        zz_desc['PCNT0'] = ""
        self.PCNT1 = 0x00000010
        zz_edict['PCNT1'] = self.PCNT1
        zz_desc['PCNT1'] = ""
        self.PCNT2 = 0x00000011
        zz_edict['PCNT2'] = self.PCNT2
        zz_desc['PCNT2'] = ""
        self.CMU = 0x00000012
        zz_edict['CMU'] = self.CMU
        zz_desc['CMU'] = ""
        self.LETEST = 0x00000013
        zz_edict['LETEST'] = self.LETEST
        zz_desc['LETEST'] = ""
        self.MANTESTL = 0x00000014
        zz_edict['MANTESTL'] = self.MANTESTL
        zz_desc['MANTESTL'] = ""
        self.MANTESTH = 0x00000015
        zz_edict['MANTESTH'] = self.MANTESTH
        zz_desc['MANTESTH'] = ""
        self.EMUL = 0x00000016
        zz_edict['EMUL'] = self.EMUL
        zz_desc['EMUL'] = ""
        self.EMUH = 0x00000017
        zz_edict['EMUH'] = self.EMUH
        zz_desc['EMUH'] = ""
        self.VDAC0 = 0x00000018
        zz_edict['VDAC0'] = self.VDAC0
        zz_desc['VDAC0'] = ""
        self.RFSENSE = 0x00000019
        zz_edict['RFSENSE'] = self.RFSENSE
        zz_desc['RFSENSE'] = ""
        self.CRYOTIMER = 0x0000001A
        zz_edict['CRYOTIMER'] = self.CRYOTIMER
        zz_desc['CRYOTIMER'] = ""
        self.USART0 = 0x00000030
        zz_edict['USART0'] = self.USART0
        zz_desc['USART0'] = ""
        self.USART1 = 0x00000031
        zz_edict['USART1'] = self.USART1
        zz_desc['USART1'] = ""
        self.USART2 = 0x00000032
        zz_edict['USART2'] = self.USART2
        zz_desc['USART2'] = ""
        self.USART3 = 0x00000033
        zz_edict['USART3'] = self.USART3
        zz_desc['USART3'] = ""
        self.TIMER0 = 0x0000003C
        zz_edict['TIMER0'] = self.TIMER0
        zz_desc['TIMER0'] = ""
        self.TIMER1 = 0x0000003D
        zz_edict['TIMER1'] = self.TIMER1
        zz_desc['TIMER1'] = ""
        self.WTIMER0 = 0x0000003E
        zz_edict['WTIMER0'] = self.WTIMER0
        zz_desc['WTIMER0'] = ""
        self.WTIMER1 = 0x0000003F
        zz_edict['WTIMER1'] = self.WTIMER1
        zz_desc['WTIMER1'] = ""
        self.CM4 = 0x00000043
        zz_edict['CM4'] = self.CM4
        zz_desc['CM4'] = ""
        self.DMEM0 = 0x00000047
        zz_edict['DMEM0'] = self.DMEM0
        zz_desc['DMEM0'] = ""
        self.DMEM1 = 0x00000048
        zz_edict['DMEM1'] = self.DMEM1
        zz_desc['DMEM1'] = ""
        self.RACH = 0x00000050
        zz_edict['RACH'] = self.RACH
        zz_desc['RACH'] = ""
        self.RAC = 0x00000051
        zz_edict['RAC'] = self.RAC
        zz_desc['RAC'] = ""
        self.BUFC = 0x00000052
        zz_edict['BUFC'] = self.BUFC
        zz_desc['BUFC'] = ""
        self.PROTIMERL = 0x00000053
        zz_edict['PROTIMERL'] = self.PROTIMERL
        zz_desc['PROTIMERL'] = ""
        self.PROTIMERH = 0x00000054
        zz_edict['PROTIMERH'] = self.PROTIMERH
        zz_desc['PROTIMERH'] = ""
        self.FRC = 0x00000055
        zz_edict['FRC'] = self.FRC
        zz_desc['FRC'] = ""
        self.MODEML = 0x00000056
        zz_edict['MODEML'] = self.MODEML
        zz_desc['MODEML'] = ""
        self.MODEMH = 0x00000057
        zz_edict['MODEMH'] = self.MODEMH
        zz_desc['MODEMH'] = ""
        self.AGC = 0x00000058
        zz_edict['AGC'] = self.AGC
        zz_desc['AGC'] = ""
        self.SYNTH = 0x0000005A
        zz_edict['SYNTH'] = self.SYNTH
        zz_desc['SYNTH'] = ""
        super(RM_Enum_PRS_CH9_CTRL_SOURCESEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH9_CTRL_EDSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.OFF = 0x00000000
        zz_edict['OFF'] = self.OFF
        zz_desc['OFF'] = ""
        self.POSEDGE = 0x00000001
        zz_edict['POSEDGE'] = self.POSEDGE
        zz_desc['POSEDGE'] = ""
        self.NEGEDGE = 0x00000002
        zz_edict['NEGEDGE'] = self.NEGEDGE
        zz_desc['NEGEDGE'] = ""
        self.BOTHEDGES = 0x00000003
        zz_edict['BOTHEDGES'] = self.BOTHEDGES
        zz_desc['BOTHEDGES'] = ""
        super(RM_Enum_PRS_CH9_CTRL_EDSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH10_CTRL_SOURCESEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.NONE = 0x00000000
        zz_edict['NONE'] = self.NONE
        zz_desc['NONE'] = ""
        self.PRSL = 0x00000001
        zz_edict['PRSL'] = self.PRSL
        zz_desc['PRSL'] = ""
        self.PRSH = 0x00000002
        zz_edict['PRSH'] = self.PRSH
        zz_desc['PRSH'] = ""
        self.ACMP0 = 0x00000003
        zz_edict['ACMP0'] = self.ACMP0
        zz_desc['ACMP0'] = ""
        self.ACMP1 = 0x00000004
        zz_edict['ACMP1'] = self.ACMP1
        zz_desc['ACMP1'] = ""
        self.ADC0 = 0x00000005
        zz_edict['ADC0'] = self.ADC0
        zz_desc['ADC0'] = ""
        self.CSEN = 0x00000006
        zz_edict['CSEN'] = self.CSEN
        zz_desc['CSEN'] = ""
        self.LESENSEL = 0x00000007
        zz_edict['LESENSEL'] = self.LESENSEL
        zz_desc['LESENSEL'] = ""
        self.LESENSEH = 0x00000008
        zz_edict['LESENSEH'] = self.LESENSEH
        zz_desc['LESENSEH'] = ""
        self.LESENSED = 0x00000009
        zz_edict['LESENSED'] = self.LESENSED
        zz_desc['LESENSED'] = ""
        self.LESENSE = 0x0000000A
        zz_edict['LESENSE'] = self.LESENSE
        zz_desc['LESENSE'] = ""
        self.RTCC = 0x0000000B
        zz_edict['RTCC'] = self.RTCC
        zz_desc['RTCC'] = ""
        self.GPIOL = 0x0000000C
        zz_edict['GPIOL'] = self.GPIOL
        zz_desc['GPIOL'] = ""
        self.GPIOH = 0x0000000D
        zz_edict['GPIOH'] = self.GPIOH
        zz_desc['GPIOH'] = ""
        self.LETIMER0 = 0x0000000E
        zz_edict['LETIMER0'] = self.LETIMER0
        zz_desc['LETIMER0'] = ""
        self.PCNT0 = 0x0000000F
        zz_edict['PCNT0'] = self.PCNT0
        zz_desc['PCNT0'] = ""
        self.PCNT1 = 0x00000010
        zz_edict['PCNT1'] = self.PCNT1
        zz_desc['PCNT1'] = ""
        self.PCNT2 = 0x00000011
        zz_edict['PCNT2'] = self.PCNT2
        zz_desc['PCNT2'] = ""
        self.CMU = 0x00000012
        zz_edict['CMU'] = self.CMU
        zz_desc['CMU'] = ""
        self.LETEST = 0x00000013
        zz_edict['LETEST'] = self.LETEST
        zz_desc['LETEST'] = ""
        self.MANTESTL = 0x00000014
        zz_edict['MANTESTL'] = self.MANTESTL
        zz_desc['MANTESTL'] = ""
        self.MANTESTH = 0x00000015
        zz_edict['MANTESTH'] = self.MANTESTH
        zz_desc['MANTESTH'] = ""
        self.EMUL = 0x00000016
        zz_edict['EMUL'] = self.EMUL
        zz_desc['EMUL'] = ""
        self.EMUH = 0x00000017
        zz_edict['EMUH'] = self.EMUH
        zz_desc['EMUH'] = ""
        self.VDAC0 = 0x00000018
        zz_edict['VDAC0'] = self.VDAC0
        zz_desc['VDAC0'] = ""
        self.RFSENSE = 0x00000019
        zz_edict['RFSENSE'] = self.RFSENSE
        zz_desc['RFSENSE'] = ""
        self.CRYOTIMER = 0x0000001A
        zz_edict['CRYOTIMER'] = self.CRYOTIMER
        zz_desc['CRYOTIMER'] = ""
        self.USART0 = 0x00000030
        zz_edict['USART0'] = self.USART0
        zz_desc['USART0'] = ""
        self.USART1 = 0x00000031
        zz_edict['USART1'] = self.USART1
        zz_desc['USART1'] = ""
        self.USART2 = 0x00000032
        zz_edict['USART2'] = self.USART2
        zz_desc['USART2'] = ""
        self.USART3 = 0x00000033
        zz_edict['USART3'] = self.USART3
        zz_desc['USART3'] = ""
        self.TIMER0 = 0x0000003C
        zz_edict['TIMER0'] = self.TIMER0
        zz_desc['TIMER0'] = ""
        self.TIMER1 = 0x0000003D
        zz_edict['TIMER1'] = self.TIMER1
        zz_desc['TIMER1'] = ""
        self.WTIMER0 = 0x0000003E
        zz_edict['WTIMER0'] = self.WTIMER0
        zz_desc['WTIMER0'] = ""
        self.WTIMER1 = 0x0000003F
        zz_edict['WTIMER1'] = self.WTIMER1
        zz_desc['WTIMER1'] = ""
        self.CM4 = 0x00000043
        zz_edict['CM4'] = self.CM4
        zz_desc['CM4'] = ""
        self.DMEM0 = 0x00000047
        zz_edict['DMEM0'] = self.DMEM0
        zz_desc['DMEM0'] = ""
        self.DMEM1 = 0x00000048
        zz_edict['DMEM1'] = self.DMEM1
        zz_desc['DMEM1'] = ""
        self.RACH = 0x00000050
        zz_edict['RACH'] = self.RACH
        zz_desc['RACH'] = ""
        self.RAC = 0x00000051
        zz_edict['RAC'] = self.RAC
        zz_desc['RAC'] = ""
        self.BUFC = 0x00000052
        zz_edict['BUFC'] = self.BUFC
        zz_desc['BUFC'] = ""
        self.PROTIMERL = 0x00000053
        zz_edict['PROTIMERL'] = self.PROTIMERL
        zz_desc['PROTIMERL'] = ""
        self.PROTIMERH = 0x00000054
        zz_edict['PROTIMERH'] = self.PROTIMERH
        zz_desc['PROTIMERH'] = ""
        self.FRC = 0x00000055
        zz_edict['FRC'] = self.FRC
        zz_desc['FRC'] = ""
        self.MODEML = 0x00000056
        zz_edict['MODEML'] = self.MODEML
        zz_desc['MODEML'] = ""
        self.MODEMH = 0x00000057
        zz_edict['MODEMH'] = self.MODEMH
        zz_desc['MODEMH'] = ""
        self.AGC = 0x00000058
        zz_edict['AGC'] = self.AGC
        zz_desc['AGC'] = ""
        self.SYNTH = 0x0000005A
        zz_edict['SYNTH'] = self.SYNTH
        zz_desc['SYNTH'] = ""
        super(RM_Enum_PRS_CH10_CTRL_SOURCESEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH10_CTRL_EDSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.OFF = 0x00000000
        zz_edict['OFF'] = self.OFF
        zz_desc['OFF'] = ""
        self.POSEDGE = 0x00000001
        zz_edict['POSEDGE'] = self.POSEDGE
        zz_desc['POSEDGE'] = ""
        self.NEGEDGE = 0x00000002
        zz_edict['NEGEDGE'] = self.NEGEDGE
        zz_desc['NEGEDGE'] = ""
        self.BOTHEDGES = 0x00000003
        zz_edict['BOTHEDGES'] = self.BOTHEDGES
        zz_desc['BOTHEDGES'] = ""
        super(RM_Enum_PRS_CH10_CTRL_EDSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH11_CTRL_SOURCESEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.NONE = 0x00000000
        zz_edict['NONE'] = self.NONE
        zz_desc['NONE'] = ""
        self.PRSL = 0x00000001
        zz_edict['PRSL'] = self.PRSL
        zz_desc['PRSL'] = ""
        self.PRSH = 0x00000002
        zz_edict['PRSH'] = self.PRSH
        zz_desc['PRSH'] = ""
        self.ACMP0 = 0x00000003
        zz_edict['ACMP0'] = self.ACMP0
        zz_desc['ACMP0'] = ""
        self.ACMP1 = 0x00000004
        zz_edict['ACMP1'] = self.ACMP1
        zz_desc['ACMP1'] = ""
        self.ADC0 = 0x00000005
        zz_edict['ADC0'] = self.ADC0
        zz_desc['ADC0'] = ""
        self.CSEN = 0x00000006
        zz_edict['CSEN'] = self.CSEN
        zz_desc['CSEN'] = ""
        self.LESENSEL = 0x00000007
        zz_edict['LESENSEL'] = self.LESENSEL
        zz_desc['LESENSEL'] = ""
        self.LESENSEH = 0x00000008
        zz_edict['LESENSEH'] = self.LESENSEH
        zz_desc['LESENSEH'] = ""
        self.LESENSED = 0x00000009
        zz_edict['LESENSED'] = self.LESENSED
        zz_desc['LESENSED'] = ""
        self.LESENSE = 0x0000000A
        zz_edict['LESENSE'] = self.LESENSE
        zz_desc['LESENSE'] = ""
        self.RTCC = 0x0000000B
        zz_edict['RTCC'] = self.RTCC
        zz_desc['RTCC'] = ""
        self.GPIOL = 0x0000000C
        zz_edict['GPIOL'] = self.GPIOL
        zz_desc['GPIOL'] = ""
        self.GPIOH = 0x0000000D
        zz_edict['GPIOH'] = self.GPIOH
        zz_desc['GPIOH'] = ""
        self.LETIMER0 = 0x0000000E
        zz_edict['LETIMER0'] = self.LETIMER0
        zz_desc['LETIMER0'] = ""
        self.PCNT0 = 0x0000000F
        zz_edict['PCNT0'] = self.PCNT0
        zz_desc['PCNT0'] = ""
        self.PCNT1 = 0x00000010
        zz_edict['PCNT1'] = self.PCNT1
        zz_desc['PCNT1'] = ""
        self.PCNT2 = 0x00000011
        zz_edict['PCNT2'] = self.PCNT2
        zz_desc['PCNT2'] = ""
        self.CMU = 0x00000012
        zz_edict['CMU'] = self.CMU
        zz_desc['CMU'] = ""
        self.LETEST = 0x00000013
        zz_edict['LETEST'] = self.LETEST
        zz_desc['LETEST'] = ""
        self.MANTESTL = 0x00000014
        zz_edict['MANTESTL'] = self.MANTESTL
        zz_desc['MANTESTL'] = ""
        self.MANTESTH = 0x00000015
        zz_edict['MANTESTH'] = self.MANTESTH
        zz_desc['MANTESTH'] = ""
        self.EMUL = 0x00000016
        zz_edict['EMUL'] = self.EMUL
        zz_desc['EMUL'] = ""
        self.EMUH = 0x00000017
        zz_edict['EMUH'] = self.EMUH
        zz_desc['EMUH'] = ""
        self.VDAC0 = 0x00000018
        zz_edict['VDAC0'] = self.VDAC0
        zz_desc['VDAC0'] = ""
        self.RFSENSE = 0x00000019
        zz_edict['RFSENSE'] = self.RFSENSE
        zz_desc['RFSENSE'] = ""
        self.CRYOTIMER = 0x0000001A
        zz_edict['CRYOTIMER'] = self.CRYOTIMER
        zz_desc['CRYOTIMER'] = ""
        self.USART0 = 0x00000030
        zz_edict['USART0'] = self.USART0
        zz_desc['USART0'] = ""
        self.USART1 = 0x00000031
        zz_edict['USART1'] = self.USART1
        zz_desc['USART1'] = ""
        self.USART2 = 0x00000032
        zz_edict['USART2'] = self.USART2
        zz_desc['USART2'] = ""
        self.USART3 = 0x00000033
        zz_edict['USART3'] = self.USART3
        zz_desc['USART3'] = ""
        self.TIMER0 = 0x0000003C
        zz_edict['TIMER0'] = self.TIMER0
        zz_desc['TIMER0'] = ""
        self.TIMER1 = 0x0000003D
        zz_edict['TIMER1'] = self.TIMER1
        zz_desc['TIMER1'] = ""
        self.WTIMER0 = 0x0000003E
        zz_edict['WTIMER0'] = self.WTIMER0
        zz_desc['WTIMER0'] = ""
        self.WTIMER1 = 0x0000003F
        zz_edict['WTIMER1'] = self.WTIMER1
        zz_desc['WTIMER1'] = ""
        self.CM4 = 0x00000043
        zz_edict['CM4'] = self.CM4
        zz_desc['CM4'] = ""
        self.DMEM0 = 0x00000047
        zz_edict['DMEM0'] = self.DMEM0
        zz_desc['DMEM0'] = ""
        self.DMEM1 = 0x00000048
        zz_edict['DMEM1'] = self.DMEM1
        zz_desc['DMEM1'] = ""
        self.RACH = 0x00000050
        zz_edict['RACH'] = self.RACH
        zz_desc['RACH'] = ""
        self.RAC = 0x00000051
        zz_edict['RAC'] = self.RAC
        zz_desc['RAC'] = ""
        self.BUFC = 0x00000052
        zz_edict['BUFC'] = self.BUFC
        zz_desc['BUFC'] = ""
        self.PROTIMERL = 0x00000053
        zz_edict['PROTIMERL'] = self.PROTIMERL
        zz_desc['PROTIMERL'] = ""
        self.PROTIMERH = 0x00000054
        zz_edict['PROTIMERH'] = self.PROTIMERH
        zz_desc['PROTIMERH'] = ""
        self.FRC = 0x00000055
        zz_edict['FRC'] = self.FRC
        zz_desc['FRC'] = ""
        self.MODEML = 0x00000056
        zz_edict['MODEML'] = self.MODEML
        zz_desc['MODEML'] = ""
        self.MODEMH = 0x00000057
        zz_edict['MODEMH'] = self.MODEMH
        zz_desc['MODEMH'] = ""
        self.AGC = 0x00000058
        zz_edict['AGC'] = self.AGC
        zz_desc['AGC'] = ""
        self.SYNTH = 0x0000005A
        zz_edict['SYNTH'] = self.SYNTH
        zz_desc['SYNTH'] = ""
        super(RM_Enum_PRS_CH11_CTRL_SOURCESEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


class RM_Enum_PRS_CH11_CTRL_EDSEL(Base_RM_Enum):
    def __init__(self, label):
        self.__dict__['zz_frozen'] = False
        zz_edict = OrderedDict()
        zz_desc = {}
        self.OFF = 0x00000000
        zz_edict['OFF'] = self.OFF
        zz_desc['OFF'] = ""
        self.POSEDGE = 0x00000001
        zz_edict['POSEDGE'] = self.POSEDGE
        zz_desc['POSEDGE'] = ""
        self.NEGEDGE = 0x00000002
        zz_edict['NEGEDGE'] = self.NEGEDGE
        zz_desc['NEGEDGE'] = ""
        self.BOTHEDGES = 0x00000003
        zz_edict['BOTHEDGES'] = self.BOTHEDGES
        zz_desc['BOTHEDGES'] = ""
        super(RM_Enum_PRS_CH11_CTRL_EDSEL, self).__init__(
            label,
            zz_edict,
            zz_desc)
        self.__dict__['zz_frozen'] = True


