
__all__ = [ 'RM_Peripheral_RTCC' ]

from static import Base_RM_Peripheral
from RTCC_register import *

class RM_Peripheral_RTCC(Base_RM_Peripheral):
    def __init__(self, rmio, label):
        self.__dict__['zz_frozen'] = False
        super(RM_Peripheral_RTCC, self).__init__(rmio, label,
            0x40042000, 'RTCC',
            "")
        self.CTRL = RM_Register_RTCC_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL'] = self.CTRL
        self.PRECNT = RM_Register_RTCC_PRECNT(self.zz_rmio, self.zz_label)
        self.zz_rdict['PRECNT'] = self.PRECNT
        self.CNT = RM_Register_RTCC_CNT(self.zz_rmio, self.zz_label)
        self.zz_rdict['CNT'] = self.CNT
        self.COMBCNT = RM_Register_RTCC_COMBCNT(self.zz_rmio, self.zz_label)
        self.zz_rdict['COMBCNT'] = self.COMBCNT
        self.TIME = RM_Register_RTCC_TIME(self.zz_rmio, self.zz_label)
        self.zz_rdict['TIME'] = self.TIME
        self.DATE = RM_Register_RTCC_DATE(self.zz_rmio, self.zz_label)
        self.zz_rdict['DATE'] = self.DATE
        self.IF = RM_Register_RTCC_IF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IF'] = self.IF
        self.IFS = RM_Register_RTCC_IFS(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFS'] = self.IFS
        self.IFC = RM_Register_RTCC_IFC(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFC'] = self.IFC
        self.IEN = RM_Register_RTCC_IEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['IEN'] = self.IEN
        self.CMD = RM_Register_RTCC_CMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['CMD'] = self.CMD
        self.SYNCBUSY = RM_Register_RTCC_SYNCBUSY(self.zz_rmio, self.zz_label)
        self.zz_rdict['SYNCBUSY'] = self.SYNCBUSY
        self.POWERDOWN = RM_Register_RTCC_POWERDOWN(self.zz_rmio, self.zz_label)
        self.zz_rdict['POWERDOWN'] = self.POWERDOWN
        self.LOCK = RM_Register_RTCC_LOCK(self.zz_rmio, self.zz_label)
        self.zz_rdict['LOCK'] = self.LOCK
        self.EM4WUEN = RM_Register_RTCC_EM4WUEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['EM4WUEN'] = self.EM4WUEN
        self.CC0_CTRL = RM_Register_RTCC_CC0_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CC0_CTRL'] = self.CC0_CTRL
        self.CC0_CCV = RM_Register_RTCC_CC0_CCV(self.zz_rmio, self.zz_label)
        self.zz_rdict['CC0_CCV'] = self.CC0_CCV
        self.CC0_TIME = RM_Register_RTCC_CC0_TIME(self.zz_rmio, self.zz_label)
        self.zz_rdict['CC0_TIME'] = self.CC0_TIME
        self.CC0_DATE = RM_Register_RTCC_CC0_DATE(self.zz_rmio, self.zz_label)
        self.zz_rdict['CC0_DATE'] = self.CC0_DATE
        self.CC1_CTRL = RM_Register_RTCC_CC1_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CC1_CTRL'] = self.CC1_CTRL
        self.CC1_CCV = RM_Register_RTCC_CC1_CCV(self.zz_rmio, self.zz_label)
        self.zz_rdict['CC1_CCV'] = self.CC1_CCV
        self.CC1_TIME = RM_Register_RTCC_CC1_TIME(self.zz_rmio, self.zz_label)
        self.zz_rdict['CC1_TIME'] = self.CC1_TIME
        self.CC1_DATE = RM_Register_RTCC_CC1_DATE(self.zz_rmio, self.zz_label)
        self.zz_rdict['CC1_DATE'] = self.CC1_DATE
        self.CC2_CTRL = RM_Register_RTCC_CC2_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CC2_CTRL'] = self.CC2_CTRL
        self.CC2_CCV = RM_Register_RTCC_CC2_CCV(self.zz_rmio, self.zz_label)
        self.zz_rdict['CC2_CCV'] = self.CC2_CCV
        self.CC2_TIME = RM_Register_RTCC_CC2_TIME(self.zz_rmio, self.zz_label)
        self.zz_rdict['CC2_TIME'] = self.CC2_TIME
        self.CC2_DATE = RM_Register_RTCC_CC2_DATE(self.zz_rmio, self.zz_label)
        self.zz_rdict['CC2_DATE'] = self.CC2_DATE
        self.RET0_REG = RM_Register_RTCC_RET0_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET0_REG'] = self.RET0_REG
        self.RET1_REG = RM_Register_RTCC_RET1_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET1_REG'] = self.RET1_REG
        self.RET2_REG = RM_Register_RTCC_RET2_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET2_REG'] = self.RET2_REG
        self.RET3_REG = RM_Register_RTCC_RET3_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET3_REG'] = self.RET3_REG
        self.RET4_REG = RM_Register_RTCC_RET4_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET4_REG'] = self.RET4_REG
        self.RET5_REG = RM_Register_RTCC_RET5_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET5_REG'] = self.RET5_REG
        self.RET6_REG = RM_Register_RTCC_RET6_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET6_REG'] = self.RET6_REG
        self.RET7_REG = RM_Register_RTCC_RET7_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET7_REG'] = self.RET7_REG
        self.RET8_REG = RM_Register_RTCC_RET8_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET8_REG'] = self.RET8_REG
        self.RET9_REG = RM_Register_RTCC_RET9_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET9_REG'] = self.RET9_REG
        self.RET10_REG = RM_Register_RTCC_RET10_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET10_REG'] = self.RET10_REG
        self.RET11_REG = RM_Register_RTCC_RET11_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET11_REG'] = self.RET11_REG
        self.RET12_REG = RM_Register_RTCC_RET12_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET12_REG'] = self.RET12_REG
        self.RET13_REG = RM_Register_RTCC_RET13_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET13_REG'] = self.RET13_REG
        self.RET14_REG = RM_Register_RTCC_RET14_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET14_REG'] = self.RET14_REG
        self.RET15_REG = RM_Register_RTCC_RET15_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET15_REG'] = self.RET15_REG
        self.RET16_REG = RM_Register_RTCC_RET16_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET16_REG'] = self.RET16_REG
        self.RET17_REG = RM_Register_RTCC_RET17_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET17_REG'] = self.RET17_REG
        self.RET18_REG = RM_Register_RTCC_RET18_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET18_REG'] = self.RET18_REG
        self.RET19_REG = RM_Register_RTCC_RET19_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET19_REG'] = self.RET19_REG
        self.RET20_REG = RM_Register_RTCC_RET20_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET20_REG'] = self.RET20_REG
        self.RET21_REG = RM_Register_RTCC_RET21_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET21_REG'] = self.RET21_REG
        self.RET22_REG = RM_Register_RTCC_RET22_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET22_REG'] = self.RET22_REG
        self.RET23_REG = RM_Register_RTCC_RET23_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET23_REG'] = self.RET23_REG
        self.RET24_REG = RM_Register_RTCC_RET24_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET24_REG'] = self.RET24_REG
        self.RET25_REG = RM_Register_RTCC_RET25_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET25_REG'] = self.RET25_REG
        self.RET26_REG = RM_Register_RTCC_RET26_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET26_REG'] = self.RET26_REG
        self.RET27_REG = RM_Register_RTCC_RET27_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET27_REG'] = self.RET27_REG
        self.RET28_REG = RM_Register_RTCC_RET28_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET28_REG'] = self.RET28_REG
        self.RET29_REG = RM_Register_RTCC_RET29_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET29_REG'] = self.RET29_REG
        self.RET30_REG = RM_Register_RTCC_RET30_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET30_REG'] = self.RET30_REG
        self.RET31_REG = RM_Register_RTCC_RET31_REG(self.zz_rmio, self.zz_label)
        self.zz_rdict['RET31_REG'] = self.RET31_REG
        self.__dict__['zz_frozen'] = True