// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

// This file contains the mapping for the command line configuration

#include PLATFORM_HEADER
#include CONFIGURATION_HEADER
#include "stack/include/ember.h"
#include EMBER_AF_API_COMMAND_INTERPRETER2

void emberResetNetworkState(void);
EmberCommandEntry emberCommandTable[] = {
  emberCommandEntryAction("leave", emberResetNetworkState, "", ""),
  emberCommandEntryTerminator(),
};
