// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

#ifdef CONFIGURATION_HEADER
  #include CONFIGURATION_HEADER
#endif

// Token header for the application.
//#include "../../../Dropbox/Project Portfolio/Sundial-Beta/Project Files/Application_headers/APPLICATION_TOKEN_HEADER.h"

#ifdef CUSTOM_TOKEN_HEADER
  #include CUSTOM_TOKEN_HEADER
#endif

