// This file is generated by Ember Desktop.  Please do not edit manually.
//
//

void emberAfInit(void);

void emberAfTick(void);

void emberAfStackStatus(EmberStatus status);

void emberAfStackIsr(void);

void emberAfIncomingMessage(EmberIncomingMessage* message);

void emberAfMessageSent(EmberStatus status, EmberOutgoingMessage* message);

void emberAfChildJoin(EmberNodeType nodeType, EmberNodeId nodeId);

void emberAfIncomingBeacon(EmberPanId panId, EmberNodeId nodeId, uint8_t payloadLength, uint8_t* payload);

void emberAfActiveScanComplete(void);

void emberAfEnergyScanComplete(int8_t mean, int8_t min, int8_t max, uint16_t variance);

void emberMarkApplicationBuffersHandler(void);
