
__all__ = [ 'RM_Peripheral_MSC' ]

from static import Base_RM_Peripheral
from MSC_register import *

class RM_Peripheral_MSC(Base_RM_Peripheral):
    def __init__(self, rmio, label):
        self.__dict__['zz_frozen'] = False
        super(RM_Peripheral_MSC, self).__init__(rmio, label,
            0x400E0000, 'MSC',
            "")
        self.CTRL = RM_Register_MSC_CTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['CTRL'] = self.CTRL
        self.READCTRL = RM_Register_MSC_READCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['READCTRL'] = self.READCTRL
        self.WRITECTRL = RM_Register_MSC_WRITECTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['WRITECTRL'] = self.WRITECTRL
        self.WRITECMD = RM_Register_MSC_WRITECMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['WRITECMD'] = self.WRITECMD
        self.ADDRB = RM_Register_MSC_ADDRB(self.zz_rmio, self.zz_label)
        self.zz_rdict['ADDRB'] = self.ADDRB
        self.WDATA = RM_Register_MSC_WDATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['WDATA'] = self.WDATA
        self.STATUS = RM_Register_MSC_STATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['STATUS'] = self.STATUS
        self.MEMFEATURE = RM_Register_MSC_MEMFEATURE(self.zz_rmio, self.zz_label)
        self.zz_rdict['MEMFEATURE'] = self.MEMFEATURE
        self.CFGFEATURE = RM_Register_MSC_CFGFEATURE(self.zz_rmio, self.zz_label)
        self.zz_rdict['CFGFEATURE'] = self.CFGFEATURE
        self.DEBUGLOCK = RM_Register_MSC_DEBUGLOCK(self.zz_rmio, self.zz_label)
        self.zz_rdict['DEBUGLOCK'] = self.DEBUGLOCK
        self.AAPLOCK = RM_Register_MSC_AAPLOCK(self.zz_rmio, self.zz_label)
        self.zz_rdict['AAPLOCK'] = self.AAPLOCK
        self.IF = RM_Register_MSC_IF(self.zz_rmio, self.zz_label)
        self.zz_rdict['IF'] = self.IF
        self.IFS = RM_Register_MSC_IFS(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFS'] = self.IFS
        self.IFC = RM_Register_MSC_IFC(self.zz_rmio, self.zz_label)
        self.zz_rdict['IFC'] = self.IFC
        self.IEN = RM_Register_MSC_IEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['IEN'] = self.IEN
        self.LOCK = RM_Register_MSC_LOCK(self.zz_rmio, self.zz_label)
        self.zz_rdict['LOCK'] = self.LOCK
        self.CACHECMD = RM_Register_MSC_CACHECMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHECMD'] = self.CACHECMD
        self.CACHEHITS = RM_Register_MSC_CACHEHITS(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHEHITS'] = self.CACHEHITS
        self.CACHEMISSES = RM_Register_MSC_CACHEMISSES(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHEMISSES'] = self.CACHEMISSES
        self.MASSLOCK = RM_Register_MSC_MASSLOCK(self.zz_rmio, self.zz_label)
        self.zz_rdict['MASSLOCK'] = self.MASSLOCK
        self.STARTUP = RM_Register_MSC_STARTUP(self.zz_rmio, self.zz_label)
        self.zz_rdict['STARTUP'] = self.STARTUP
        self.LVEN = RM_Register_MSC_LVEN(self.zz_rmio, self.zz_label)
        self.zz_rdict['LVEN'] = self.LVEN
        self.UCFGLOCK0 = RM_Register_MSC_UCFGLOCK0(self.zz_rmio, self.zz_label)
        self.zz_rdict['UCFGLOCK0'] = self.UCFGLOCK0
        self.CMD = RM_Register_MSC_CMD(self.zz_rmio, self.zz_label)
        self.zz_rdict['CMD'] = self.CMD
        self.DSRINPORT = RM_Register_MSC_DSRINPORT(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSRINPORT'] = self.DSRINPORT
        self.DSROUTPORT = RM_Register_MSC_DSROUTPORT(self.zz_rmio, self.zz_label)
        self.zz_rdict['DSROUTPORT'] = self.DSROUTPORT
        self.CHIPREVHW = RM_Register_MSC_CHIPREVHW(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHIPREVHW'] = self.CHIPREVHW
        self.CHIPREV = RM_Register_MSC_CHIPREV(self.zz_rmio, self.zz_label)
        self.zz_rdict['CHIPREV'] = self.CHIPREV
        self.TESTCTRL = RM_Register_MSC_TESTCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['TESTCTRL'] = self.TESTCTRL
        self.PATDIAGCTRL = RM_Register_MSC_PATDIAGCTRL(self.zz_rmio, self.zz_label)
        self.zz_rdict['PATDIAGCTRL'] = self.PATDIAGCTRL
        self.PATADDR = RM_Register_MSC_PATADDR(self.zz_rmio, self.zz_label)
        self.zz_rdict['PATADDR'] = self.PATADDR
        self.PATDONEADDR = RM_Register_MSC_PATDONEADDR(self.zz_rmio, self.zz_label)
        self.zz_rdict['PATDONEADDR'] = self.PATDONEADDR
        self.PATSTATUS = RM_Register_MSC_PATSTATUS(self.zz_rmio, self.zz_label)
        self.zz_rdict['PATSTATUS'] = self.PATSTATUS
        self.TESTTC0 = RM_Register_MSC_TESTTC0(self.zz_rmio, self.zz_label)
        self.zz_rdict['TESTTC0'] = self.TESTTC0
        self.DOUT0 = RM_Register_MSC_DOUT0(self.zz_rmio, self.zz_label)
        self.zz_rdict['DOUT0'] = self.DOUT0
        self.DOUT1 = RM_Register_MSC_DOUT1(self.zz_rmio, self.zz_label)
        self.zz_rdict['DOUT1'] = self.DOUT1
        self.REPADDR0 = RM_Register_MSC_REPADDR0(self.zz_rmio, self.zz_label)
        self.zz_rdict['REPADDR0'] = self.REPADDR0
        self.REPADDR1 = RM_Register_MSC_REPADDR1(self.zz_rmio, self.zz_label)
        self.zz_rdict['REPADDR1'] = self.REPADDR1
        self.REPADDR2 = RM_Register_MSC_REPADDR2(self.zz_rmio, self.zz_label)
        self.zz_rdict['REPADDR2'] = self.REPADDR2
        self.REPADDR3 = RM_Register_MSC_REPADDR3(self.zz_rmio, self.zz_label)
        self.zz_rdict['REPADDR3'] = self.REPADDR3
        self.REPADDR4 = RM_Register_MSC_REPADDR4(self.zz_rmio, self.zz_label)
        self.zz_rdict['REPADDR4'] = self.REPADDR4
        self.REPADDR5 = RM_Register_MSC_REPADDR5(self.zz_rmio, self.zz_label)
        self.zz_rdict['REPADDR5'] = self.REPADDR5
        self.REPADDR6 = RM_Register_MSC_REPADDR6(self.zz_rmio, self.zz_label)
        self.zz_rdict['REPADDR6'] = self.REPADDR6
        self.REPADDR7 = RM_Register_MSC_REPADDR7(self.zz_rmio, self.zz_label)
        self.zz_rdict['REPADDR7'] = self.REPADDR7
        self.CACHE0_DATA = RM_Register_MSC_CACHE0_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE0_DATA'] = self.CACHE0_DATA
        self.CACHE1_DATA = RM_Register_MSC_CACHE1_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE1_DATA'] = self.CACHE1_DATA
        self.CACHE2_DATA = RM_Register_MSC_CACHE2_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE2_DATA'] = self.CACHE2_DATA
        self.CACHE3_DATA = RM_Register_MSC_CACHE3_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE3_DATA'] = self.CACHE3_DATA
        self.CACHE4_DATA = RM_Register_MSC_CACHE4_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE4_DATA'] = self.CACHE4_DATA
        self.CACHE5_DATA = RM_Register_MSC_CACHE5_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE5_DATA'] = self.CACHE5_DATA
        self.CACHE6_DATA = RM_Register_MSC_CACHE6_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE6_DATA'] = self.CACHE6_DATA
        self.CACHE7_DATA = RM_Register_MSC_CACHE7_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE7_DATA'] = self.CACHE7_DATA
        self.CACHE8_DATA = RM_Register_MSC_CACHE8_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE8_DATA'] = self.CACHE8_DATA
        self.CACHE9_DATA = RM_Register_MSC_CACHE9_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE9_DATA'] = self.CACHE9_DATA
        self.CACHE10_DATA = RM_Register_MSC_CACHE10_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE10_DATA'] = self.CACHE10_DATA
        self.CACHE11_DATA = RM_Register_MSC_CACHE11_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE11_DATA'] = self.CACHE11_DATA
        self.CACHE12_DATA = RM_Register_MSC_CACHE12_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE12_DATA'] = self.CACHE12_DATA
        self.CACHE13_DATA = RM_Register_MSC_CACHE13_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE13_DATA'] = self.CACHE13_DATA
        self.CACHE14_DATA = RM_Register_MSC_CACHE14_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE14_DATA'] = self.CACHE14_DATA
        self.CACHE15_DATA = RM_Register_MSC_CACHE15_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE15_DATA'] = self.CACHE15_DATA
        self.CACHE16_DATA = RM_Register_MSC_CACHE16_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE16_DATA'] = self.CACHE16_DATA
        self.CACHE17_DATA = RM_Register_MSC_CACHE17_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE17_DATA'] = self.CACHE17_DATA
        self.CACHE18_DATA = RM_Register_MSC_CACHE18_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE18_DATA'] = self.CACHE18_DATA
        self.CACHE19_DATA = RM_Register_MSC_CACHE19_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE19_DATA'] = self.CACHE19_DATA
        self.CACHE20_DATA = RM_Register_MSC_CACHE20_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE20_DATA'] = self.CACHE20_DATA
        self.CACHE21_DATA = RM_Register_MSC_CACHE21_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE21_DATA'] = self.CACHE21_DATA
        self.CACHE22_DATA = RM_Register_MSC_CACHE22_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE22_DATA'] = self.CACHE22_DATA
        self.CACHE23_DATA = RM_Register_MSC_CACHE23_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE23_DATA'] = self.CACHE23_DATA
        self.CACHE24_DATA = RM_Register_MSC_CACHE24_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE24_DATA'] = self.CACHE24_DATA
        self.CACHE25_DATA = RM_Register_MSC_CACHE25_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE25_DATA'] = self.CACHE25_DATA
        self.CACHE26_DATA = RM_Register_MSC_CACHE26_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE26_DATA'] = self.CACHE26_DATA
        self.CACHE27_DATA = RM_Register_MSC_CACHE27_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE27_DATA'] = self.CACHE27_DATA
        self.CACHE28_DATA = RM_Register_MSC_CACHE28_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE28_DATA'] = self.CACHE28_DATA
        self.CACHE29_DATA = RM_Register_MSC_CACHE29_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE29_DATA'] = self.CACHE29_DATA
        self.CACHE30_DATA = RM_Register_MSC_CACHE30_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE30_DATA'] = self.CACHE30_DATA
        self.CACHE31_DATA = RM_Register_MSC_CACHE31_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE31_DATA'] = self.CACHE31_DATA
        self.CACHE32_DATA = RM_Register_MSC_CACHE32_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE32_DATA'] = self.CACHE32_DATA
        self.CACHE33_DATA = RM_Register_MSC_CACHE33_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE33_DATA'] = self.CACHE33_DATA
        self.CACHE34_DATA = RM_Register_MSC_CACHE34_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE34_DATA'] = self.CACHE34_DATA
        self.CACHE35_DATA = RM_Register_MSC_CACHE35_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE35_DATA'] = self.CACHE35_DATA
        self.CACHE36_DATA = RM_Register_MSC_CACHE36_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE36_DATA'] = self.CACHE36_DATA
        self.CACHE37_DATA = RM_Register_MSC_CACHE37_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE37_DATA'] = self.CACHE37_DATA
        self.CACHE38_DATA = RM_Register_MSC_CACHE38_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE38_DATA'] = self.CACHE38_DATA
        self.CACHE39_DATA = RM_Register_MSC_CACHE39_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE39_DATA'] = self.CACHE39_DATA
        self.CACHE40_DATA = RM_Register_MSC_CACHE40_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE40_DATA'] = self.CACHE40_DATA
        self.CACHE41_DATA = RM_Register_MSC_CACHE41_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE41_DATA'] = self.CACHE41_DATA
        self.CACHE42_DATA = RM_Register_MSC_CACHE42_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE42_DATA'] = self.CACHE42_DATA
        self.CACHE43_DATA = RM_Register_MSC_CACHE43_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE43_DATA'] = self.CACHE43_DATA
        self.CACHE44_DATA = RM_Register_MSC_CACHE44_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE44_DATA'] = self.CACHE44_DATA
        self.CACHE45_DATA = RM_Register_MSC_CACHE45_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE45_DATA'] = self.CACHE45_DATA
        self.CACHE46_DATA = RM_Register_MSC_CACHE46_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE46_DATA'] = self.CACHE46_DATA
        self.CACHE47_DATA = RM_Register_MSC_CACHE47_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE47_DATA'] = self.CACHE47_DATA
        self.CACHE48_DATA = RM_Register_MSC_CACHE48_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE48_DATA'] = self.CACHE48_DATA
        self.CACHE49_DATA = RM_Register_MSC_CACHE49_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE49_DATA'] = self.CACHE49_DATA
        self.CACHE50_DATA = RM_Register_MSC_CACHE50_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE50_DATA'] = self.CACHE50_DATA
        self.CACHE51_DATA = RM_Register_MSC_CACHE51_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE51_DATA'] = self.CACHE51_DATA
        self.CACHE52_DATA = RM_Register_MSC_CACHE52_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE52_DATA'] = self.CACHE52_DATA
        self.CACHE53_DATA = RM_Register_MSC_CACHE53_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE53_DATA'] = self.CACHE53_DATA
        self.CACHE54_DATA = RM_Register_MSC_CACHE54_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE54_DATA'] = self.CACHE54_DATA
        self.CACHE55_DATA = RM_Register_MSC_CACHE55_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE55_DATA'] = self.CACHE55_DATA
        self.CACHE56_DATA = RM_Register_MSC_CACHE56_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE56_DATA'] = self.CACHE56_DATA
        self.CACHE57_DATA = RM_Register_MSC_CACHE57_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE57_DATA'] = self.CACHE57_DATA
        self.CACHE58_DATA = RM_Register_MSC_CACHE58_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE58_DATA'] = self.CACHE58_DATA
        self.CACHE59_DATA = RM_Register_MSC_CACHE59_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE59_DATA'] = self.CACHE59_DATA
        self.CACHE60_DATA = RM_Register_MSC_CACHE60_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE60_DATA'] = self.CACHE60_DATA
        self.CACHE61_DATA = RM_Register_MSC_CACHE61_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE61_DATA'] = self.CACHE61_DATA
        self.CACHE62_DATA = RM_Register_MSC_CACHE62_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE62_DATA'] = self.CACHE62_DATA
        self.CACHE63_DATA = RM_Register_MSC_CACHE63_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE63_DATA'] = self.CACHE63_DATA
        self.CACHE64_DATA = RM_Register_MSC_CACHE64_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE64_DATA'] = self.CACHE64_DATA
        self.CACHE65_DATA = RM_Register_MSC_CACHE65_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE65_DATA'] = self.CACHE65_DATA
        self.CACHE66_DATA = RM_Register_MSC_CACHE66_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE66_DATA'] = self.CACHE66_DATA
        self.CACHE67_DATA = RM_Register_MSC_CACHE67_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE67_DATA'] = self.CACHE67_DATA
        self.CACHE68_DATA = RM_Register_MSC_CACHE68_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE68_DATA'] = self.CACHE68_DATA
        self.CACHE69_DATA = RM_Register_MSC_CACHE69_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE69_DATA'] = self.CACHE69_DATA
        self.CACHE70_DATA = RM_Register_MSC_CACHE70_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE70_DATA'] = self.CACHE70_DATA
        self.CACHE71_DATA = RM_Register_MSC_CACHE71_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE71_DATA'] = self.CACHE71_DATA
        self.CACHE72_DATA = RM_Register_MSC_CACHE72_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE72_DATA'] = self.CACHE72_DATA
        self.CACHE73_DATA = RM_Register_MSC_CACHE73_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE73_DATA'] = self.CACHE73_DATA
        self.CACHE74_DATA = RM_Register_MSC_CACHE74_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE74_DATA'] = self.CACHE74_DATA
        self.CACHE75_DATA = RM_Register_MSC_CACHE75_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE75_DATA'] = self.CACHE75_DATA
        self.CACHE76_DATA = RM_Register_MSC_CACHE76_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE76_DATA'] = self.CACHE76_DATA
        self.CACHE77_DATA = RM_Register_MSC_CACHE77_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE77_DATA'] = self.CACHE77_DATA
        self.CACHE78_DATA = RM_Register_MSC_CACHE78_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE78_DATA'] = self.CACHE78_DATA
        self.CACHE79_DATA = RM_Register_MSC_CACHE79_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE79_DATA'] = self.CACHE79_DATA
        self.CACHE80_DATA = RM_Register_MSC_CACHE80_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE80_DATA'] = self.CACHE80_DATA
        self.CACHE81_DATA = RM_Register_MSC_CACHE81_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE81_DATA'] = self.CACHE81_DATA
        self.CACHE82_DATA = RM_Register_MSC_CACHE82_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE82_DATA'] = self.CACHE82_DATA
        self.CACHE83_DATA = RM_Register_MSC_CACHE83_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE83_DATA'] = self.CACHE83_DATA
        self.CACHE84_DATA = RM_Register_MSC_CACHE84_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE84_DATA'] = self.CACHE84_DATA
        self.CACHE85_DATA = RM_Register_MSC_CACHE85_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE85_DATA'] = self.CACHE85_DATA
        self.CACHE86_DATA = RM_Register_MSC_CACHE86_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE86_DATA'] = self.CACHE86_DATA
        self.CACHE87_DATA = RM_Register_MSC_CACHE87_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE87_DATA'] = self.CACHE87_DATA
        self.CACHE88_DATA = RM_Register_MSC_CACHE88_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE88_DATA'] = self.CACHE88_DATA
        self.CACHE89_DATA = RM_Register_MSC_CACHE89_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE89_DATA'] = self.CACHE89_DATA
        self.CACHE90_DATA = RM_Register_MSC_CACHE90_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE90_DATA'] = self.CACHE90_DATA
        self.CACHE91_DATA = RM_Register_MSC_CACHE91_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE91_DATA'] = self.CACHE91_DATA
        self.CACHE92_DATA = RM_Register_MSC_CACHE92_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE92_DATA'] = self.CACHE92_DATA
        self.CACHE93_DATA = RM_Register_MSC_CACHE93_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE93_DATA'] = self.CACHE93_DATA
        self.CACHE94_DATA = RM_Register_MSC_CACHE94_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE94_DATA'] = self.CACHE94_DATA
        self.CACHE95_DATA = RM_Register_MSC_CACHE95_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE95_DATA'] = self.CACHE95_DATA
        self.CACHE96_DATA = RM_Register_MSC_CACHE96_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE96_DATA'] = self.CACHE96_DATA
        self.CACHE97_DATA = RM_Register_MSC_CACHE97_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE97_DATA'] = self.CACHE97_DATA
        self.CACHE98_DATA = RM_Register_MSC_CACHE98_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE98_DATA'] = self.CACHE98_DATA
        self.CACHE99_DATA = RM_Register_MSC_CACHE99_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE99_DATA'] = self.CACHE99_DATA
        self.CACHE100_DATA = RM_Register_MSC_CACHE100_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE100_DATA'] = self.CACHE100_DATA
        self.CACHE101_DATA = RM_Register_MSC_CACHE101_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE101_DATA'] = self.CACHE101_DATA
        self.CACHE102_DATA = RM_Register_MSC_CACHE102_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE102_DATA'] = self.CACHE102_DATA
        self.CACHE103_DATA = RM_Register_MSC_CACHE103_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE103_DATA'] = self.CACHE103_DATA
        self.CACHE104_DATA = RM_Register_MSC_CACHE104_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE104_DATA'] = self.CACHE104_DATA
        self.CACHE105_DATA = RM_Register_MSC_CACHE105_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE105_DATA'] = self.CACHE105_DATA
        self.CACHE106_DATA = RM_Register_MSC_CACHE106_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE106_DATA'] = self.CACHE106_DATA
        self.CACHE107_DATA = RM_Register_MSC_CACHE107_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE107_DATA'] = self.CACHE107_DATA
        self.CACHE108_DATA = RM_Register_MSC_CACHE108_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE108_DATA'] = self.CACHE108_DATA
        self.CACHE109_DATA = RM_Register_MSC_CACHE109_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE109_DATA'] = self.CACHE109_DATA
        self.CACHE110_DATA = RM_Register_MSC_CACHE110_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE110_DATA'] = self.CACHE110_DATA
        self.CACHE111_DATA = RM_Register_MSC_CACHE111_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE111_DATA'] = self.CACHE111_DATA
        self.CACHE112_DATA = RM_Register_MSC_CACHE112_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE112_DATA'] = self.CACHE112_DATA
        self.CACHE113_DATA = RM_Register_MSC_CACHE113_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE113_DATA'] = self.CACHE113_DATA
        self.CACHE114_DATA = RM_Register_MSC_CACHE114_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE114_DATA'] = self.CACHE114_DATA
        self.CACHE115_DATA = RM_Register_MSC_CACHE115_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE115_DATA'] = self.CACHE115_DATA
        self.CACHE116_DATA = RM_Register_MSC_CACHE116_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE116_DATA'] = self.CACHE116_DATA
        self.CACHE117_DATA = RM_Register_MSC_CACHE117_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE117_DATA'] = self.CACHE117_DATA
        self.CACHE118_DATA = RM_Register_MSC_CACHE118_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE118_DATA'] = self.CACHE118_DATA
        self.CACHE119_DATA = RM_Register_MSC_CACHE119_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE119_DATA'] = self.CACHE119_DATA
        self.CACHE120_DATA = RM_Register_MSC_CACHE120_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE120_DATA'] = self.CACHE120_DATA
        self.CACHE121_DATA = RM_Register_MSC_CACHE121_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE121_DATA'] = self.CACHE121_DATA
        self.CACHE122_DATA = RM_Register_MSC_CACHE122_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE122_DATA'] = self.CACHE122_DATA
        self.CACHE123_DATA = RM_Register_MSC_CACHE123_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE123_DATA'] = self.CACHE123_DATA
        self.CACHE124_DATA = RM_Register_MSC_CACHE124_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE124_DATA'] = self.CACHE124_DATA
        self.CACHE125_DATA = RM_Register_MSC_CACHE125_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE125_DATA'] = self.CACHE125_DATA
        self.CACHE126_DATA = RM_Register_MSC_CACHE126_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE126_DATA'] = self.CACHE126_DATA
        self.CACHE127_DATA = RM_Register_MSC_CACHE127_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE127_DATA'] = self.CACHE127_DATA
        self.CACHE128_DATA = RM_Register_MSC_CACHE128_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE128_DATA'] = self.CACHE128_DATA
        self.CACHE129_DATA = RM_Register_MSC_CACHE129_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE129_DATA'] = self.CACHE129_DATA
        self.CACHE130_DATA = RM_Register_MSC_CACHE130_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE130_DATA'] = self.CACHE130_DATA
        self.CACHE131_DATA = RM_Register_MSC_CACHE131_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE131_DATA'] = self.CACHE131_DATA
        self.CACHE132_DATA = RM_Register_MSC_CACHE132_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE132_DATA'] = self.CACHE132_DATA
        self.CACHE133_DATA = RM_Register_MSC_CACHE133_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE133_DATA'] = self.CACHE133_DATA
        self.CACHE134_DATA = RM_Register_MSC_CACHE134_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE134_DATA'] = self.CACHE134_DATA
        self.CACHE135_DATA = RM_Register_MSC_CACHE135_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE135_DATA'] = self.CACHE135_DATA
        self.CACHE136_DATA = RM_Register_MSC_CACHE136_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE136_DATA'] = self.CACHE136_DATA
        self.CACHE137_DATA = RM_Register_MSC_CACHE137_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE137_DATA'] = self.CACHE137_DATA
        self.CACHE138_DATA = RM_Register_MSC_CACHE138_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE138_DATA'] = self.CACHE138_DATA
        self.CACHE139_DATA = RM_Register_MSC_CACHE139_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE139_DATA'] = self.CACHE139_DATA
        self.CACHE140_DATA = RM_Register_MSC_CACHE140_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE140_DATA'] = self.CACHE140_DATA
        self.CACHE141_DATA = RM_Register_MSC_CACHE141_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE141_DATA'] = self.CACHE141_DATA
        self.CACHE142_DATA = RM_Register_MSC_CACHE142_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE142_DATA'] = self.CACHE142_DATA
        self.CACHE143_DATA = RM_Register_MSC_CACHE143_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE143_DATA'] = self.CACHE143_DATA
        self.CACHE144_DATA = RM_Register_MSC_CACHE144_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE144_DATA'] = self.CACHE144_DATA
        self.CACHE145_DATA = RM_Register_MSC_CACHE145_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE145_DATA'] = self.CACHE145_DATA
        self.CACHE146_DATA = RM_Register_MSC_CACHE146_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE146_DATA'] = self.CACHE146_DATA
        self.CACHE147_DATA = RM_Register_MSC_CACHE147_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE147_DATA'] = self.CACHE147_DATA
        self.CACHE148_DATA = RM_Register_MSC_CACHE148_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE148_DATA'] = self.CACHE148_DATA
        self.CACHE149_DATA = RM_Register_MSC_CACHE149_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE149_DATA'] = self.CACHE149_DATA
        self.CACHE150_DATA = RM_Register_MSC_CACHE150_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE150_DATA'] = self.CACHE150_DATA
        self.CACHE151_DATA = RM_Register_MSC_CACHE151_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE151_DATA'] = self.CACHE151_DATA
        self.CACHE152_DATA = RM_Register_MSC_CACHE152_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE152_DATA'] = self.CACHE152_DATA
        self.CACHE153_DATA = RM_Register_MSC_CACHE153_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE153_DATA'] = self.CACHE153_DATA
        self.CACHE154_DATA = RM_Register_MSC_CACHE154_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE154_DATA'] = self.CACHE154_DATA
        self.CACHE155_DATA = RM_Register_MSC_CACHE155_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE155_DATA'] = self.CACHE155_DATA
        self.CACHE156_DATA = RM_Register_MSC_CACHE156_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE156_DATA'] = self.CACHE156_DATA
        self.CACHE157_DATA = RM_Register_MSC_CACHE157_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE157_DATA'] = self.CACHE157_DATA
        self.CACHE158_DATA = RM_Register_MSC_CACHE158_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE158_DATA'] = self.CACHE158_DATA
        self.CACHE159_DATA = RM_Register_MSC_CACHE159_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE159_DATA'] = self.CACHE159_DATA
        self.CACHE160_DATA = RM_Register_MSC_CACHE160_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE160_DATA'] = self.CACHE160_DATA
        self.CACHE161_DATA = RM_Register_MSC_CACHE161_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE161_DATA'] = self.CACHE161_DATA
        self.CACHE162_DATA = RM_Register_MSC_CACHE162_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE162_DATA'] = self.CACHE162_DATA
        self.CACHE163_DATA = RM_Register_MSC_CACHE163_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE163_DATA'] = self.CACHE163_DATA
        self.CACHE164_DATA = RM_Register_MSC_CACHE164_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE164_DATA'] = self.CACHE164_DATA
        self.CACHE165_DATA = RM_Register_MSC_CACHE165_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE165_DATA'] = self.CACHE165_DATA
        self.CACHE166_DATA = RM_Register_MSC_CACHE166_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE166_DATA'] = self.CACHE166_DATA
        self.CACHE167_DATA = RM_Register_MSC_CACHE167_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE167_DATA'] = self.CACHE167_DATA
        self.CACHE168_DATA = RM_Register_MSC_CACHE168_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE168_DATA'] = self.CACHE168_DATA
        self.CACHE169_DATA = RM_Register_MSC_CACHE169_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE169_DATA'] = self.CACHE169_DATA
        self.CACHE170_DATA = RM_Register_MSC_CACHE170_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE170_DATA'] = self.CACHE170_DATA
        self.CACHE171_DATA = RM_Register_MSC_CACHE171_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE171_DATA'] = self.CACHE171_DATA
        self.CACHE172_DATA = RM_Register_MSC_CACHE172_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE172_DATA'] = self.CACHE172_DATA
        self.CACHE173_DATA = RM_Register_MSC_CACHE173_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE173_DATA'] = self.CACHE173_DATA
        self.CACHE174_DATA = RM_Register_MSC_CACHE174_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE174_DATA'] = self.CACHE174_DATA
        self.CACHE175_DATA = RM_Register_MSC_CACHE175_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE175_DATA'] = self.CACHE175_DATA
        self.CACHE176_DATA = RM_Register_MSC_CACHE176_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE176_DATA'] = self.CACHE176_DATA
        self.CACHE177_DATA = RM_Register_MSC_CACHE177_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE177_DATA'] = self.CACHE177_DATA
        self.CACHE178_DATA = RM_Register_MSC_CACHE178_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE178_DATA'] = self.CACHE178_DATA
        self.CACHE179_DATA = RM_Register_MSC_CACHE179_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE179_DATA'] = self.CACHE179_DATA
        self.CACHE180_DATA = RM_Register_MSC_CACHE180_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE180_DATA'] = self.CACHE180_DATA
        self.CACHE181_DATA = RM_Register_MSC_CACHE181_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE181_DATA'] = self.CACHE181_DATA
        self.CACHE182_DATA = RM_Register_MSC_CACHE182_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE182_DATA'] = self.CACHE182_DATA
        self.CACHE183_DATA = RM_Register_MSC_CACHE183_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE183_DATA'] = self.CACHE183_DATA
        self.CACHE184_DATA = RM_Register_MSC_CACHE184_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE184_DATA'] = self.CACHE184_DATA
        self.CACHE185_DATA = RM_Register_MSC_CACHE185_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE185_DATA'] = self.CACHE185_DATA
        self.CACHE186_DATA = RM_Register_MSC_CACHE186_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE186_DATA'] = self.CACHE186_DATA
        self.CACHE187_DATA = RM_Register_MSC_CACHE187_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE187_DATA'] = self.CACHE187_DATA
        self.CACHE188_DATA = RM_Register_MSC_CACHE188_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE188_DATA'] = self.CACHE188_DATA
        self.CACHE189_DATA = RM_Register_MSC_CACHE189_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE189_DATA'] = self.CACHE189_DATA
        self.CACHE190_DATA = RM_Register_MSC_CACHE190_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE190_DATA'] = self.CACHE190_DATA
        self.CACHE191_DATA = RM_Register_MSC_CACHE191_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE191_DATA'] = self.CACHE191_DATA
        self.CACHE192_DATA = RM_Register_MSC_CACHE192_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE192_DATA'] = self.CACHE192_DATA
        self.CACHE193_DATA = RM_Register_MSC_CACHE193_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE193_DATA'] = self.CACHE193_DATA
        self.CACHE194_DATA = RM_Register_MSC_CACHE194_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE194_DATA'] = self.CACHE194_DATA
        self.CACHE195_DATA = RM_Register_MSC_CACHE195_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE195_DATA'] = self.CACHE195_DATA
        self.CACHE196_DATA = RM_Register_MSC_CACHE196_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE196_DATA'] = self.CACHE196_DATA
        self.CACHE197_DATA = RM_Register_MSC_CACHE197_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE197_DATA'] = self.CACHE197_DATA
        self.CACHE198_DATA = RM_Register_MSC_CACHE198_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE198_DATA'] = self.CACHE198_DATA
        self.CACHE199_DATA = RM_Register_MSC_CACHE199_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE199_DATA'] = self.CACHE199_DATA
        self.CACHE200_DATA = RM_Register_MSC_CACHE200_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE200_DATA'] = self.CACHE200_DATA
        self.CACHE201_DATA = RM_Register_MSC_CACHE201_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE201_DATA'] = self.CACHE201_DATA
        self.CACHE202_DATA = RM_Register_MSC_CACHE202_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE202_DATA'] = self.CACHE202_DATA
        self.CACHE203_DATA = RM_Register_MSC_CACHE203_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE203_DATA'] = self.CACHE203_DATA
        self.CACHE204_DATA = RM_Register_MSC_CACHE204_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE204_DATA'] = self.CACHE204_DATA
        self.CACHE205_DATA = RM_Register_MSC_CACHE205_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE205_DATA'] = self.CACHE205_DATA
        self.CACHE206_DATA = RM_Register_MSC_CACHE206_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE206_DATA'] = self.CACHE206_DATA
        self.CACHE207_DATA = RM_Register_MSC_CACHE207_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE207_DATA'] = self.CACHE207_DATA
        self.CACHE208_DATA = RM_Register_MSC_CACHE208_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE208_DATA'] = self.CACHE208_DATA
        self.CACHE209_DATA = RM_Register_MSC_CACHE209_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE209_DATA'] = self.CACHE209_DATA
        self.CACHE210_DATA = RM_Register_MSC_CACHE210_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE210_DATA'] = self.CACHE210_DATA
        self.CACHE211_DATA = RM_Register_MSC_CACHE211_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE211_DATA'] = self.CACHE211_DATA
        self.CACHE212_DATA = RM_Register_MSC_CACHE212_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE212_DATA'] = self.CACHE212_DATA
        self.CACHE213_DATA = RM_Register_MSC_CACHE213_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE213_DATA'] = self.CACHE213_DATA
        self.CACHE214_DATA = RM_Register_MSC_CACHE214_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE214_DATA'] = self.CACHE214_DATA
        self.CACHE215_DATA = RM_Register_MSC_CACHE215_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE215_DATA'] = self.CACHE215_DATA
        self.CACHE216_DATA = RM_Register_MSC_CACHE216_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE216_DATA'] = self.CACHE216_DATA
        self.CACHE217_DATA = RM_Register_MSC_CACHE217_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE217_DATA'] = self.CACHE217_DATA
        self.CACHE218_DATA = RM_Register_MSC_CACHE218_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE218_DATA'] = self.CACHE218_DATA
        self.CACHE219_DATA = RM_Register_MSC_CACHE219_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE219_DATA'] = self.CACHE219_DATA
        self.CACHE220_DATA = RM_Register_MSC_CACHE220_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE220_DATA'] = self.CACHE220_DATA
        self.CACHE221_DATA = RM_Register_MSC_CACHE221_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE221_DATA'] = self.CACHE221_DATA
        self.CACHE222_DATA = RM_Register_MSC_CACHE222_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE222_DATA'] = self.CACHE222_DATA
        self.CACHE223_DATA = RM_Register_MSC_CACHE223_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE223_DATA'] = self.CACHE223_DATA
        self.CACHE224_DATA = RM_Register_MSC_CACHE224_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE224_DATA'] = self.CACHE224_DATA
        self.CACHE225_DATA = RM_Register_MSC_CACHE225_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE225_DATA'] = self.CACHE225_DATA
        self.CACHE226_DATA = RM_Register_MSC_CACHE226_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE226_DATA'] = self.CACHE226_DATA
        self.CACHE227_DATA = RM_Register_MSC_CACHE227_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE227_DATA'] = self.CACHE227_DATA
        self.CACHE228_DATA = RM_Register_MSC_CACHE228_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE228_DATA'] = self.CACHE228_DATA
        self.CACHE229_DATA = RM_Register_MSC_CACHE229_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE229_DATA'] = self.CACHE229_DATA
        self.CACHE230_DATA = RM_Register_MSC_CACHE230_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE230_DATA'] = self.CACHE230_DATA
        self.CACHE231_DATA = RM_Register_MSC_CACHE231_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE231_DATA'] = self.CACHE231_DATA
        self.CACHE232_DATA = RM_Register_MSC_CACHE232_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE232_DATA'] = self.CACHE232_DATA
        self.CACHE233_DATA = RM_Register_MSC_CACHE233_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE233_DATA'] = self.CACHE233_DATA
        self.CACHE234_DATA = RM_Register_MSC_CACHE234_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE234_DATA'] = self.CACHE234_DATA
        self.CACHE235_DATA = RM_Register_MSC_CACHE235_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE235_DATA'] = self.CACHE235_DATA
        self.CACHE236_DATA = RM_Register_MSC_CACHE236_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE236_DATA'] = self.CACHE236_DATA
        self.CACHE237_DATA = RM_Register_MSC_CACHE237_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE237_DATA'] = self.CACHE237_DATA
        self.CACHE238_DATA = RM_Register_MSC_CACHE238_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE238_DATA'] = self.CACHE238_DATA
        self.CACHE239_DATA = RM_Register_MSC_CACHE239_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE239_DATA'] = self.CACHE239_DATA
        self.CACHE240_DATA = RM_Register_MSC_CACHE240_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE240_DATA'] = self.CACHE240_DATA
        self.CACHE241_DATA = RM_Register_MSC_CACHE241_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE241_DATA'] = self.CACHE241_DATA
        self.CACHE242_DATA = RM_Register_MSC_CACHE242_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE242_DATA'] = self.CACHE242_DATA
        self.CACHE243_DATA = RM_Register_MSC_CACHE243_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE243_DATA'] = self.CACHE243_DATA
        self.CACHE244_DATA = RM_Register_MSC_CACHE244_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE244_DATA'] = self.CACHE244_DATA
        self.CACHE245_DATA = RM_Register_MSC_CACHE245_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE245_DATA'] = self.CACHE245_DATA
        self.CACHE246_DATA = RM_Register_MSC_CACHE246_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE246_DATA'] = self.CACHE246_DATA
        self.CACHE247_DATA = RM_Register_MSC_CACHE247_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE247_DATA'] = self.CACHE247_DATA
        self.CACHE248_DATA = RM_Register_MSC_CACHE248_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE248_DATA'] = self.CACHE248_DATA
        self.CACHE249_DATA = RM_Register_MSC_CACHE249_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE249_DATA'] = self.CACHE249_DATA
        self.CACHE250_DATA = RM_Register_MSC_CACHE250_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE250_DATA'] = self.CACHE250_DATA
        self.CACHE251_DATA = RM_Register_MSC_CACHE251_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE251_DATA'] = self.CACHE251_DATA
        self.CACHE252_DATA = RM_Register_MSC_CACHE252_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE252_DATA'] = self.CACHE252_DATA
        self.CACHE253_DATA = RM_Register_MSC_CACHE253_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE253_DATA'] = self.CACHE253_DATA
        self.CACHE254_DATA = RM_Register_MSC_CACHE254_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE254_DATA'] = self.CACHE254_DATA
        self.CACHE255_DATA = RM_Register_MSC_CACHE255_DATA(self.zz_rmio, self.zz_label)
        self.zz_rdict['CACHE255_DATA'] = self.CACHE255_DATA
        self.__dict__['zz_frozen'] = True